{
 "title": "DLTS User Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "label_values(task_cpu_percent, username)"
   },
   {
    "name": "vc_name",
    "query": "label_values(task_cpu_percent{username=\"$username\"}, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of idle GPUs under  the user.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Assigned NPUs",
   "type": "singlestat",
   "description": "Number of NPUs assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active NPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle NPUs",
   "type": "singlestat",
   "description": "Number of idle GPUs under  the user.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "Device Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)",
     "legendFormat": "GPU Assigned"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "GPU Active"
    },
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "GPU Idle"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "NPU Assigned"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "NPU Active"
    },
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "NPU Idle"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  { "title": "NPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Assigned NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned GPUs to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Active NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  {
   "title": "Active NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) assigned to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  { "title": "Device Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Device Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "GPU Assigned"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "GPU Active"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "GPU VC Assigned"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "GPU VC Active"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "NPU Assigned"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "NPU Active"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "NPU VC Assigned"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "NPU VC Active"
    }
   ]
  },
  { "title": "Resource Per Active Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (avg by (uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU Memory",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 45 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Block In Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Network Inbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Network Outbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Resource Per Active Device Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Device Memory Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "CPU Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "Memory Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    }
   ]
  },
  {
   "title": "Network I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    }
   ]
  }
 ]
}