{
 "title": "DLTS Job Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "job_id",
    "query": "label_values(task_cpu_percent, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the job.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)) - (count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Assigned NPUs",
   "type": "singlestat",
   "description": "Number of NPUs assigned to the job.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active NPUs",
   "type": "singlestat",
   "description": "Number of active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle NPUs",
   "type": "singlestat",
   "description": "Number of active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (count(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the job in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  {
   "title": "Active Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the job over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  { "title": "NPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Assigned NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the job in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Active NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  {
   "title": "Active NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the job over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  { "title": "Resource Per Active Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU Memory",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) / count(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{job_name=\"$job_name\"}) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 29 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{job_name=\"$job_name\"}) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Block In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Network In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Network Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) / count(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Device Utilization",
   "type": "graph",
   "description": "Device utilization for all GPUs in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) by (minor_number, instance)",
     "legendFormat": "GPU {{'{{'}}minor_number{{'}}'}} on {{'{{'}}instance{{'}}'}}"
    },
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) by (minor_number, instance)",
     "legendFormat": "NPU {{'{{'}}minor_number{{'}}'}} on {{'{{'}}instance{{'}}'}}"
    }
   ]
  },
  {
   "title": "Device Memory Usage",
   "type": "graph",
   "description": "Device memory utilization for all Devices in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_mem_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) by (minor_number, instance)",
     "legendFormat": "GPU {{'{{'}}minor_number{{'}}'}} on {{'{{'}}instance{{'}}'}}"
    },
    {
     "expr": "avg(task_device_mem_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) by (minor_number, instance)",
     "legendFormat": "NPU {{'{{'}}minor_number{{'}}'}} on {{'{{'}}instance{{'}}'}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_cpu_percent{job_name=\"$job_name\"}) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(task_mem_usage_byte{job_name=\"$job_name\"}) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "description": "Disk IO rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}} In"
    },
    {
     "expr": "sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}} Out"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network I/O rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}} In"
    },
    {
     "expr": "sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{'{{'}}instance{{'}}'}} Out"
    }
   ]
  }
 ]
}