FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
RUN git clone --branch dev https://5ad9420031b357cdd1f9f9cea5022c19c0ea2da1@github.com/aurorazl/RemoteSensing-UI.git /RemoteSensing-UI
WORKDIR /RemoteSensing-UI/src/projects/WebUI/WebUI
RUN dotnet publish --configuration Release -r linux-x64

FROM alpine:3.11
WORKDIR /app
COPY --from=build-env /RemoteSensing-UI/src/projects/WebUI/WebUI/bin/Release/netcoreapp2.2/linux-x64 .

ENTRYPOINT ["WebUI","--urls=http://*:3080"]