FROM apulistech/dotnetcore-sdk:3.1-arm64 AS build-env
RUN git clone --branch arm https://0d7d3ce231a0f47c97b62c0d7e3ed1211f8218c3@github.com/apulistech/data-platform-backend.git /RemoteSensing-UI
WORKDIR /RemoteSensing-UI/src/projects/WebUI/WebUI
RUN dotnet publish --configuration Release

FROM apulistech/dotnetcore-runtime:3.1-arm64
WORKDIR /app
COPY --from=build-env /RemoteSensing-UI/src/projects/WebUI/WebUI/bin/Release/netcoreapp3.1/publish .