FROM apulistech/dotnetcore-sdk:3.1-arm64 AS build-env
RUN git clone --branch arm https://eb42b44ac8aad9d022c4ad5c8732a04c60bb91f6@github.com/apulistech/data-platform-backend.git /RemoteSensing-UI
WORKDIR /RemoteSensing-UI/src/projects/WebUI/WebUI
RUN dotnet publish --configuration Release

FROM apulistech/dotnetcore-runtime:3.1-arm64
WORKDIR /app
COPY --from=build-env /RemoteSensing-UI/src/projects/WebUI/WebUI/bin/Release/netcoreapp3.1/publish .