FROM apulistech/build_dotnetcore:0.1

RUN git clone --branch dev https://5ad9420031b357cdd1f9f9cea5022c19c0ea2da1@github.com/aurorazl/RemoteSensing-UI.git /RemoteSensing-UI
WORKDIR /RemoteSensing-UI/src/projects/WebUI
