// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  task_slot_cfg_reg_offset_field.h
// Department    :  CAD Development Department
// Author        :  Yau Shek Fan
// Version       :  1.0
// Date          :  2017/7/10
// Description   :  The description of Hi1910 project
// Others        :  Generated automatically by nManager V4.2 
// History       :  Yau Shek Fan 2018/03/19 11:46:49 Create file
// ******************************************************************************

#ifndef __TASK_SLOT_CFG_REG_OFFSET_FIELD_H__
#define __TASK_SLOT_CFG_REG_OFFSET_FIELD_H__

#define TASK_SLOT_CFG_DEPENDENT_TASK_SLOT_ID_LEN    5
#define TASK_SLOT_CFG_DEPENDENT_TASK_SLOT_ID_OFFSET 24
#define TASK_SLOT_CFG_DEPENDENT_EN_LEN              1
#define TASK_SLOT_CFG_DEPENDENT_EN_OFFSET           16
#define TASK_SLOT_CFG_DFX_MODE_EN_LEN               1
#define TASK_SLOT_CFG_DFX_MODE_EN_OFFSET            8
#define TASK_SLOT_CFG_OVERRIDE_MODE_LEN             2
#define TASK_SLOT_CFG_OVERRIDE_MODE_OFFSET          2
#define TASK_SLOT_CFG_PROFILING_EN_LEN              1
#define TASK_SLOT_CFG_PROFILING_EN_OFFSET           1
#define TASK_SLOT_CFG_TASKSLOT_EN_LEN               1
#define TASK_SLOT_CFG_TASKSLOT_EN_OFFSET            0

#define TASK_SLOT_CFG_TASK_TERMINATE_LEN       1
#define TASK_SLOT_CFG_TASK_TERMINATE_OFFSET    7
#define TASK_SLOT_CFG_DFX_RESUME_LEN           1
#define TASK_SLOT_CFG_DFX_RESUME_OFFSET        6
#define TASK_SLOT_CFG_TASK_PAUSE_RESUME_LEN    1
#define TASK_SLOT_CFG_TASK_PAUSE_RESUME_OFFSET 5
#define TASK_SLOT_CFG_TASK_PAUSE_LEN           1
#define TASK_SLOT_CFG_TASK_PAUSE_OFFSET        4
#define TASK_SLOT_CFG_DEBUG_PAUSE_LEN          1
#define TASK_SLOT_CFG_DEBUG_PAUSE_OFFSET       3
#define TASK_SLOT_CFG_TASK_KILL_LEN            1
#define TASK_SLOT_CFG_TASK_KILL_OFFSET         2
#define TASK_SLOT_CFG_EXCPETION_HANDLED_LEN    1
#define TASK_SLOT_CFG_EXCPETION_HANDLED_OFFSET 1
#define TASK_SLOT_CFG_DEBUG_RESUME_LEN         1
#define TASK_SLOT_CFG_DEBUG_RESUME_OFFSET      0

#define TASK_SLOT_CFG_TS_SECURE_LEN    3
#define TASK_SLOT_CFG_TS_SECURE_OFFSET 0

#define TASK_SLOT_CFG_ALLOC_GOAL_LEN    6
#define TASK_SLOT_CFG_ALLOC_GOAL_OFFSET 0

#define TASK_SLOT_CFG_CORE_ASSIGN_LEN    32
#define TASK_SLOT_CFG_CORE_ASSIGN_OFFSET 0

#define TASK_SLOT_CFG_ALLOC_GOAL_OVERRIDE_LEN    6
#define TASK_SLOT_CFG_ALLOC_GOAL_OVERRIDE_OFFSET 0

#define TASK_SLOT_CFG_CORE_ASSIGN_OVERRIDE_LEN    32
#define TASK_SLOT_CFG_CORE_ASSIGN_OVERRIDE_OFFSET 0

#define TASK_SLOT_CFG_CUR_CORE_USAGE_LEN    32
#define TASK_SLOT_CFG_CUR_CORE_USAGE_OFFSET 0

#define TASK_SLOT_CFG_TSC_STATE_LEN     3
#define TASK_SLOT_CFG_TSC_STATE_OFFSET  8
#define TASK_SLOT_CFG_KICK_STATE_LEN    2
#define TASK_SLOT_CFG_KICK_STATE_OFFSET 0

#define TASK_SLOT_CFG_DFX_CODE_LEN    8
#define TASK_SLOT_CFG_DFX_CODE_OFFSET 0

#define TASK_SLOT_CFG_TERM_CODE_LEN    8
#define TASK_SLOT_CFG_TERM_CODE_OFFSET 0

#define TASK_SLOT_CFG_DEBUG_BITMAP_LEN    32
#define TASK_SLOT_CFG_DEBUG_BITMAP_OFFSET 0

#define TASK_SLOT_CFG_EXCEPTION_BITMAP_LEN    32
#define TASK_SLOT_CFG_EXCEPTION_BITMAP_OFFSET 0

#define TASK_SLOT_CFG_NEXT_BLOCK_ID_LEN    16
#define TASK_SLOT_CFG_NEXT_BLOCK_ID_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_0_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_0_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_1_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_1_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_2_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_2_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_3_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_3_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_4_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_4_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_5_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_5_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_6_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_6_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_7_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_7_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_8_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_8_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_9_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_9_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_10_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_10_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_11_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_11_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_12_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_12_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_13_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_13_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_14_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_14_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_15_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_15_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_16_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_16_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_17_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_17_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_18_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_18_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_19_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_19_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_20_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_20_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_21_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_21_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_22_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_22_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_23_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_23_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_24_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_24_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_25_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_25_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_26_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_26_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_27_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_27_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_28_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_28_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_29_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_29_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_30_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_30_OFFSET 0

#define TASK_SLOT_CFG_CUR_BLOCK_ID_31_LEN    17
#define TASK_SLOT_CFG_CUR_BLOCK_ID_31_OFFSET 0

#define TASK_SLOT_CFG_TASK_PRIORITY_LEN    3
#define TASK_SLOT_CFG_TASK_PRIORITY_OFFSET 0

#define TASK_SLOT_CFG_HBM_WEIGHT_LEN    3
#define TASK_SLOT_CFG_HBM_WEIGHT_OFFSET 16
#define TASK_SLOT_CFG_L2_WEIGHT_LEN     3
#define TASK_SLOT_CFG_L2_WEIGHT_OFFSET  0

#define TASK_SLOT_CFG_MIN_NUM_CORE_LEN    6
#define TASK_SLOT_CFG_MIN_NUM_CORE_OFFSET 0

#define TASK_SLOT_CFG_PC_START_LO_LEN    32
#define TASK_SLOT_CFG_PC_START_LO_OFFSET 0

#define TASK_SLOT_CFG_PC_START_HI_LEN    32
#define TASK_SLOT_CFG_PC_START_HI_OFFSET 0

#define TASK_SLOT_CFG_PARAM_BASE_LO_LEN    32
#define TASK_SLOT_CFG_PARAM_BASE_LO_OFFSET 0

#define TASK_SLOT_CFG_PARAM_BASE_HI_LEN    32
#define TASK_SLOT_CFG_PARAM_BASE_HI_OFFSET 0

#define TASK_SLOT_CFG_SMMU_SSID_LEN    16
#define TASK_SLOT_CFG_SMMU_SSID_OFFSET 0

#define TASK_SLOT_CFG_L2_IN_MAIN_LEN    8
#define TASK_SLOT_CFG_L2_IN_MAIN_OFFSET 0

#define TASK_SLOT_CFG_BLK_DIM_LEN    16
#define TASK_SLOT_CFG_BLK_DIM_OFFSET 0

#define TASK_SLOT_CFG_DATA_MAIN_BASE_LO_LEN    32
#define TASK_SLOT_CFG_DATA_MAIN_BASE_LO_OFFSET 0

#define TASK_SLOT_CFG_DATA_MAIN_BASE_HI_LEN    32
#define TASK_SLOT_CFG_DATA_MAIN_BASE_HI_OFFSET 0

#define TASK_SLOT_CFG_UB_BASE_LEN    32
#define TASK_SLOT_CFG_UB_BASE_OFFSET 0

#define TASK_SLOT_CFG_DATA_SIZE_LEN    32
#define TASK_SLOT_CFG_DATA_SIZE_OFFSET 0

#define TASK_SLOT_CFG_L2_VADDR_BASE_LO_LEN    32
#define TASK_SLOT_CFG_L2_VADDR_BASE_LO_OFFSET 0

#define TASK_SLOT_CFG_L2_VADDR_BASE_HI_LEN    32
#define TASK_SLOT_CFG_L2_VADDR_BASE_HI_OFFSET 0

#define TASK_SLOT_CFG_NUM_PAGE_VALID_LEN    7
#define TASK_SLOT_CFG_NUM_PAGE_VALID_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_0_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_0_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_1_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_1_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_2_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_2_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_3_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_3_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_4_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_4_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_5_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_5_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_6_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_6_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_7_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_7_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_8_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_8_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_9_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_9_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_10_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_10_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_11_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_11_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_12_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_12_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_13_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_13_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_14_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_14_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_15_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_15_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_16_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_16_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_17_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_17_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_18_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_18_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_19_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_19_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_20_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_20_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_21_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_21_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_22_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_22_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_23_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_23_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_24_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_24_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_25_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_25_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_26_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_26_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_27_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_27_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_28_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_28_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_29_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_29_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_30_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_30_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_31_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_31_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_32_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_32_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_33_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_33_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_34_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_34_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_35_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_35_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_36_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_36_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_37_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_37_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_38_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_38_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_39_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_39_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_40_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_40_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_41_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_41_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_42_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_42_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_43_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_43_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_44_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_44_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_45_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_45_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_46_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_46_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_47_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_47_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_48_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_48_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_49_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_49_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_50_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_50_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_51_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_51_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_52_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_52_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_53_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_53_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_54_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_54_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_55_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_55_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_56_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_56_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_57_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_57_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_58_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_58_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_59_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_59_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_60_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_60_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_61_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_61_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_62_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_62_OFFSET 0

#define TASK_SLOT_CFG_L2_REMAP_ADDR_63_LEN    8
#define TASK_SLOT_CFG_L2_REMAP_ADDR_63_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_0_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_0_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_1_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_1_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_2_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_2_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_3_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_3_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_4_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_4_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_5_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_5_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_6_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_6_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_LO_7_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_LO_7_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_0_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_0_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_1_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_1_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_2_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_2_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_3_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_3_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_4_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_4_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_5_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_5_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_6_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_6_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CNT_HI_7_LEN    32
#define TASK_SLOT_CFG_PROFILING_CNT_HI_7_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CYC_CNT_LO_LEN    32
#define TASK_SLOT_CFG_PROFILING_CYC_CNT_LO_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_CYC_CNT_HI_LEN    32
#define TASK_SLOT_CFG_PROFILING_CYC_CNT_HI_OFFSET 0

#define TASK_SLOT_CFG_OVERFLOW_CYC_CNT_LO_LEN    32
#define TASK_SLOT_CFG_OVERFLOW_CYC_CNT_LO_OFFSET 0

#define TASK_SLOT_CFG_OVERFLOW_CYC_CNT_HI_LEN    32
#define TASK_SLOT_CFG_OVERFLOW_CYC_CNT_HI_OFFSET 0

#define TASK_SLOT_CFG_OVERFLOW_OCCUR_LEN    1
#define TASK_SLOT_CFG_OVERFLOW_OCCUR_OFFSET 0

#define TASK_SLOT_CFG_PROFILING_RANGE_EN_LEN    1
#define TASK_SLOT_CFG_PROFILING_RANGE_EN_OFFSET 0

#define TASK_SLOT_CFG_PROFILE_STOP_BLK_NUM_LEN     16
#define TASK_SLOT_CFG_PROFILE_STOP_BLK_NUM_OFFSET  16
#define TASK_SLOT_CFG_PROFILE_START_BLK_NUM_LEN    16
#define TASK_SLOT_CFG_PROFILE_START_BLK_NUM_OFFSET 0

#endif // __TASK_SLOT_CFG_REG_OFFSET_FIELD_H__
