// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  hipciec_nvme_pf_local_ctrl_reg_reg_offset_field.h
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1.0
// Date          :  2017/10/24
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2018/07/13 11:22:03 Create file
// ******************************************************************************

#ifndef __HIPCIEC_NVME_PF_LOCAL_CTRL_REG_REG_OFFSET_FIELD_H__
#define __HIPCIEC_NVME_PF_LOCAL_CTRL_REG_REG_OFFSET_FIELD_H__

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_TIMEOUT_LEN    8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_TIMEOUT_OFFSET 24
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_AMS_LEN        2
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_AMS_OFFSET     17
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQR_LEN        1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQR_OFFSET     16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MQES_LEN       16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MQES_OFFSET    0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPSMAX_LEN    4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPSMAX_OFFSET 20
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPSMIN_LEN    4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPSMIN_OFFSET 16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CSS_LEN       8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CSS_OFFSET    5
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRS_LEN     1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRS_OFFSET  4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_DSTRD_LEN     4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_DSTRD_OFFSET  0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MJR_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MJR_OFFSET 16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MNR_LEN    8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MNR_OFFSET 8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_TER_LEN    8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_TER_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_INTMS_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_INTMS_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_INTMC_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_INTMC_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_IOCQES_LEN    4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_IOCQES_OFFSET 20
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_IOSQES_LEN    4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_IOSQES_OFFSET 16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SHN_LEN       2
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SHN_OFFSET    14
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_AMS_LEN       3
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_AMS_OFFSET    11
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPS_LEN       4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_MPS_OFFSET    7
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CSS_LEN       3
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CSS_OFFSET    4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ENABLE_LEN    1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ENABLE_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_PP_LEN       1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_PP_OFFSET    5
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRO_LEN    1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRO_OFFSET 4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SHST_LEN     2
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SHST_OFFSET  2
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CFS_LEN      1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CFS_OFFSET   1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_READY_LEN    1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_READY_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRC_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_NSSRC_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQS_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQS_OFFSET 16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQS_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQS_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQB_LOW_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQB_LOW_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQB_HIGH_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ASQB_HIGH_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQB_LOW_LEN    20
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQB_LOW_OFFSET 12

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQB_HIGH_LEN    32
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_ACQB_HIGH_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_OFFSET_LEN    20
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_OFFSET_OFFSET 12
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_BIR_LEN       3
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_BIR_OFFSET    0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SZ_LEN       20
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SZ_OFFSET    12
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SZU_LEN      4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SZU_OFFSET   8
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_WDS_LEN      1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_WDS_OFFSET   4
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_RDS_LEN      1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_RDS_OFFSET   3
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_LISTS_LEN    1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_LISTS_OFFSET 2
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQS_LEN      1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQS_OFFSET   1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQS_LEN      1
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQS_OFFSET   0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_0_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_0_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_1_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_1_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_2_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_2_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_3_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_3_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_4_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_4_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_5_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_5_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_6_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_6_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_7_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_7_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_8_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_8_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_9_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_9_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_10_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_10_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_11_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_11_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_12_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_12_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_13_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_13_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_14_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_14_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_15_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_15_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_16_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_16_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_17_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_17_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_18_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_18_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_19_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_19_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_20_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_20_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_21_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_21_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_22_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_22_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_23_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_23_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_24_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_24_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_25_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_25_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_26_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_26_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_27_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_27_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_28_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_28_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_29_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_29_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_30_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_30_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_31_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_31_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_32_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_32_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_33_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_33_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_34_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_34_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_35_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_35_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_36_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_36_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_37_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_37_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_38_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_38_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_39_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_39_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_40_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_40_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_41_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_41_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_42_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_42_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_43_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_43_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_44_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_44_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_45_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_45_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_46_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_46_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_47_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_47_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_48_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_48_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_49_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_49_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_50_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_50_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_51_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_51_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_52_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_52_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_53_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_53_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_54_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_54_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_55_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_55_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_56_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_56_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_57_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_57_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_58_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_58_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_59_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_59_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_60_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_60_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_61_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_61_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_62_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_62_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_63_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_63_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_64_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_64_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_65_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_65_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_66_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_66_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_67_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_67_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_68_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_68_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_69_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_69_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_70_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_70_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_71_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_71_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_72_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_72_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_73_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_73_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_74_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_74_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_75_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_75_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_76_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_76_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_77_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_77_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_78_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_78_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_79_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_79_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_80_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_80_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_81_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_81_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_82_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_82_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_83_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_83_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_84_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_84_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_85_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_85_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_86_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_86_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_87_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_87_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_88_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_88_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_89_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_89_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_90_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_90_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_91_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_91_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_92_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_92_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_93_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_93_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_94_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_94_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_95_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_95_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_96_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_96_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_97_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_97_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_98_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_98_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_99_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_99_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_100_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_100_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_101_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_101_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_102_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_102_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_103_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_103_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_104_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_104_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_105_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_105_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_106_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_106_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_107_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_107_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_108_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_108_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_109_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_109_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_110_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_110_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_111_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_111_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_112_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_112_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_113_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_113_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_114_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_114_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_115_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_115_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_116_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_116_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_117_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_117_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_118_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_118_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_119_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_119_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_120_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_120_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_121_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_121_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_122_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_122_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_123_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_123_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_124_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_124_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_125_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_125_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_126_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_126_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_127_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_SQTDBL_127_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_0_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_0_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_1_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_1_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_2_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_2_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_3_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_3_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_4_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_4_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_5_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_5_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_6_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_6_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_7_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_7_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_8_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_8_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_9_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_9_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_10_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_10_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_11_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_11_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_12_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_12_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_13_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_13_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_14_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_14_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_15_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_15_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_16_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_16_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_17_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_17_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_18_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_18_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_19_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_19_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_20_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_20_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_21_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_21_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_22_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_22_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_23_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_23_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_24_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_24_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_25_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_25_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_26_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_26_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_27_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_27_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_28_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_28_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_29_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_29_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_30_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_30_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_31_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_31_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_32_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_32_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_33_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_33_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_34_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_34_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_35_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_35_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_36_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_36_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_37_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_37_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_38_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_38_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_39_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_39_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_40_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_40_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_41_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_41_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_42_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_42_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_43_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_43_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_44_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_44_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_45_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_45_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_46_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_46_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_47_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_47_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_48_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_48_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_49_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_49_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_50_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_50_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_51_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_51_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_52_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_52_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_53_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_53_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_54_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_54_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_55_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_55_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_56_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_56_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_57_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_57_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_58_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_58_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_59_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_59_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_60_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_60_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_61_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_61_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_62_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_62_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_63_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_63_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_64_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_64_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_65_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_65_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_66_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_66_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_67_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_67_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_68_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_68_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_69_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_69_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_70_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_70_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_71_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_71_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_72_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_72_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_73_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_73_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_74_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_74_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_75_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_75_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_76_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_76_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_77_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_77_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_78_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_78_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_79_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_79_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_80_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_80_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_81_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_81_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_82_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_82_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_83_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_83_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_84_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_84_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_85_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_85_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_86_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_86_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_87_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_87_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_88_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_88_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_89_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_89_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_90_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_90_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_91_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_91_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_92_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_92_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_93_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_93_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_94_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_94_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_95_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_95_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_96_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_96_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_97_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_97_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_98_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_98_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_99_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_99_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_100_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_100_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_101_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_101_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_102_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_102_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_103_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_103_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_104_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_104_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_105_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_105_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_106_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_106_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_107_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_107_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_108_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_108_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_109_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_109_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_110_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_110_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_111_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_111_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_112_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_112_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_113_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_113_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_114_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_114_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_115_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_115_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_116_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_116_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_117_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_117_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_118_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_118_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_119_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_119_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_120_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_120_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_121_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_121_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_122_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_122_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_123_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_123_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_124_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_124_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_125_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_125_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_126_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_126_OFFSET 0

#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_127_LEN    16
#define HIPCIEC_NVME_PF_LOCAL_CTRL_REG_CQHDBL_127_OFFSET 0

#endif // __HIPCIEC_NVME_PF_LOCAL_CTRL_REG_REG_OFFSET_FIELD_H__
