// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  misc_up_cfg_reg_offset_field.h
// Project line  :  ICT
// Department    :  ICT Processor Chipset Development Dep
// Author        :huawei
// Version       :  1.0
// Date          :  2018/7/2
// Description   :  The description of CLOUD project
// Others        :  Generated automatically by nManager V4.2 
// History       :huawei 2018/11/09 16:35:42 Create file
// ******************************************************************************

#ifndef __MISC_UP_CFG_REG_OFFSET_FIELD_H__
#define __MISC_UP_CFG_REG_OFFSET_FIELD_H__

#define MISC_UP_CFG_RESERVED_0_LEN     31
#define MISC_UP_CFG_RESERVED_0_OFFSET  1
#define MISC_UP_CFG_SC_PLL7_SEL_LEN    1
#define MISC_UP_CFG_SC_PLL7_SEL_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN            1
#define MISC_UP_CFG_RESERVED_0_OFFSET         31
#define MISC_UP_CFG_PLL7_FOUTVCOEN_LEN        1
#define MISC_UP_CFG_PLL7_FOUTVCOEN_OFFSET     30
#define MISC_UP_CFG_PLL7_FOUTPOSTDIVEN_LEN    1
#define MISC_UP_CFG_PLL7_FOUTPOSTDIVEN_OFFSET 29
#define MISC_UP_CFG_PLL7_FOUT4PHASEEN_LEN     1
#define MISC_UP_CFG_PLL7_FOUT4PHASEEN_OFFSET  28
#define MISC_UP_CFG_PLL7_DACEN_LEN            1
#define MISC_UP_CFG_PLL7_DACEN_OFFSET         27
#define MISC_UP_CFG_PLL7_DSMEN_LEN            1
#define MISC_UP_CFG_PLL7_DSMEN_OFFSET         26
#define MISC_UP_CFG_PLL7_EN_LEN               1
#define MISC_UP_CFG_PLL7_EN_OFFSET            25
#define MISC_UP_CFG_PLL7_BYPASS_LEN           1
#define MISC_UP_CFG_PLL7_BYPASS_OFFSET        24
#define MISC_UP_CFG_PLL7_POSTDIV2_LEN         3
#define MISC_UP_CFG_PLL7_POSTDIV2_OFFSET      21
#define MISC_UP_CFG_PLL7_POSTDIV1_LEN         3
#define MISC_UP_CFG_PLL7_POSTDIV1_OFFSET      18
#define MISC_UP_CFG_PLL7_FBDIV_LEN            12
#define MISC_UP_CFG_PLL7_FBDIV_OFFSET         6
#define MISC_UP_CFG_PLL7_REFDIV_LEN           6
#define MISC_UP_CFG_PLL7_REFDIV_OFFSET        0

#define MISC_UP_CFG_RESERVED_0_LEN    6
#define MISC_UP_CFG_RESERVED_0_OFFSET 26
#define MISC_UP_CFG_PLL7_FRAC_LEN     26
#define MISC_UP_CFG_PLL7_FRAC_OFFSET  0

#define MISC_UP_CFG_RESERVED_0_LEN              18
#define MISC_UP_CFG_RESERVED_0_OFFSET           14
#define MISC_UP_CFG_DTC_M_CFG_FNPLL_1V2_LEN     6
#define MISC_UP_CFG_DTC_M_CFG_FNPLL_1V2_OFFSET  8
#define MISC_UP_CFG_RESERVED_1_LEN              2
#define MISC_UP_CFG_RESERVED_1_OFFSET           6
#define MISC_UP_CFG_PHE_SEL_IN_FNPLL_1V2_LEN    2
#define MISC_UP_CFG_PHE_SEL_IN_FNPLL_1V2_OFFSET 4
#define MISC_UP_CFG_RESERVED_2_LEN              2
#define MISC_UP_CFG_RESERVED_2_OFFSET           2
#define MISC_UP_CFG_DTC_TEST_FNPLL_1V2_LEN      1
#define MISC_UP_CFG_DTC_TEST_FNPLL_1V2_OFFSET   1
#define MISC_UP_CFG_PHE_SEL_EN_FNPLL_1V2_LEN    1
#define MISC_UP_CFG_PHE_SEL_EN_FNPLL_1V2_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN               21
#define MISC_UP_CFG_RESERVED_0_OFFSET            11
#define MISC_UP_CFG_SPREAD_FNPLL_1V2_LEN         3
#define MISC_UP_CFG_SPREAD_FNPLL_1V2_OFFSET      8
#define MISC_UP_CFG_DIVVAL_FNPLL_1V2_LEN         4
#define MISC_UP_CFG_DIVVAL_FNPLL_1V2_OFFSET      4
#define MISC_UP_CFG_RESERVED_1_LEN               1
#define MISC_UP_CFG_RESERVED_1_OFFSET            3
#define MISC_UP_CFG_SEL_EXTWAVE_FNPLL_1V2_LEN    1
#define MISC_UP_CFG_SEL_EXTWAVE_FNPLL_1V2_OFFSET 2
#define MISC_UP_CFG_DOWNSPREAD_FNPLL_1V2_LEN     1
#define MISC_UP_CFG_DOWNSPREAD_FNPLL_1V2_OFFSET  1
#define MISC_UP_CFG_SPREAD_EN_FNPLL_1V2_LEN      1
#define MISC_UP_CFG_SPREAD_EN_FNPLL_1V2_OFFSET   0

#define MISC_UP_CFG_RESERVED_0_LEN               16
#define MISC_UP_CFG_RESERVED_0_OFFSET            16
#define MISC_UP_CFG_EXTWAVEVAL_FNPLL_1V2_LEN     8
#define MISC_UP_CFG_EXTWAVEVAL_FNPLL_1V2_OFFSET  8
#define MISC_UP_CFG_EXT_MAXADDR_FNPLL_1V2_LEN    8
#define MISC_UP_CFG_EXT_MAXADDR_FNPLL_1V2_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN                   17
#define MISC_UP_CFG_RESERVED_0_OFFSET                15
#define MISC_UP_CFG_FBDIV_DELAY_NUM_FNPLL_1V2_LEN    7
#define MISC_UP_CFG_FBDIV_DELAY_NUM_FNPLL_1V2_OFFSET 8
#define MISC_UP_CFG_LOCK_EN_FNPLL_1V2_LEN            1
#define MISC_UP_CFG_LOCK_EN_FNPLL_1V2_OFFSET         7
#define MISC_UP_CFG_DIV2_PD_FNPLL_1V2_LEN            1
#define MISC_UP_CFG_DIV2_PD_FNPLL_1V2_OFFSET         6
#define MISC_UP_CFG_FBDIV_RST_N_FNPLL_1V2_LEN        1
#define MISC_UP_CFG_FBDIV_RST_N_FNPLL_1V2_OFFSET     5
#define MISC_UP_CFG_REFDIV_RST_N_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_REFDIV_RST_N_FNPLL_1V2_OFFSET    4
#define MISC_UP_CFG_LOCK_THR_FNPLL_1V2_LEN           2
#define MISC_UP_CFG_LOCK_THR_FNPLL_1V2_OFFSET        2
#define MISC_UP_CFG_TEST_MODE_FNPLL_1V2_LEN          1
#define MISC_UP_CFG_TEST_MODE_FNPLL_1V2_OFFSET       1
#define MISC_UP_CFG_INPUT_CFG_EN_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_INPUT_CFG_EN_FNPLL_1V2_OFFSET    0

#define MISC_UP_CFG_RESERVED_0_LEN                   19
#define MISC_UP_CFG_RESERVED_0_OFFSET                13
#define MISC_UP_CFG_CTINUE_LOCK_NUM_FNPLL_1V2_LEN    5
#define MISC_UP_CFG_CTINUE_LOCK_NUM_FNPLL_1V2_OFFSET 8
#define MISC_UP_CFG_PHE_CODE_B_FNPLL_1V2_LEN         2
#define MISC_UP_CFG_PHE_CODE_B_FNPLL_1V2_OFFSET      6
#define MISC_UP_CFG_PHE_CODE_A_FNPLL_1V2_LEN         2
#define MISC_UP_CFG_PHE_CODE_A_FNPLL_1V2_OFFSET      4
#define MISC_UP_CFG_RESERVED_1_LEN                   1
#define MISC_UP_CFG_RESERVED_1_OFFSET                3
#define MISC_UP_CFG_DLL_FORCE_EN_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_DLL_FORCE_EN_FNPLL_1V2_OFFSET    2
#define MISC_UP_CFG_DTC_CTRL_INV_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_DTC_CTRL_INV_FNPLL_1V2_OFFSET    1
#define MISC_UP_CFG_BBPD_CALIB_BYP_FNPLL_1V2_LEN     1
#define MISC_UP_CFG_BBPD_CALIB_BYP_FNPLL_1V2_OFFSET  0

#define MISC_UP_CFG_RESERVED_0_LEN                 18
#define MISC_UP_CFG_RESERVED_0_OFFSET              14
#define MISC_UP_CFG_K_GAIN_CFG_FNPLL_1V2_LEN       6
#define MISC_UP_CFG_K_GAIN_CFG_FNPLL_1V2_OFFSET    8
#define MISC_UP_CFG_RESERVED_1_LEN                 1
#define MISC_UP_CFG_RESERVED_1_OFFSET              7
#define MISC_UP_CFG_K_GAIN_AV_THR_FNPLL_1V2_LEN    3
#define MISC_UP_CFG_K_GAIN_AV_THR_FNPLL_1V2_OFFSET 4
#define MISC_UP_CFG_RESERVED_2_LEN                 2
#define MISC_UP_CFG_RESERVED_2_OFFSET              2
#define MISC_UP_CFG_K_GAIN_CFG_EN_FNPLL_1V2_LEN    1
#define MISC_UP_CFG_K_GAIN_CFG_EN_FNPLL_1V2_OFFSET 1
#define MISC_UP_CFG_READ_EN_FNPLL_1V2_LEN          1
#define MISC_UP_CFG_READ_EN_FNPLL_1V2_OFFSET       0

#define MISC_UP_CFG_RESERVED_0_LEN                 16
#define MISC_UP_CFG_RESERVED_0_OFFSET              16
#define MISC_UP_CFG_BBPD_LOCK_NUM_FNPLL_1V2_LEN    8
#define MISC_UP_CFG_BBPD_LOCK_NUM_FNPLL_1V2_OFFSET 8
#define MISC_UP_CFG_RESERVED_1_LEN                 2
#define MISC_UP_CFG_RESERVED_1_OFFSET              6
#define MISC_UP_CFG_DTC_O_CFG_FNPLL_1V2_LEN        6
#define MISC_UP_CFG_DTC_O_CFG_FNPLL_1V2_OFFSET     0

#define MISC_UP_CFG_RESERVED_0_LEN                 17
#define MISC_UP_CFG_RESERVED_0_OFFSET              15
#define MISC_UP_CFG_CALIB_LPF_BW1_FNPLL_1V2_LEN    3
#define MISC_UP_CFG_CALIB_LPF_BW1_FNPLL_1V2_OFFSET 12
#define MISC_UP_CFG_RESERVED_1_LEN                 1
#define MISC_UP_CFG_RESERVED_1_OFFSET              11
#define MISC_UP_CFG_CALIB_LPF_BW_FNPLL_1V2_LEN     3
#define MISC_UP_CFG_CALIB_LPF_BW_FNPLL_1V2_OFFSET  8
#define MISC_UP_CFG_RESERVED_2_LEN                 1
#define MISC_UP_CFG_RESERVED_2_OFFSET              7
#define MISC_UP_CFG_LPF_BW1_FNPLL_1V2_LEN          3
#define MISC_UP_CFG_LPF_BW1_FNPLL_1V2_OFFSET       4
#define MISC_UP_CFG_RESERVED_3_LEN                 1
#define MISC_UP_CFG_RESERVED_3_OFFSET              3
#define MISC_UP_CFG_LPF_BW_FNPLL_1V2_LEN           3
#define MISC_UP_CFG_LPF_BW_FNPLL_1V2_OFFSET        0

#define MISC_UP_CFG_RESERVED_0_LEN              18
#define MISC_UP_CFG_RESERVED_0_OFFSET           14
#define MISC_UP_CFG_MIN_K_GAIN_FNPLL_1V2_LEN    6
#define MISC_UP_CFG_MIN_K_GAIN_FNPLL_1V2_OFFSET 8
#define MISC_UP_CFG_RESERVED_1_LEN              2
#define MISC_UP_CFG_RESERVED_1_OFFSET           6
#define MISC_UP_CFG_MAX_K_GAIN_FNPLL_1V2_LEN    6
#define MISC_UP_CFG_MAX_K_GAIN_FNPLL_1V2_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN                 16
#define MISC_UP_CFG_RESERVED_0_OFFSET              16
#define MISC_UP_CFG_TEST_DATA_SEL_FNPLL_1V2_LEN    4
#define MISC_UP_CFG_TEST_DATA_SEL_FNPLL_1V2_OFFSET 12
#define MISC_UP_CFG_RESERVED_1_LEN                 4
#define MISC_UP_CFG_RESERVED_1_OFFSET              8
#define MISC_UP_CFG_VDC_SEL_FNPLL_1V2_LEN          4
#define MISC_UP_CFG_VDC_SEL_FNPLL_1V2_OFFSET       4
#define MISC_UP_CFG_RESERVED_2_LEN                 1
#define MISC_UP_CFG_RESERVED_2_OFFSET              3
#define MISC_UP_CFG_ICP_CTRL_FNPLL_1V2_LEN         1
#define MISC_UP_CFG_ICP_CTRL_FNPLL_1V2_OFFSET      2
#define MISC_UP_CFG_UPDN_SEL_FNPLL_1V2_LEN         1
#define MISC_UP_CFG_UPDN_SEL_FNPLL_1V2_OFFSET      1
#define MISC_UP_CFG_EN_DAC_TEST_FNPLL_1V2_LEN      1
#define MISC_UP_CFG_EN_DAC_TEST_FNPLL_1V2_OFFSET   0

#define MISC_UP_CFG_RESERVED_0_LEN                24
#define MISC_UP_CFG_RESERVED_0_OFFSET             8
#define MISC_UP_CFG_REF_LOST_THR_FNPLL_1V2_LEN    8
#define MISC_UP_CFG_REF_LOST_THR_FNPLL_1V2_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN               1
#define MISC_UP_CFG_RESERVED_0_OFFSET            31
#define MISC_UP_CFG_PLL7_HI_FOUTVCOPD_LEN        1
#define MISC_UP_CFG_PLL7_HI_FOUTVCOPD_OFFSET     30
#define MISC_UP_CFG_PLL7_HI_FOUTPOSTDIVPD_LEN    1
#define MISC_UP_CFG_PLL7_HI_FOUTPOSTDIVPD_OFFSET 29
#define MISC_UP_CFG_PLL7_HI_FOUT4PHASEPD_LEN     1
#define MISC_UP_CFG_PLL7_HI_FOUT4PHASEPD_OFFSET  28
#define MISC_UP_CFG_PLL7_HI_DLL_EN_LEN           1
#define MISC_UP_CFG_PLL7_HI_DLL_EN_OFFSET        27
#define MISC_UP_CFG_PLL7_HI_MODE_LEN             1
#define MISC_UP_CFG_PLL7_HI_MODE_OFFSET          26
#define MISC_UP_CFG_PLL7_HI_PD_LEN               1
#define MISC_UP_CFG_PLL7_HI_PD_OFFSET            25
#define MISC_UP_CFG_PLL7_HI_BYPASS_LEN           1
#define MISC_UP_CFG_PLL7_HI_BYPASS_OFFSET        24
#define MISC_UP_CFG_PLL7_HI_POSTDIV2_LEN         3
#define MISC_UP_CFG_PLL7_HI_POSTDIV2_OFFSET      21
#define MISC_UP_CFG_PLL7_HI_POSTDIV1_LEN         3
#define MISC_UP_CFG_PLL7_HI_POSTDIV1_OFFSET      18
#define MISC_UP_CFG_PLL7_HI_FBDIV_LEN            12
#define MISC_UP_CFG_PLL7_HI_FBDIV_OFFSET         6
#define MISC_UP_CFG_PLL7_HI_REFDIV_LEN           6
#define MISC_UP_CFG_PLL7_HI_REFDIV_OFFSET        0

#define MISC_UP_CFG_RESERVED_0_LEN      6
#define MISC_UP_CFG_RESERVED_0_OFFSET   26
#define MISC_UP_CFG_PLL7_HI_FRAC_LEN    26
#define MISC_UP_CFG_PLL7_HI_FRAC_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN                31
#define MISC_UP_CFG_RESERVED_0_OFFSET             1
#define MISC_UP_CFG_PLL7_BYPASS_EXTERNAL_N_LEN    1
#define MISC_UP_CFG_PLL7_BYPASS_EXTERNAL_N_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN        31
#define MISC_UP_CFG_RESERVED_0_OFFSET     1
#define MISC_UP_CFG_PLL7_PERI_MODE_LEN    1
#define MISC_UP_CFG_PLL7_PERI_MODE_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN              16
#define MISC_UP_CFG_RESERVED_0_OFFSET           16
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC31_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC31_OFFSET 15
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC29_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC29_OFFSET 14
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC27_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC27_OFFSET 13
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC25_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC25_OFFSET 12
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC23_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC23_OFFSET 11
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC21_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC21_OFFSET 10
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC19_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC19_OFFSET 9
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC17_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC17_OFFSET 8
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC15_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC15_OFFSET 7
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC13_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC13_OFFSET 6
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC11_LEN    1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC11_OFFSET 5
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC9_LEN     1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC9_OFFSET  4
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC7_LEN     1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC7_OFFSET  3
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC5_LEN     1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC5_OFFSET  2
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC3_LEN     1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC3_OFFSET  1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC1_LEN     1
#define MISC_UP_CFG_SC_SRST_REQ_HW_AIC1_OFFSET  0

#define MISC_UP_CFG_RESERVED_0_LEN               16
#define MISC_UP_CFG_RESERVED_0_OFFSET            16
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC31_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC31_OFFSET 15
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC29_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC29_OFFSET 14
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC27_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC27_OFFSET 13
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC25_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC25_OFFSET 12
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC23_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC23_OFFSET 11
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC21_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC21_OFFSET 10
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC19_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC19_OFFSET 9
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC17_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC17_OFFSET 8
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC15_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC15_OFFSET 7
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC13_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC13_OFFSET 6
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC11_LEN    1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC11_OFFSET 5
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC9_LEN     1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC9_OFFSET  4
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC7_LEN     1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC7_OFFSET  3
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC5_LEN     1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC5_OFFSET  2
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC3_LEN     1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC3_OFFSET  1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC1_LEN     1
#define MISC_UP_CFG_SC_SRST_DREQ_HW_AIC1_OFFSET  0

#define MISC_UP_CFG_RESERVED_0_LEN        30
#define MISC_UP_CFG_RESERVED_0_OFFSET     2
#define MISC_UP_CFG_PLL7_HI_UNLOCK_LEN    1
#define MISC_UP_CFG_PLL7_HI_UNLOCK_OFFSET 1
#define MISC_UP_CFG_PLL7_UNLOCK_LEN       1
#define MISC_UP_CFG_PLL7_UNLOCK_OFFSET    0

#define MISC_UP_CFG_RESERVED_0_LEN                 30
#define MISC_UP_CFG_RESERVED_0_OFFSET              2
#define MISC_UP_CFG_PLL7_HI_UNLOCK_INT_MASK_LEN    1
#define MISC_UP_CFG_PLL7_HI_UNLOCK_INT_MASK_OFFSET 1
#define MISC_UP_CFG_PLL7_UNLOCK_INT_MASK_LEN       1
#define MISC_UP_CFG_PLL7_UNLOCK_INT_MASK_OFFSET    0

#define MISC_UP_CFG_RESERVED_0_LEN      30
#define MISC_UP_CFG_RESERVED_0_OFFSET   2
#define MISC_UP_CFG_PLL7_HI_LOCK_LEN    1
#define MISC_UP_CFG_PLL7_HI_LOCK_OFFSET 1
#define MISC_UP_CFG_PLL7_LOCK_LEN       1
#define MISC_UP_CFG_PLL7_LOCK_OFFSET    0

#define MISC_UP_CFG_RESERVED_0_LEN              16
#define MISC_UP_CFG_RESERVED_0_OFFSET           16
#define MISC_UP_CFG_PLL7_HI_FNPLL_STATE0_LEN    16
#define MISC_UP_CFG_PLL7_HI_FNPLL_STATE0_OFFSET 0

#define MISC_UP_CFG_RESERVED_0_LEN                      16
#define MISC_UP_CFG_RESERVED_0_OFFSET                   16
#define MISC_UP_CFG_TEST_DATA_FNPLL_1V2_LEN             8
#define MISC_UP_CFG_TEST_DATA_FNPLL_1V2_OFFSET          8
#define MISC_UP_CFG_RESERVED_1_LEN                      1
#define MISC_UP_CFG_RESERVED_1_OFFSET                   7
#define MISC_UP_CFG_CLOCK_LOST_FNPLL_1V2_LEN            1
#define MISC_UP_CFG_CLOCK_LOST_FNPLL_1V2_OFFSET         6
#define MISC_UP_CFG_RESERVED_2_LEN                      1
#define MISC_UP_CFG_RESERVED_2_OFFSET                   5
#define MISC_UP_CFG_BBPD_CALIB_SUCCESS_FNPLL_1V2_LEN    1
#define MISC_UP_CFG_BBPD_CALIB_SUCCESS_FNPLL_1V2_OFFSET 4
#define MISC_UP_CFG_BBPD_CALIB_FAIL_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_BBPD_CALIB_FAIL_FNPLL_1V2_OFFSET    3
#define MISC_UP_CFG_BBPD_CALIB_DONE_FNPLL_1V2_LEN       1
#define MISC_UP_CFG_BBPD_CALIB_DONE_FNPLL_1V2_OFFSET    2
#define MISC_UP_CFG_PLL_LOCK_ATE_FNPLL_1V2_LEN          1
#define MISC_UP_CFG_PLL_LOCK_ATE_FNPLL_1V2_OFFSET       1
#define MISC_UP_CFG_PLL_LOCK_FNPLL_1V2_LEN              1
#define MISC_UP_CFG_PLL_LOCK_FNPLL_1V2_OFFSET           0

#define MISC_UP_CFG_RESERVED_0_LEN                 16
#define MISC_UP_CFG_RESERVED_0_OFFSET              16
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC31_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC31_OFFSET 15
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC29_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC29_OFFSET 14
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC27_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC27_OFFSET 13
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC25_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC25_OFFSET 12
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC23_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC23_OFFSET 11
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC21_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC21_OFFSET 10
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC19_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC19_OFFSET 9
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC17_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC17_OFFSET 8
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC15_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC15_OFFSET 7
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC13_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC13_OFFSET 6
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC11_LEN    1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC11_OFFSET 5
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC9_LEN     1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC9_OFFSET  4
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC7_LEN     1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC7_OFFSET  3
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC5_LEN     1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC5_OFFSET  2
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC3_LEN     1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC3_OFFSET  1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC1_LEN     1
#define MISC_UP_CFG_SC_SRST_ST_REQ_HW_AIC1_OFFSET  0

#define MISC_UP_CFG_RESERVED_0_LEN    31
#define MISC_UP_CFG_RESERVED_0_OFFSET 1
#define MISC_UP_CFG_SC_TS_EN_LEN      1
#define MISC_UP_CFG_SC_TS_EN_OFFSET   0

#define MISC_UP_CFG_RESERVED_0_LEN                   30
#define MISC_UP_CFG_RESERVED_0_OFFSET                2
#define MISC_UP_CFG_PLL7_HI_UNLOCK_INT_STATUS_LEN    1
#define MISC_UP_CFG_PLL7_HI_UNLOCK_INT_STATUS_OFFSET 1
#define MISC_UP_CFG_PLL7_UNLOCK_INT_STATUS_LEN       1
#define MISC_UP_CFG_PLL7_UNLOCK_INT_STATUS_OFFSET    0

#define MISC_UP_CFG_SYSCTRL_LOCK_LEN    32
#define MISC_UP_CFG_SYSCTRL_LOCK_OFFSET 0

#define MISC_UP_CFG_SYSCTRL_UNLOCK_LEN    32
#define MISC_UP_CFG_SYSCTRL_UNLOCK_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV0_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV0_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV1_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV1_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV2_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV2_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV3_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV3_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV4_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV4_OFFSET 0

#define MISC_UP_CFG_SC_ECO_RSV5_LEN    32
#define MISC_UP_CFG_SC_ECO_RSV5_OFFSET 0

#define MISC_UP_CFG_FPGA_VERI_NUM_LEN    32
#define MISC_UP_CFG_FPGA_VERI_NUM_OFFSET 0

#endif // __MISC_UP_CFG_REG_OFFSET_FIELD_H__
