// ****************************************************************************** 
// Copyright     :  Copyright (C) 2019, Hisilicon Technologies Co. Ltd.
// File name     :  misc_down_cfg_reg_offset.h
// Project line  :  ICT
// Department    :  ICT Processor Chipset Development Dep
// Author        : huawei
// Version       :  1.0
// Date          :  2018/7/2
// Description   :  The description of CLOUD project
// Others        :  Generated automatically by nManager V4.2 
// History       : huawei 2019/01/26 15:24:23 Create file
// ******************************************************************************

#ifndef __MISC_DOWN_CFG_REG_OFFSET_H__
#define __MISC_DOWN_CFG_REG_OFFSET_H__

/* MISC_DOWN_CFG Base address of Module's Register */
#define SOC_MISC_DOWN_CFG_BASE                       (0x160000)

/******************************************************************************/
/*                      SOC MISC_DOWN_CFG Registers' Definitions                            */
/******************************************************************************/

#define SOC_MISC_DOWN_CFG_SC_PLL0_SEL_REG               (SOC_MISC_DOWN_CFG_BASE + 0x8)    /* PLL0选择 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_FCTRL_REG             (SOC_MISC_DOWN_CFG_BASE + 0x10)   /* SC_PLL0_FCTRL为CDIE_CRG的PLL0整数分频 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_FCTRL_FRAC_REG        (SOC_MISC_DOWN_CFG_BASE + 0x14)   /* SC_PLL0_FCTRL_FRAC为CDIE_CRG的PLL0小数分频 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG0_REG     (SOC_MISC_DOWN_CFG_BASE + 0x20)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG1_REG     (SOC_MISC_DOWN_CFG_BASE + 0x24)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG2_REG     (SOC_MISC_DOWN_CFG_BASE + 0x28)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG3_REG     (SOC_MISC_DOWN_CFG_BASE + 0x2C)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG4_REG     (SOC_MISC_DOWN_CFG_BASE + 0x30)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG5_REG     (SOC_MISC_DOWN_CFG_BASE + 0x34)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG6_REG     (SOC_MISC_DOWN_CFG_BASE + 0x38)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG7_REG     (SOC_MISC_DOWN_CFG_BASE + 0x3C)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG8_REG     (SOC_MISC_DOWN_CFG_BASE + 0x40)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG9_REG     (SOC_MISC_DOWN_CFG_BASE + 0x44)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FNPLL_CFG10_REG    (SOC_MISC_DOWN_CFG_BASE + 0x48)   /* PLL输入配置寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FCTRL_REG          (SOC_MISC_DOWN_CFG_BASE + 0x80)   /* SC_PLL0_HI_FCTRL为CDIE_CRG的PLL0_HI整数分频 */
#define SOC_MISC_DOWN_CFG_SC_PLL0_HI_FCTRL_FRAC_REG     (SOC_MISC_DOWN_CFG_BASE + 0x84)   /* SC_PLL0_HI_FCTRL_FRAC为CDIE_CRG的PLL0_HI小数分频 */
#define SOC_MISC_DOWN_CFG_SC_PLL_CLK_BYPASS0_REG        (SOC_MISC_DOWN_CFG_BASE + 0xA0)   /* SC_PLL_CLK_BYPASS0为CDIE_CRG的PLL相关工作时钟选择。 */
#define SOC_MISC_DOWN_CFG_SC_SWITCH_CLK_SEL_REG         (SOC_MISC_DOWN_CFG_BASE + 0x110)  /* 总线时钟的分频选择寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_TSENSOR_A_CLK_SEL_REG      (SOC_MISC_DOWN_CFG_BASE + 0x120)  /* 总线时钟的分频选择寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_BYPASS_ICG_EN_PLL_REG      (SOC_MISC_DOWN_CFG_BASE + 0x160)  /* PLL控制寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_ACK_DLY_TIME_REG           (SOC_MISC_DOWN_CFG_BASE + 0x200)  /* 等待DDR或HBM的ACK的超时时间配置 */
#define SOC_MISC_DOWN_CFG_SC_TIME_WAIT_EFUSE_DONE_REG   (SOC_MISC_DOWN_CFG_BASE + 0x204)  /* 等待efuse done的超时时间配置 */
#define SOC_MISC_DOWN_CFG_SC_PORN_ENABLE_REG            (SOC_MISC_DOWN_CFG_BASE + 0x220)  /* 按键复位区分上电非上电选择 */
#define SOC_MISC_DOWN_CFG_SC_REF_CLK_EN_REG             (SOC_MISC_DOWN_CFG_BASE + 0x600)  /* SC_REF_CLK_EN是clk_ref的时钟使能寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_REF_CLK_DIS_REG            (SOC_MISC_DOWN_CFG_BASE + 0x604)  /* SC_REF_CLK_DIS是clk_ref时钟禁止寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_GPIO_CLK_DB_EN_REG         (SOC_MISC_DOWN_CFG_BASE + 0x608)  /* SC_GPIO_DB_CLK_EN是clk_gpio_db的时钟使能寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_GPIO_CLK_DB_DIS_REG        (SOC_MISC_DOWN_CFG_BASE + 0x60C)  /* SC_GPIO_DB_CLK_DIS是clk_gpio_db时钟禁止寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_CLK_EN_REG           (SOC_MISC_DOWN_CFG_BASE + 0x618)  /* SC_DJTAG_CLKEN表示DJTAG逻辑时钟使能配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_CLK_DIS_REG          (SOC_MISC_DOWN_CFG_BASE + 0x61C)  /* SC_DJTAG_CLK_DIS表示DJTAG逻辑时钟禁止寄存器 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_CLK_EN_REG      (SOC_MISC_DOWN_CFG_BASE + 0x620)  /* FUNC_MBIST时钟使能寄存器 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_CLK_DIS_REG     (SOC_MISC_DOWN_CFG_BASE + 0x624)  /* FUNC_MBIST时钟禁止寄存器 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_CLK_EN_REG          (SOC_MISC_DOWN_CFG_BASE + 0x630)  /* SC_SYSCNT_CLK_EN是clk_syscnt的时钟使能寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_CLK_DIS_REG         (SOC_MISC_DOWN_CFG_BASE + 0x634)  /* SC_SYSCNT_CLK_DIS是clk_syscnt时钟禁止寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_DCIP_CLK_EN_REG            (SOC_MISC_DOWN_CFG_BASE + 0x650)  /* SC_DCIP_CLK_EN的时钟使能寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_DCIP_CLK_DIS_REG           (SOC_MISC_DOWN_CFG_BASE + 0x654)  /* SC_DCIP_CLK_DIS是DCIP时钟禁止寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_MESH_CLK_EN_REG            (SOC_MISC_DOWN_CFG_BASE + 0x700)  /* MESH时钟使能寄存器 */
#define SOC_MISC_DOWN_CFG_SC_MESH_CLK_DIS_REG           (SOC_MISC_DOWN_CFG_BASE + 0x704)  /* MESH时钟禁止寄存器 */
#define SOC_MISC_DOWN_CFG_SC_HW_AIC_RESET_REQ_REG       (SOC_MISC_DOWN_CFG_BASE + 0xA00)  /* AIC软复位请求控制寄存器 */
#define SOC_MISC_DOWN_CFG_SC_HW_AIC_RESET_DREQ_REG      (SOC_MISC_DOWN_CFG_BASE + 0xA04)  /* AIC软复位去请求控制寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_RESET_REQ_REG          (SOC_MISC_DOWN_CFG_BASE + 0xB00)  /* ACG FFS软复位请求配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_RESET_DREQ_REG         (SOC_MISC_DOWN_CFG_BASE + 0xB04)  /* ACG FFS软复位请求配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_CPM_RESET_REQ_REG          (SOC_MISC_DOWN_CFG_BASE + 0xB08)  /* ACG CPM软复位请求配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_CPM_RESET_DREQ_REG         (SOC_MISC_DOWN_CFG_BASE + 0xB0C)  /* ACG CPM软复位请求配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_DCIP_RESET_REQ_REG         (SOC_MISC_DOWN_CFG_BASE + 0xC60)  /* DCIPS软复位请求信号。 */
#define SOC_MISC_DOWN_CFG_SC_DCIP_RESET_DREQ_REG        (SOC_MISC_DOWN_CFG_BASE + 0xC64)  /* DCIP软复位去请求信号。 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_RESET_REQ_REG        (SOC_MISC_DOWN_CFG_BASE + 0xD18)  /* SC_DJTAG_SRST_REQ表示DJTAG逻辑复位请求寄存器 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_RESET_DREQ_REG       (SOC_MISC_DOWN_CFG_BASE + 0xD1C)  /* SC_DJTAG_SRST_DREQ表示DJTAG逻辑复位去请求寄存器 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_RESET_REQ_REG   (SOC_MISC_DOWN_CFG_BASE + 0xD20)  /* SC_FUNC_MBIST_RESET_REQ表示对当前FUNC_MBIST的RST_REQ信号的配置。 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_RESET_DREQ_REG  (SOC_MISC_DOWN_CFG_BASE + 0xD24)  /* SC_FUNC_MBIST_RESET_DEREQ表示对当前FUNC_MBIST的RST_REQ信号的去复位。 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_RESET_REQ_REG       (SOC_MISC_DOWN_CFG_BASE + 0xD30)  /* SC_SYSCNT_SRST_REQ表示SYSCNT逻辑复位请求寄存器 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_RESET_DREQ_REG      (SOC_MISC_DOWN_CFG_BASE + 0xD34)  /* SC_SYSCNT_SRST_DREQ表示SYSCNT逻辑复位去请求寄存器 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_CLK_SEL_REG         (SOC_MISC_DOWN_CFG_BASE + 0x2008) /* SYSCNT时钟选择寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_HBM_ENABLE0_REG            (SOC_MISC_DOWN_CFG_BASE + 0x2200) /* HBM0和HBM1使用情况指示寄存器 */
#define SOC_MISC_DOWN_CFG_SC_HBM_ENABLE1_REG            (SOC_MISC_DOWN_CFG_BASE + 0x2204) /* HBM2和HBM3使用情况指示寄存器 */
#define SOC_MISC_DOWN_CFG_SC_DDRC_ENABLE_REG            (SOC_MISC_DOWN_CFG_BASE + 0x2208) /* DDRC使用情况指示寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_CFG0_REG               (SOC_MISC_DOWN_CFG_BASE + 0x3600) /* ACG中ACG的配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_CFG1_REG               (SOC_MISC_DOWN_CFG_BASE + 0x3614) /* ACG配置寄存器1 */
#define SOC_MISC_DOWN_CFG_SC_ACG_CFG2_REG               (SOC_MISC_DOWN_CFG_BASE + 0x3618) /* ACG中CPM的配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_BYPASS_REG             (SOC_MISC_DOWN_CFG_BASE + 0x3650) 
#define SOC_MISC_DOWN_CFG_SC_MESH_REACTIVATE_EN_REG     (SOC_MISC_DOWN_CFG_BASE + 0x3750) /* MESH时钟重新激活配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_MESH_REACTIVATE_CYCLES_REG (SOC_MISC_DOWN_CFG_BASE + 0x3754) /* MESH时钟重新激活CYCLES数寄存器 */
#define SOC_MISC_DOWN_CFG_SC_PLL_SRC_INT_REG            (SOC_MISC_DOWN_CFG_BASE + 0x4000) /* PLL中断源寄存器 */
#define SOC_MISC_DOWN_CFG_SC_PLL_INT_MASK_REG           (SOC_MISC_DOWN_CFG_BASE + 0x4004) /* PLL中断屏蔽寄存器 */
#define SOC_MISC_DOWN_CFG_SC_LAST_RST_STATUS_CLR_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4100) /* 复位原因记录清除寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG0_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4400) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG1_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4404) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG2_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4408) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG3_REG    (SOC_MISC_DOWN_CFG_BASE + 0x440C) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG4_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4410) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_CFG5_REG    (SOC_MISC_DOWN_CFG_BASE + 0x4414) /* JITTER MONITOR配置寄存器 */
#define SOC_MISC_DOWN_CFG_SC_PLL_LOCK_STATUS_REG        (SOC_MISC_DOWN_CFG_BASE + 0x5000) /* PLL锁定状态寄存器。 */
#define SOC_MISC_DOWN_CFG_PLL0_HI_FNPLL_STATE0_REG      (SOC_MISC_DOWN_CFG_BASE + 0x5004) /* PLL输出状态寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_PLL0_HI_FNPLL_STATE1_REG      (SOC_MISC_DOWN_CFG_BASE + 0x5008) /* PLL输出状态寄存器;静态信号 */
#define SOC_MISC_DOWN_CFG_SC_REF_CLK_ST_REG             (SOC_MISC_DOWN_CFG_BASE + 0x5600) /* SC_REF_CLK_ST表示CDIE_CRG内ref_clk的时钟状态。 */
#define SOC_MISC_DOWN_CFG_SC_GPIO_DB_CLK_ST_REG         (SOC_MISC_DOWN_CFG_BASE + 0x5608) /* SC_GPIO_DB_CLK_ST表示CDIE_CRG内gpio_db_clk的时钟状态。 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_CLK_ST_REG           (SOC_MISC_DOWN_CFG_BASE + 0x5618) /* SC_DJTAG_CLK_ST表示DJTAG相关逻辑时钟状态 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_CLK_ST_REG      (SOC_MISC_DOWN_CFG_BASE + 0x5620) /* FUNC_MBIST时钟状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_CLK_ST_REG          (SOC_MISC_DOWN_CFG_BASE + 0x5630) /* SC_SYSCNT_CLK_ST表示CDIE_CRG内syscnt_clk的时钟状态。 */
#define SOC_MISC_DOWN_CFG_SC_DCBIST_CLK_ST_REG          (SOC_MISC_DOWN_CFG_BASE + 0x5650) /* SC_DCBIST_CLK_ST表示DCIP的时钟状态。 */
#define SOC_MISC_DOWN_CFG_SC_MESH_CLK_ST_REG            (SOC_MISC_DOWN_CFG_BASE + 0x5700) /* MESH的时钟状态寄存器。 */
#define SOC_MISC_DOWN_CFG_SC_HW_AIC_RESET_ST_REG        (SOC_MISC_DOWN_CFG_BASE + 0x5A00) /* HW_AIC的当前软复位状态 */
#define SOC_MISC_DOWN_CFG_SC_ACG_RESET_ST_REG           (SOC_MISC_DOWN_CFG_BASE + 0x5B00) /* ACG的RST_REQ信号的状态。 */
#define SOC_MISC_DOWN_CFG_SC_CPM_RESET_ST_REG           (SOC_MISC_DOWN_CFG_BASE + 0x5B08) /* CPM的RST_REQ信号的状态。 */
#define SOC_MISC_DOWN_CFG_SC_DCIP_TRESET_ST_REG         (SOC_MISC_DOWN_CFG_BASE + 0x5C60) /* DCIP的RST_REQ信号的状态。 */
#define SOC_MISC_DOWN_CFG_SC_DJTAG_RESET_ST_REG         (SOC_MISC_DOWN_CFG_BASE + 0x5D18) /* SC_DJTAG_SRST_ST表示DJTAG相关逻辑复位状态 */
#define SOC_MISC_DOWN_CFG_SC_FUNC_MBIST_RESET_ST_REG    (SOC_MISC_DOWN_CFG_BASE + 0x5D20) /* SC_FUNC_MBIST_RESET_ST表示对当前FUNC_MBIST的RST_REQ信号的状态。 */
#define SOC_MISC_DOWN_CFG_SC_SYSCNT_RESET_ST_REG        (SOC_MISC_DOWN_CFG_BASE + 0x5D30) /* SC_SYSCNT_SRST_ST表示DJTAG相关逻辑复位状态 */
#define SOC_MISC_DOWN_CFG_SC_LAST_RST_STATUS_REG        (SOC_MISC_DOWN_CFG_BASE + 0x6100) /* 复位原因记录寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_STATE0_REG  (SOC_MISC_DOWN_CFG_BASE + 0x6200) /* JITTER MONITOR状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_STATE1_REG  (SOC_MISC_DOWN_CFG_BASE + 0x6204) /* JITTER MONITOR状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_STATE2_REG  (SOC_MISC_DOWN_CFG_BASE + 0x6208) /* JITTER MONITOR状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_JITTER_MONITOR_STATE3_REG  (SOC_MISC_DOWN_CFG_BASE + 0x620C) /* JITTER MONITOR状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_ST0_REG                (SOC_MISC_DOWN_CFG_BASE + 0x6600) /* ACG状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ACG_ST1_REG                (SOC_MISC_DOWN_CFG_BASE + 0x6604) /* ACG中CPM的状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_PLL_INT_STATUS_REG         (SOC_MISC_DOWN_CFG_BASE + 0x8000) /* PLL中断状态寄存器 */
#define SOC_MISC_DOWN_CFG_SC_SYSCTRL_LOCK_REG           (SOC_MISC_DOWN_CFG_BASE + 0xF100) /* 系统控制器锁定寄存器。（注意：1，此寄存器空间必须是安全访问才能成功） */
#define SOC_MISC_DOWN_CFG_SC_SYSCTRL_UNLOCK_REG         (SOC_MISC_DOWN_CFG_BASE + 0xF110) /* 系统控制器解锁寄存器。（注意：1，此寄存器空间必须是安全访问才能成功） */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV0_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF00) /* ECO 寄存器 */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV1_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF04) /* ECO 寄存器1 */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV2_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF08) /* ECO 寄存器2 */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV3_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF0C) /* ECO 寄存器3 */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV4_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF10) /* ECO 寄存器4 */
#define SOC_MISC_DOWN_CFG_SC_ECO_RSV5_REG               (SOC_MISC_DOWN_CFG_BASE + 0xFF14) /* ECO 寄存器5 */
#define SOC_MISC_DOWN_CFG_FPGA_VER_REG                  (SOC_MISC_DOWN_CFG_BASE + 0xFFFC) /* FPGA版本寄存器 */

#endif // __MISC_DOWN_CFG_REG_OFFSET_H__
