// ****************************************************************************** 
// Copyright     :  Copyright (C) 2019, Hisilicon Technologies Co. Ltd.
// File name     :  misc_down_cfg_reg_offset_field.h
// Project line  :  ICT
// Department    :  ICT Processor Chipset Development Dep
// Author        : huawei
// Version       :  1.0
// Date          :  2018/7/2
// Description   :  The description of CLOUD project
// Others        :  Generated automatically by nManager V4.2 
// History       : huawei 2019/01/26 15:24:23 Create file
// ******************************************************************************

#ifndef __MISC_DOWN_CFG_REG_OFFSET_FIELD_H__
#define __MISC_DOWN_CFG_REG_OFFSET_FIELD_H__

#define MISC_DOWN_CFG_SC_PLL0_SEL_LEN    1
#define MISC_DOWN_CFG_SC_PLL0_SEL_OFFSET 0

#define MISC_DOWN_CFG_PLL0_FOUTVCOEN_LEN        1
#define MISC_DOWN_CFG_PLL0_FOUTVCOEN_OFFSET     30
#define MISC_DOWN_CFG_PLL0_FOUTPOSTDIVEN_LEN    1
#define MISC_DOWN_CFG_PLL0_FOUTPOSTDIVEN_OFFSET 29
#define MISC_DOWN_CFG_PLL0_FOUT4PHASEEN_LEN     1
#define MISC_DOWN_CFG_PLL0_FOUT4PHASEEN_OFFSET  28
#define MISC_DOWN_CFG_PLL0_DACEN_LEN            1
#define MISC_DOWN_CFG_PLL0_DACEN_OFFSET         27
#define MISC_DOWN_CFG_PLL0_DSMEN_LEN            1
#define MISC_DOWN_CFG_PLL0_DSMEN_OFFSET         26
#define MISC_DOWN_CFG_PLL0_EN_LEN               1
#define MISC_DOWN_CFG_PLL0_EN_OFFSET            25
#define MISC_DOWN_CFG_PLL0_BYPASS_LEN           1
#define MISC_DOWN_CFG_PLL0_BYPASS_OFFSET        24
#define MISC_DOWN_CFG_PLL0_POSTDIV2_LEN         3
#define MISC_DOWN_CFG_PLL0_POSTDIV2_OFFSET      21
#define MISC_DOWN_CFG_PLL0_POSTDIV1_LEN         3
#define MISC_DOWN_CFG_PLL0_POSTDIV1_OFFSET      18
#define MISC_DOWN_CFG_PLL0_FBDIV_LEN            12
#define MISC_DOWN_CFG_PLL0_FBDIV_OFFSET         6
#define MISC_DOWN_CFG_PLL0_REFDIV_LEN           6
#define MISC_DOWN_CFG_PLL0_REFDIV_OFFSET        0

#define MISC_DOWN_CFG_PLL0_FRAC_LEN    26
#define MISC_DOWN_CFG_PLL0_FRAC_OFFSET 0

#define MISC_DOWN_CFG_DTC_M_CFG_FNPLL_1V2_LEN     6
#define MISC_DOWN_CFG_DTC_M_CFG_FNPLL_1V2_OFFSET  8
#define MISC_DOWN_CFG_PHE_SEL_IN_FNPLL_1V2_LEN    2
#define MISC_DOWN_CFG_PHE_SEL_IN_FNPLL_1V2_OFFSET 4
#define MISC_DOWN_CFG_DTC_TEST_FNPLL_1V2_LEN      1
#define MISC_DOWN_CFG_DTC_TEST_FNPLL_1V2_OFFSET   1
#define MISC_DOWN_CFG_PHE_SEL_EN_FNPLL_1V2_LEN    1
#define MISC_DOWN_CFG_PHE_SEL_EN_FNPLL_1V2_OFFSET 0

#define MISC_DOWN_CFG_SPREAD_FNPLL_1V2_LEN         3
#define MISC_DOWN_CFG_SPREAD_FNPLL_1V2_OFFSET      8
#define MISC_DOWN_CFG_DIVVAL_FNPLL_1V2_LEN         4
#define MISC_DOWN_CFG_DIVVAL_FNPLL_1V2_OFFSET      4
#define MISC_DOWN_CFG_SEL_EXTWAVE_FNPLL_1V2_LEN    1
#define MISC_DOWN_CFG_SEL_EXTWAVE_FNPLL_1V2_OFFSET 2
#define MISC_DOWN_CFG_DOWNSPREAD_FNPLL_1V2_LEN     1
#define MISC_DOWN_CFG_DOWNSPREAD_FNPLL_1V2_OFFSET  1
#define MISC_DOWN_CFG_SPREAD_EN_FNPLL_1V2_LEN      1
#define MISC_DOWN_CFG_SPREAD_EN_FNPLL_1V2_OFFSET   0

#define MISC_DOWN_CFG_EXTWAVEVAL_FNPLL_1V2_LEN     8
#define MISC_DOWN_CFG_EXTWAVEVAL_FNPLL_1V2_OFFSET  8
#define MISC_DOWN_CFG_EXT_MAXADDR_FNPLL_1V2_LEN    8
#define MISC_DOWN_CFG_EXT_MAXADDR_FNPLL_1V2_OFFSET 0

#define MISC_DOWN_CFG_FBDIV_DELAY_NUM_FNPLL_1V2_LEN    7
#define MISC_DOWN_CFG_FBDIV_DELAY_NUM_FNPLL_1V2_OFFSET 8
#define MISC_DOWN_CFG_LOCK_EN_FNPLL_1V2_LEN            1
#define MISC_DOWN_CFG_LOCK_EN_FNPLL_1V2_OFFSET         7
#define MISC_DOWN_CFG_DIV2_PD_FNPLL_1V2_LEN            1
#define MISC_DOWN_CFG_DIV2_PD_FNPLL_1V2_OFFSET         6
#define MISC_DOWN_CFG_FBDIV_RST_N_FNPLL_1V2_LEN        1
#define MISC_DOWN_CFG_FBDIV_RST_N_FNPLL_1V2_OFFSET     5
#define MISC_DOWN_CFG_REFDIV_RST_N_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_REFDIV_RST_N_FNPLL_1V2_OFFSET    4
#define MISC_DOWN_CFG_LOCK_THR_FNPLL_1V2_LEN           2
#define MISC_DOWN_CFG_LOCK_THR_FNPLL_1V2_OFFSET        2
#define MISC_DOWN_CFG_TEST_MODE_FNPLL_1V2_LEN          1
#define MISC_DOWN_CFG_TEST_MODE_FNPLL_1V2_OFFSET       1
#define MISC_DOWN_CFG_INPUT_CFG_EN_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_INPUT_CFG_EN_FNPLL_1V2_OFFSET    0

#define MISC_DOWN_CFG_CTINUE_LOCK_NUM_FNPLL_1V2_LEN    5
#define MISC_DOWN_CFG_CTINUE_LOCK_NUM_FNPLL_1V2_OFFSET 8
#define MISC_DOWN_CFG_PHE_CODE_B_FNPLL_1V2_LEN         2
#define MISC_DOWN_CFG_PHE_CODE_B_FNPLL_1V2_OFFSET      6
#define MISC_DOWN_CFG_PHE_CODE_A_FNPLL_1V2_LEN         2
#define MISC_DOWN_CFG_PHE_CODE_A_FNPLL_1V2_OFFSET      4
#define MISC_DOWN_CFG_DLL_FORCE_EN_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_DLL_FORCE_EN_FNPLL_1V2_OFFSET    2
#define MISC_DOWN_CFG_DTC_CTRL_INV_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_DTC_CTRL_INV_FNPLL_1V2_OFFSET    1
#define MISC_DOWN_CFG_BBPD_CALIB_BYP_FNPLL_1V2_LEN     1
#define MISC_DOWN_CFG_BBPD_CALIB_BYP_FNPLL_1V2_OFFSET  0

#define MISC_DOWN_CFG_K_GAIN_CFG_FNPLL_1V2_LEN       6
#define MISC_DOWN_CFG_K_GAIN_CFG_FNPLL_1V2_OFFSET    8
#define MISC_DOWN_CFG_K_GAIN_AV_THR_FNPLL_1V2_LEN    3
#define MISC_DOWN_CFG_K_GAIN_AV_THR_FNPLL_1V2_OFFSET 4
#define MISC_DOWN_CFG_K_GAIN_CFG_EN_FNPLL_1V2_LEN    1
#define MISC_DOWN_CFG_K_GAIN_CFG_EN_FNPLL_1V2_OFFSET 1
#define MISC_DOWN_CFG_READ_EN_FNPLL_1V2_LEN          1
#define MISC_DOWN_CFG_READ_EN_FNPLL_1V2_OFFSET       0

#define MISC_DOWN_CFG_BBPD_LOCK_NUM_FNPLL_1V2_LEN    8
#define MISC_DOWN_CFG_BBPD_LOCK_NUM_FNPLL_1V2_OFFSET 8
#define MISC_DOWN_CFG_DTC_O_CFG_FNPLL_1V2_LEN        6
#define MISC_DOWN_CFG_DTC_O_CFG_FNPLL_1V2_OFFSET     0

#define MISC_DOWN_CFG_CALIB_LPF_BW1_FNPLL_1V2_LEN    3
#define MISC_DOWN_CFG_CALIB_LPF_BW1_FNPLL_1V2_OFFSET 12
#define MISC_DOWN_CFG_CALIB_LPF_BW_FNPLL_1V2_LEN     3
#define MISC_DOWN_CFG_CALIB_LPF_BW_FNPLL_1V2_OFFSET  8
#define MISC_DOWN_CFG_LPF_BW1_FNPLL_1V2_LEN          3
#define MISC_DOWN_CFG_LPF_BW1_FNPLL_1V2_OFFSET       4
#define MISC_DOWN_CFG_LPF_BW_FNPLL_1V2_LEN           3
#define MISC_DOWN_CFG_LPF_BW_FNPLL_1V2_OFFSET        0

#define MISC_DOWN_CFG_MIN_K_GAIN_FNPLL_1V2_LEN    6
#define MISC_DOWN_CFG_MIN_K_GAIN_FNPLL_1V2_OFFSET 8
#define MISC_DOWN_CFG_MAX_K_GAIN_FNPLL_1V2_LEN    6
#define MISC_DOWN_CFG_MAX_K_GAIN_FNPLL_1V2_OFFSET 0

#define MISC_DOWN_CFG_TEST_DATA_SEL_FNPLL_1V2_LEN    4
#define MISC_DOWN_CFG_TEST_DATA_SEL_FNPLL_1V2_OFFSET 12
#define MISC_DOWN_CFG_VDC_SEL_FNPLL_1V2_LEN          4
#define MISC_DOWN_CFG_VDC_SEL_FNPLL_1V2_OFFSET       4
#define MISC_DOWN_CFG_ICP_CTRL_FNPLL_1V2_LEN         1
#define MISC_DOWN_CFG_ICP_CTRL_FNPLL_1V2_OFFSET      2
#define MISC_DOWN_CFG_UPDN_SEL_FNPLL_1V2_LEN         1
#define MISC_DOWN_CFG_UPDN_SEL_FNPLL_1V2_OFFSET      1
#define MISC_DOWN_CFG_EN_DAC_TEST_FNPLL_1V2_LEN      1
#define MISC_DOWN_CFG_EN_DAC_TEST_FNPLL_1V2_OFFSET   0

#define MISC_DOWN_CFG_REF_LOST_THR_FNPLL_1V2_LEN    8
#define MISC_DOWN_CFG_REF_LOST_THR_FNPLL_1V2_OFFSET 0

#define MISC_DOWN_CFG_PLL0_HI_FOUTVCOPD_LEN        1
#define MISC_DOWN_CFG_PLL0_HI_FOUTVCOPD_OFFSET     30
#define MISC_DOWN_CFG_PLL0_HI_FOUTPOSTDIVPD_LEN    1
#define MISC_DOWN_CFG_PLL0_HI_FOUTPOSTDIVPD_OFFSET 29
#define MISC_DOWN_CFG_PLL0_HI_FOUT4PHASEPD_LEN     1
#define MISC_DOWN_CFG_PLL0_HI_FOUT4PHASEPD_OFFSET  28
#define MISC_DOWN_CFG_PLL0_HI_DLL_EN_LEN           1
#define MISC_DOWN_CFG_PLL0_HI_DLL_EN_OFFSET        27
#define MISC_DOWN_CFG_PLL0_HI_MODE_LEN             1
#define MISC_DOWN_CFG_PLL0_HI_MODE_OFFSET          26
#define MISC_DOWN_CFG_PLL0_HI_PD_LEN               1
#define MISC_DOWN_CFG_PLL0_HI_PD_OFFSET            25
#define MISC_DOWN_CFG_PLL0_HI_BYPASS_LEN           1
#define MISC_DOWN_CFG_PLL0_HI_BYPASS_OFFSET        24
#define MISC_DOWN_CFG_PLL0_HI_POSTDIV2_LEN         3
#define MISC_DOWN_CFG_PLL0_HI_POSTDIV2_OFFSET      21
#define MISC_DOWN_CFG_PLL0_HI_POSTDIV1_LEN         3
#define MISC_DOWN_CFG_PLL0_HI_POSTDIV1_OFFSET      18
#define MISC_DOWN_CFG_PLL0_HI_FBDIV_LEN            12
#define MISC_DOWN_CFG_PLL0_HI_FBDIV_OFFSET         6
#define MISC_DOWN_CFG_PLL0_HI_REFDIV_LEN           6
#define MISC_DOWN_CFG_PLL0_HI_REFDIV_OFFSET        0

#define MISC_DOWN_CFG_PLL0_HI_FRAC_LEN    26
#define MISC_DOWN_CFG_PLL0_HI_FRAC_OFFSET 0

#define MISC_DOWN_CFG_PLL0_BYPASS_EXTERNAL_N_LEN    1
#define MISC_DOWN_CFG_PLL0_BYPASS_EXTERNAL_N_OFFSET 0

#define MISC_DOWN_CFG_SC_SWITCH_DIV_SEL_KERNEL_LEN    1
#define MISC_DOWN_CFG_SC_SWITCH_DIV_SEL_KERNEL_OFFSET 0

#define MISC_DOWN_CFG_SC_TSENSOR_A_CLK_SEL_LEN    1
#define MISC_DOWN_CFG_SC_TSENSOR_A_CLK_SEL_OFFSET 0

#define MISC_DOWN_CFG_SC_BYPASS_ICG_EN_PLL_LEN    1
#define MISC_DOWN_CFG_SC_BYPASS_ICG_EN_PLL_OFFSET 0

#define MISC_DOWN_CFG_SC_ACK_DLY_TIME_LEN    32
#define MISC_DOWN_CFG_SC_ACK_DLY_TIME_OFFSET 0

#define MISC_DOWN_CFG_SC_TIME_WAIT_EFUSE_DONE_LEN    32
#define MISC_DOWN_CFG_SC_TIME_WAIT_EFUSE_DONE_OFFSET 0

#define MISC_DOWN_CFG_SC_PORN_ENABLE_LEN    1
#define MISC_DOWN_CFG_SC_PORN_ENABLE_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_REF_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_REF_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_REF_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_REF_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_GPIO_DB_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_GPIO_DB_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_GPIO_DB_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_GPIO_DB_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_EN_MESH_LEN    1
#define MISC_DOWN_CFG_SC_ICG_EN_MESH_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_DIS_MESH_LEN    1
#define MISC_DOWN_CFG_SC_ICG_DIS_MESH_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC30_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC30_OFFSET 15
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC28_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC28_OFFSET 14
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC26_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC26_OFFSET 13
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC24_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC24_OFFSET 12
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC22_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC22_OFFSET 11
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC20_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC20_OFFSET 10
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC18_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC18_OFFSET 9
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC16_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC16_OFFSET 8
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC14_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC14_OFFSET 7
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC12_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC12_OFFSET 6
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC10_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC10_OFFSET 5
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC8_LEN     1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC8_OFFSET  4
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC6_LEN     1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC6_OFFSET  3
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC4_LEN     1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC4_OFFSET  2
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC2_LEN     1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC2_OFFSET  1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC0_LEN     1
#define MISC_DOWN_CFG_SC_SRST_REQ_HW_AIC0_OFFSET  0

#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC30_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC30_OFFSET 15
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC28_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC28_OFFSET 14
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC26_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC26_OFFSET 13
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC24_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC24_OFFSET 12
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC22_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC22_OFFSET 11
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC20_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC20_OFFSET 10
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC18_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC18_OFFSET 9
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC16_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC16_OFFSET 8
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC14_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC14_OFFSET 7
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC12_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC12_OFFSET 6
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC10_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC10_OFFSET 5
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC8_LEN     1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC8_OFFSET  4
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC6_LEN     1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC6_OFFSET  3
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC4_LEN     1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC4_OFFSET  2
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC2_LEN     1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC2_OFFSET  1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC0_LEN     1
#define MISC_DOWN_CFG_SC_SRST_DREQ_HW_AIC0_OFFSET  0

#define MISC_DOWN_CFG_SC_SRST_REQ_FFS_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_FFS_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_DREQ_FFS_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_FFS_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_CPM_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_CPM_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_DREQ_CPM_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_CPM_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_DREQ_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_DREQ_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_SRST_DREQ_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_REQ_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SC_SRST_REQ_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_SRST_DREQ_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SRST_DREQ_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_SC_SYSCNT_CLK_SEL_LEN    1
#define MISC_DOWN_CFG_SC_SYSCNT_CLK_SEL_OFFSET 0

#define MISC_DOWN_CFG_SC_HBM_ENABLE0_LEN    32
#define MISC_DOWN_CFG_SC_HBM_ENABLE0_OFFSET 0

#define MISC_DOWN_CFG_SC_HBM_ENABLE1_LEN    32
#define MISC_DOWN_CFG_SC_HBM_ENABLE1_OFFSET 0

#define MISC_DOWN_CFG_SC_DDRC_ENABLE_LEN    2
#define MISC_DOWN_CFG_SC_DDRC_ENABLE_OFFSET 0

#define MISC_DOWN_CFG_SC_ACG_ON_MODE_LEN          1
#define MISC_DOWN_CFG_SC_ACG_ON_MODE_OFFSET       28
#define MISC_DOWN_CFG_SC_ACG_ENABLE_FFS_LEN       8
#define MISC_DOWN_CFG_SC_ACG_ENABLE_FFS_OFFSET    20
#define MISC_DOWN_CFG_SC_ACG_D_RATE_LEN           2
#define MISC_DOWN_CFG_SC_ACG_D_RATE_OFFSET        18
#define MISC_DOWN_CFG_SC_ACG_ENABLE_MOD_LEN       2
#define MISC_DOWN_CFG_SC_ACG_ENABLE_MOD_OFFSET    16
#define MISC_DOWN_CFG_SC_ACG_TEST_FFS_LEN         2
#define MISC_DOWN_CFG_SC_ACG_TEST_FFS_OFFSET      14
#define MISC_DOWN_CFG_SC_ACG_DIV64_EN_LEN         1
#define MISC_DOWN_CFG_SC_ACG_DIV64_EN_OFFSET      13
#define MISC_DOWN_CFG_SC_ACG_GLITCH_TEST_LEN      1
#define MISC_DOWN_CFG_SC_ACG_GLITCH_TEST_OFFSET   12
#define MISC_DOWN_CFG_SC_ACG_TRIM_LEN             2
#define MISC_DOWN_CFG_SC_ACG_TRIM_OFFSET          10
#define MISC_DOWN_CFG_SC_ACG_OFF_TIME_STEP_LEN    1
#define MISC_DOWN_CFG_SC_ACG_OFF_TIME_STEP_OFFSET 9
#define MISC_DOWN_CFG_SC_ACG_OFF_MODE_LEN         1
#define MISC_DOWN_CFG_SC_ACG_OFF_MODE_OFFSET      8
#define MISC_DOWN_CFG_SC_ACG_ENABLE_SEL_LEN       8
#define MISC_DOWN_CFG_SC_ACG_ENABLE_SEL_OFFSET    0

#define MISC_DOWN_CFG_SC_ACG_PULSE_WIDTH_SEL_LEN    1
#define MISC_DOWN_CFG_SC_ACG_PULSE_WIDTH_SEL_OFFSET 31
#define MISC_DOWN_CFG_SC_ACG_CPM_THRESHOLD_F_LEN    6
#define MISC_DOWN_CFG_SC_ACG_CPM_THRESHOLD_F_OFFSET 25
#define MISC_DOWN_CFG_SC_ACG_CPM_THRESHOLD_R_LEN    6
#define MISC_DOWN_CFG_SC_ACG_CPM_THRESHOLD_R_OFFSET 19
#define MISC_DOWN_CFG_SC_ACG_DATA_LIMIT_E_LEN       1
#define MISC_DOWN_CFG_SC_ACG_DATA_LIMIT_E_OFFSET    18
#define MISC_DOWN_CFG_SC_ACG_DATA_MOD_LEN           2
#define MISC_DOWN_CFG_SC_ACG_DATA_MOD_OFFSET        16
#define MISC_DOWN_CFG_SC_ACG_EDGE_SEL_LEN           1
#define MISC_DOWN_CFG_SC_ACG_EDGE_SEL_OFFSET        15
#define MISC_DOWN_CFG_SC_ACG_CPM_PERIOD_LEN         1
#define MISC_DOWN_CFG_SC_ACG_CPM_PERIOD_OFFSET      14
#define MISC_DOWN_CFG_SC_ACG_TEST_CPM_LEN           8
#define MISC_DOWN_CFG_SC_ACG_TEST_CPM_OFFSET        0

#define MISC_DOWN_CFG_SC_ACG_LVT_LL_LEN    4
#define MISC_DOWN_CFG_SC_ACG_LVT_LL_OFFSET 12
#define MISC_DOWN_CFG_SC_ACG_LVT_SL_LEN    4
#define MISC_DOWN_CFG_SC_ACG_LVT_SL_OFFSET 8
#define MISC_DOWN_CFG_SC_ACG_SVT_LL_LEN    4
#define MISC_DOWN_CFG_SC_ACG_SVT_LL_OFFSET 4
#define MISC_DOWN_CFG_SC_ACG_SVT_SL_LEN    4
#define MISC_DOWN_CFG_SC_ACG_SVT_SL_OFFSET 0

#define MISC_DOWN_CFG_SC_ACG_BYPASS_LEN    1
#define MISC_DOWN_CFG_SC_ACG_BYPASS_OFFSET 0

#define MISC_DOWN_CFG_SC_MESH_REACTIVATE_EN_LEN    1
#define MISC_DOWN_CFG_SC_MESH_REACTIVATE_EN_OFFSET 0

#define MISC_DOWN_CFG_SC_MESH_REACTIVATE_CYCLES_LEN    10
#define MISC_DOWN_CFG_SC_MESH_REACTIVATE_CYCLES_OFFSET 0

#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_LEN    1
#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_OFFSET 1
#define MISC_DOWN_CFG_PLL0_UNLOCK_LEN       1
#define MISC_DOWN_CFG_PLL0_UNLOCK_OFFSET    0

#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_INT_MASK_LEN    1
#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_INT_MASK_OFFSET 1
#define MISC_DOWN_CFG_PLL0_UNLOCK_INT_MASK_LEN       1
#define MISC_DOWN_CFG_PLL0_UNLOCK_INT_MASK_OFFSET    0

#define MISC_DOWN_CFG_LAST_RST_STATUS_CLR_LEN    1
#define MISC_DOWN_CFG_LAST_RST_STATUS_CLR_OFFSET 0

#define MISC_DOWN_CFG_SC_MAX2MIN_CYC_LEN       5
#define MISC_DOWN_CFG_SC_MAX2MIN_CYC_OFFSET    8
#define MISC_DOWN_CFG_SC_CDTC_REV_LEN          1
#define MISC_DOWN_CFG_SC_CDTC_REV_OFFSET       7
#define MISC_DOWN_CFG_SC_FDTC_REV_LEN          1
#define MISC_DOWN_CFG_SC_FDTC_REV_OFFSET       6
#define MISC_DOWN_CFG_SC_DTC_START_LEN         1
#define MISC_DOWN_CFG_SC_DTC_START_OFFSET      5
#define MISC_DOWN_CFG_SC_TIMING_CTRL_EN_LEN    1
#define MISC_DOWN_CFG_SC_TIMING_CTRL_EN_OFFSET 4
#define MISC_DOWN_CFG_SC_ONE2TWO_CYC_LEN       1
#define MISC_DOWN_CFG_SC_ONE2TWO_CYC_OFFSET    3
#define MISC_DOWN_CFG_SC_JM_RST_N_LEN          1
#define MISC_DOWN_CFG_SC_JM_RST_N_OFFSET       2
#define MISC_DOWN_CFG_SC_JM_CLK_EN_LEN         1
#define MISC_DOWN_CFG_SC_JM_CLK_EN_OFFSET      0

#define MISC_DOWN_CFG_SC_CDTC_GAP_LEN      5
#define MISC_DOWN_CFG_SC_CDTC_GAP_OFFSET   11
#define MISC_DOWN_CFG_SC_DTC_MARGIN_LEN    10
#define MISC_DOWN_CFG_SC_DTC_MARGIN_OFFSET 0

#define MISC_DOWN_CFG_SC_CDTC_CODE_INIT_LEN    8
#define MISC_DOWN_CFG_SC_CDTC_CODE_INIT_OFFSET 8
#define MISC_DOWN_CFG_SC_FDTC_CODE_INIT_LEN    8
#define MISC_DOWN_CFG_SC_FDTC_CODE_INIT_OFFSET 0

#define MISC_DOWN_CFG_SC_CDTC_CYC_LEN    5
#define MISC_DOWN_CFG_SC_CDTC_CYC_OFFSET 8
#define MISC_DOWN_CFG_SC_FDTC_CYC_LEN    5
#define MISC_DOWN_CFG_SC_FDTC_CYC_OFFSET 0

#define MISC_DOWN_CFG_SC_CDTC_STEP_LEN    6
#define MISC_DOWN_CFG_SC_CDTC_STEP_OFFSET 8
#define MISC_DOWN_CFG_SC_FDTC_STEP_LEN    7
#define MISC_DOWN_CFG_SC_FDTC_STEP_OFFSET 0

#define MISC_DOWN_CFG_SC_CDTC_LENGTH_LEN    8
#define MISC_DOWN_CFG_SC_CDTC_LENGTH_OFFSET 8
#define MISC_DOWN_CFG_SC_FDTC_LENGTH_LEN    8
#define MISC_DOWN_CFG_SC_FDTC_LENGTH_OFFSET 0

#define MISC_DOWN_CFG_PLL0_HI_LOCK_LEN    1
#define MISC_DOWN_CFG_PLL0_HI_LOCK_OFFSET 1
#define MISC_DOWN_CFG_PLL0_LOCK_LEN       1
#define MISC_DOWN_CFG_PLL0_LOCK_OFFSET    0

#define MISC_DOWN_CFG_PLL0_HI_FNPLL_STATE0_LEN    16
#define MISC_DOWN_CFG_PLL0_HI_FNPLL_STATE0_OFFSET 0

#define MISC_DOWN_CFG_TEST_DATA_FNPLL_1V2_LEN             8
#define MISC_DOWN_CFG_TEST_DATA_FNPLL_1V2_OFFSET          8
#define MISC_DOWN_CFG_CLOCK_LOST_FNPLL_1V2_LEN            1
#define MISC_DOWN_CFG_CLOCK_LOST_FNPLL_1V2_OFFSET         6
#define MISC_DOWN_CFG_BBPD_CALIB_SUCCESS_FNPLL_1V2_LEN    1
#define MISC_DOWN_CFG_BBPD_CALIB_SUCCESS_FNPLL_1V2_OFFSET 4
#define MISC_DOWN_CFG_BBPD_CALIB_FAIL_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_BBPD_CALIB_FAIL_FNPLL_1V2_OFFSET    3
#define MISC_DOWN_CFG_BBPD_CALIB_DONE_FNPLL_1V2_LEN       1
#define MISC_DOWN_CFG_BBPD_CALIB_DONE_FNPLL_1V2_OFFSET    2
#define MISC_DOWN_CFG_PLL_LOCK_ATE_FNPLL_1V2_LEN          1
#define MISC_DOWN_CFG_PLL_LOCK_ATE_FNPLL_1V2_OFFSET       1
#define MISC_DOWN_CFG_PLL_LOCK_FNPLL_1V2_LEN              1
#define MISC_DOWN_CFG_PLL_LOCK_FNPLL_1V2_OFFSET           0

#define MISC_DOWN_CFG_SC_ICG_ST_REF_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_REF_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_GPIO_DB_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_GPIO_DB_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_ICG_ST_MESH_LEN    1
#define MISC_DOWN_CFG_SC_ICG_ST_MESH_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC30_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC30_OFFSET 15
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC28_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC28_OFFSET 14
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC26_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC26_OFFSET 13
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC24_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC24_OFFSET 12
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC22_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC22_OFFSET 11
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC20_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC20_OFFSET 10
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC18_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC18_OFFSET 9
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC16_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC16_OFFSET 8
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC14_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC14_OFFSET 7
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC12_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC12_OFFSET 6
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC10_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC10_OFFSET 5
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC8_LEN     1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC8_OFFSET  4
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC6_LEN     1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC6_OFFSET  3
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC4_LEN     1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC4_OFFSET  2
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC2_LEN     1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC2_OFFSET  1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC0_LEN     1
#define MISC_DOWN_CFG_SC_SRST_ST_REQ_HW_AIC0_OFFSET  0

#define MISC_DOWN_CFG_SC_SRST_ST_ACG_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_ACG_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_CPM_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_CPM_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_CORE_LEN       1
#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_CORE_OFFSET    2
#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_BCBIST1_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_BCBIST1_OFFSET 1
#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_BCBIST0_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_DCIP_BCBIST0_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_DJTAG_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_DJTAG_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_FUNC_MBIST_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_FUNC_MBIST_OFFSET 0

#define MISC_DOWN_CFG_SC_SRST_ST_SYSCNT_LEN    1
#define MISC_DOWN_CFG_SC_SRST_ST_SYSCNT_OFFSET 0

#define MISC_DOWN_CFG_LAST_RST_STATUS_LEN    30
#define MISC_DOWN_CFG_LAST_RST_STATUS_OFFSET 0

#define MISC_DOWN_CFG_JM_CODE_A_LEN    8
#define MISC_DOWN_CFG_JM_CODE_A_OFFSET 8
#define MISC_DOWN_CFG_JM_CODE_B_LEN    8
#define MISC_DOWN_CFG_JM_CODE_B_OFFSET 0

#define MISC_DOWN_CFG_JM_CODE_C_LEN    8
#define MISC_DOWN_CFG_JM_CODE_C_OFFSET 8
#define MISC_DOWN_CFG_JM_CODE_D_LEN    8
#define MISC_DOWN_CFG_JM_CODE_D_OFFSET 0

#define MISC_DOWN_CFG_JM_CODE_E_LEN           8
#define MISC_DOWN_CFG_JM_CODE_E_OFFSET        8
#define MISC_DOWN_CFG_TEST_DTC_CURR_ST_LEN    3
#define MISC_DOWN_CFG_TEST_DTC_CURR_ST_OFFSET 4
#define MISC_DOWN_CFG_JM_OVERFLOW_LEN         1
#define MISC_DOWN_CFG_JM_OVERFLOW_OFFSET      3
#define MISC_DOWN_CFG_JM_UNDERFLOW_LEN        1
#define MISC_DOWN_CFG_JM_UNDERFLOW_OFFSET     2
#define MISC_DOWN_CFG_TEST_COMP_LEN           1
#define MISC_DOWN_CFG_TEST_COMP_OFFSET        1
#define MISC_DOWN_CFG_JM_DTC_MEA_DONE_LEN     1
#define MISC_DOWN_CFG_JM_DTC_MEA_DONE_OFFSET  0

#define MISC_DOWN_CFG_JM_CODE_MAX_LEN    8
#define MISC_DOWN_CFG_JM_CODE_MAX_OFFSET 8
#define MISC_DOWN_CFG_JM_CODE_MIN_LEN    8
#define MISC_DOWN_CFG_JM_CODE_MIN_OFFSET 0

#define MISC_DOWN_CFG_SC_ACG_CLK_OUT_DIV_64_LEN    1
#define MISC_DOWN_CFG_SC_ACG_CLK_OUT_DIV_64_OFFSET 6
#define MISC_DOWN_CFG_SC_ACG_TEST_OUT_FFS_LEN      4
#define MISC_DOWN_CFG_SC_ACG_TEST_OUT_FFS_OFFSET   2
#define MISC_DOWN_CFG_SC_ACG_GLITCH_RESULT_LEN     1
#define MISC_DOWN_CFG_SC_ACG_GLITCH_RESULT_OFFSET  1
#define MISC_DOWN_CFG_SC_ACG_LOCK_LEN              1
#define MISC_DOWN_CFG_SC_ACG_LOCK_OFFSET           0

#define MISC_DOWN_CFG_SC_ACG_TEST_OUT_CPM_LEN    4
#define MISC_DOWN_CFG_SC_ACG_TEST_OUT_CPM_OFFSET 20
#define MISC_DOWN_CFG_SC_ACG_CPM_DATA_LEN        16
#define MISC_DOWN_CFG_SC_ACG_CPM_DATA_OFFSET     0

#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_INT_STATUS_LEN    1
#define MISC_DOWN_CFG_PLL0_HI_UNLOCK_INT_STATUS_OFFSET 1
#define MISC_DOWN_CFG_PLL0_UNLOCK_INT_STATUS_LEN       1
#define MISC_DOWN_CFG_PLL0_UNLOCK_INT_STATUS_OFFSET    0

#define MISC_DOWN_CFG_SYSCTRL_LOCK_LEN    32
#define MISC_DOWN_CFG_SYSCTRL_LOCK_OFFSET 0

#define MISC_DOWN_CFG_SYSCTRL_UNLOCK_LEN    32
#define MISC_DOWN_CFG_SYSCTRL_UNLOCK_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV0_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV0_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV1_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV1_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV2_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV2_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV3_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV3_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV4_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV4_OFFSET 0

#define MISC_DOWN_CFG_SC_ECO_RSV5_LEN    32
#define MISC_DOWN_CFG_SC_ECO_RSV5_OFFSET 0

#define MISC_DOWN_CFG_FPGA_VERI_NUM_LEN    32
#define MISC_DOWN_CFG_FPGA_VERI_NUM_OFFSET 0

#endif // __MISC_DOWN_CFG_REG_OFFSET_FIELD_H__
