// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  sdmam_common_regs_reg_offset.h
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2018/11/19 15:40:05 Create file
// ******************************************************************************

#ifndef __SDMAM_COMMON_REGS_REG_OFFSET_H__
#define __SDMAM_COMMON_REGS_REG_OFFSET_H__

/* SDMAM_COMMON_REGS Base address of Module's Register */
#define SOC_SDMAM_COMMON_REGS_BASE                       (0x0)

/******************************************************************************/
/*                      SOC SDMAM_COMMON_REGS Registers' Definitions                            */
/******************************************************************************/

#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO0_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC00) /* SDMAM EMU PRESS CNT寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO1_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC04) /* SDMAM EMU PRESS CNT寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO2_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC08) /* SDMAM EMU PRESS CNT寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO3_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC0C) /* SDMAM EMU PRESS CNT寄存器3 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO4_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC10) /* SDMAM EMU PRESS CNT寄存器4 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO5_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC14) /* SDMAM EMU PRESS CNT寄存器5 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO6_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC18) /* SDMAM EMU PRESS CNT寄存器6 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO7_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC1C) /* SDMAM EMU PRESS CNT寄存器7 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO8_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC20) /* SDMAM EMU PRESS CNT寄存器8 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO9_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xC24) /* SDMAM EMU PRESS CNT寄存器9 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO10_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC28) /* SDMAM EMU PRESS CNT寄存器10 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO11_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC2C) /* SDMAM EMU PRESS CNT寄存器11 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO12_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC30) /* SDMAM EMU PRESS CNT寄存器12 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO13_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC34) /* SDMAM EMU PRESS CNT寄存器13 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO14_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC38) /* SDMAM EMU PRESS CNT寄存器14 */
#define SOC_SDMAM_COMMON_REGS_DFX_EMU_INFO15_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xC3C) /* SDMAM EMU PRESS CNT寄存器15 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO0_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD00) /* 探测SDMAM运行信息寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO1_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD04) /* 探测SDMAM运行信息寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO2_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD08) /* 探测SDMAM运行信息寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO3_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD0C) /* 探测SDMAM运行信息寄存器3 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO4_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD10) /* 探测SDMAM运行信息寄存器4 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO5_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD14) /* 探测SDMAM运行信息寄存器5 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO6_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD18) /* 探测SDMAM运行信息寄存器6 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO7_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD1C) /* 探测SDMAM运行信息寄存器7 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO8_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD20) /* 探测SDMAM运行信息寄存器8 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO9_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xD34) /* 探测SDMAM运行信息寄存器9 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO10_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD38) /* 探测SDMAM运行信息寄存器10 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO11_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD3C) /* 探测SDMAM运行信息寄存器11 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO12_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD40) /* 探测SDMAM运行信息寄存器12 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO13_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD44) /* 探测SDMAM运行信息寄存器13 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO14_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD48) /* 探测SDMAM运行信息寄存器14 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO15_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD4C) /* 探测SDMAM运行信息寄存器15 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO16_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD50) /* 探测SDMAM运行信息寄存器16 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO17_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD54) /* 探测SDMAM运行信息寄存器17 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO18_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD58) /* 探测SDMAM运行信息寄存器18 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO19_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD5C) /* 探测SDMAM运行信息寄存器19 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO20_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD60) /* 探测SDMAM运行信息寄存器20 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO21_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD64) /* 探测SDMAM运行信息寄存器21 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO22_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD68) /* 探测SDMAM运行信息寄存器22 */
#define SOC_SDMAM_COMMON_REGS_DFX_PROBE_INFO23_REG (SOC_SDMAM_COMMON_REGS_BASE + 0xD6C) /* 探测SDMAM运行信息寄存器23 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL0_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0xFD0) /* DFX ctrl Register0 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL1_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0xFD4) /* DFX ctrl Register1 */
#define SOC_SDMAM_COMMON_REGS_DFX_CTRL2_REG        (SOC_SDMAM_COMMON_REGS_BASE + 0xFD8) /* DFX ctrl Register2 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_MASK_NS_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xF00) /* 非安全中断屏蔽寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_MASK_S_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xF04) /* 安全中断屏蔽寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_IRQ_STATUS_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xF08) /* 安全和非安全通道中断状态寄存器 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG0_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xFE0) /* AXUSER配置寄存器0 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG1_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xFE4) /* AXUSER配置寄存器1 */
#define SOC_SDMAM_COMMON_REGS_DMA_AXUSER_REG2_REG  (SOC_SDMAM_COMMON_REGS_BASE + 0xFE8) /* AXUSER配置寄存器2 */
#define SOC_SDMAM_COMMON_REGS_DMA_ATSREQ_REG_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xFEC) /* 向SMMU发送ATS请求属性配置寄存器 */
#define SOC_SDMAM_COMMON_REGS_DFX_VERSION_ID_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xFF0) /* 版本号寄存器寄存器 */
#define SOC_SDMAM_COMMON_REGS_DFX_CNT_CLR_CE_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xFF4) /* CNT_CYC类型寄存器读清控制信号 */
#define SOC_SDMAM_COMMON_REGS_DFX_TEST_CTRL_REG    (SOC_SDMAM_COMMON_REGS_BASE + 0xFF8) /* DFX和计数器控制寄存器 */
#define SOC_SDMAM_COMMON_REGS_DFX_FEATURE_EN_REG   (SOC_SDMAM_COMMON_REGS_BASE + 0xFFC) /* 功能使能开关寄存器 */

#endif // __SDMAM_COMMON_REGS_REG_OFFSET_H__
