// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  sysctrl_cfg_reg_offset_field.h
// Project line  :  ICT
// Department    :  ICT Processor Chipset Development Dep
// Author        :  xxx
// Version       :  1.0
// Date          :  2018/6/25
// Description   :  The description of AI project
// Others        :  Generated automatically by nManager V4.2 
// History       :  xxx 2018/12/15 16:51:44 Create file
// ******************************************************************************

#ifndef __SYSCTRL_CFG_REG_OFFSET_FIELD_H__
#define __SYSCTRL_CFG_REG_OFFSET_FIELD_H__

#define SYSCTRL_CFG_PLL1_FOUTVCOEN_LEN        1
#define SYSCTRL_CFG_PLL1_FOUTVCOEN_OFFSET     30
#define SYSCTRL_CFG_PLL1_FOUTPOSTDIVEN_LEN    1
#define SYSCTRL_CFG_PLL1_FOUTPOSTDIVEN_OFFSET 29
#define SYSCTRL_CFG_PLL1_FOUT4PHASEEN_LEN     1
#define SYSCTRL_CFG_PLL1_FOUT4PHASEEN_OFFSET  28
#define SYSCTRL_CFG_PLL1_DACEN_LEN            1
#define SYSCTRL_CFG_PLL1_DACEN_OFFSET         27
#define SYSCTRL_CFG_PLL1_DSMEN_LEN            1
#define SYSCTRL_CFG_PLL1_DSMEN_OFFSET         26
#define SYSCTRL_CFG_PLL1_EN_LEN               1
#define SYSCTRL_CFG_PLL1_EN_OFFSET            25
#define SYSCTRL_CFG_PLL1_BYPASS_LEN           1
#define SYSCTRL_CFG_PLL1_BYPASS_OFFSET        24
#define SYSCTRL_CFG_PLL1_POSTDIV2_LEN         3
#define SYSCTRL_CFG_PLL1_POSTDIV2_OFFSET      21
#define SYSCTRL_CFG_PLL1_POSTDIV1_LEN         3
#define SYSCTRL_CFG_PLL1_POSTDIV1_OFFSET      18
#define SYSCTRL_CFG_PLL1_FBDIV_LEN            12
#define SYSCTRL_CFG_PLL1_FBDIV_OFFSET         6
#define SYSCTRL_CFG_PLL1_REFDIV_LEN           6
#define SYSCTRL_CFG_PLL1_REFDIV_OFFSET        0

#define SYSCTRL_CFG_PLL1_FRAC_LEN    24
#define SYSCTRL_CFG_PLL1_FRAC_OFFSET 0

#define SYSCTRL_CFG_PLL6_FOUTVCOEN_LEN        1
#define SYSCTRL_CFG_PLL6_FOUTVCOEN_OFFSET     30
#define SYSCTRL_CFG_PLL6_FOUTPOSTDIVEN_LEN    1
#define SYSCTRL_CFG_PLL6_FOUTPOSTDIVEN_OFFSET 29
#define SYSCTRL_CFG_PLL6_FOUT4PHASEEN_LEN     1
#define SYSCTRL_CFG_PLL6_FOUT4PHASEEN_OFFSET  28
#define SYSCTRL_CFG_PLL6_DACEN_LEN            1
#define SYSCTRL_CFG_PLL6_DACEN_OFFSET         27
#define SYSCTRL_CFG_PLL6_DSMEN_LEN            1
#define SYSCTRL_CFG_PLL6_DSMEN_OFFSET         26
#define SYSCTRL_CFG_PLL6_EN_LEN               1
#define SYSCTRL_CFG_PLL6_EN_OFFSET            25
#define SYSCTRL_CFG_PLL6_BYPASS_LEN           1
#define SYSCTRL_CFG_PLL6_BYPASS_OFFSET        24
#define SYSCTRL_CFG_PLL6_POSTDIV2_LEN         3
#define SYSCTRL_CFG_PLL6_POSTDIV2_OFFSET      21
#define SYSCTRL_CFG_PLL6_POSTDIV1_LEN         3
#define SYSCTRL_CFG_PLL6_POSTDIV1_OFFSET      18
#define SYSCTRL_CFG_PLL6_FBDIV_LEN            12
#define SYSCTRL_CFG_PLL6_FBDIV_OFFSET         6
#define SYSCTRL_CFG_PLL6_REFDIV_LEN           6
#define SYSCTRL_CFG_PLL6_REFDIV_OFFSET        0

#define SYSCTRL_CFG_PLL6_FRAC_LEN    24
#define SYSCTRL_CFG_PLL6_FRAC_OFFSET 0

#define SYSCTRL_CFG_PLL6_BYPASS_EXTERNAL_N_LEN    1
#define SYSCTRL_CFG_PLL6_BYPASS_EXTERNAL_N_OFFSET 1
#define SYSCTRL_CFG_PLL1_BYPASS_EXTERNAL_N_LEN    1
#define SYSCTRL_CFG_PLL1_BYPASS_EXTERNAL_N_OFFSET 0

#define SYSCTRL_CFG_PLL6_PERI_MODE_LEN    1
#define SYSCTRL_CFG_PLL6_PERI_MODE_OFFSET 1
#define SYSCTRL_CFG_PLL1_PERI_MODE_LEN    1
#define SYSCTRL_CFG_PLL1_PERI_MODE_OFFSET 0

#define SYSCTRL_CFG_PLL_TIME_LEN     25
#define SYSCTRL_CFG_PLL_TIME_OFFSET  3
#define SYSCTRL_CFG_PLL_EN_SW_LEN    1
#define SYSCTRL_CFG_PLL_EN_SW_OFFSET 1
#define SYSCTRL_CFG_PLL_OVER_LEN     1
#define SYSCTRL_CFG_PLL_OVER_OFFSET  0

#define SYSCTRL_CFG_MODECTRL_LEN    3
#define SYSCTRL_CFG_MODECTRL_OFFSET 0

#define SYSCTRL_CFG_HPM_CLK_SEL_LEN    1
#define SYSCTRL_CFG_HPM_CLK_SEL_OFFSET 0

#define SYSCTRL_CFG_FUNC_MBIST_CLK_SEL_LEN    1
#define SYSCTRL_CFG_FUNC_MBIST_CLK_SEL_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_CLK_SEL_LEN    2
#define SYSCTRL_CFG_TSENSOR_CLK_SEL_OFFSET 0

#define SYSCTRL_CFG_ALL_SCAN_SYS_INT_LEN    1
#define SYSCTRL_CFG_ALL_SCAN_SYS_INT_OFFSET 0

#define SYSCTRL_CFG_SC_BYPASS_ICG_EN_PLL_LEN    1
#define SYSCTRL_CFG_SC_BYPASS_ICG_EN_PLL_OFFSET 0

#define SYSCTRL_CFG_SYS_SOFT_RST_LEN    32
#define SYSCTRL_CFG_SYS_SOFT_RST_OFFSET 0

#define SYSCTRL_CFG_WDOG_RESET_CFG_LEN    32
#define SYSCTRL_CFG_WDOG_RESET_CFG_OFFSET 0

#define SYSCTRL_CFG_PORN_ENABLE_LEN    1
#define SYSCTRL_CFG_PORN_ENABLE_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_MBIGEN_LEN    1
#define SYSCTRL_CFG_ICG_EN_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_MBIGEN_LEN    1
#define SYSCTRL_CFG_ICG_DIS_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_FTE_LEN    1
#define SYSCTRL_CFG_ICG_EN_FTE_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_FTE_LEN    1
#define SYSCTRL_CFG_ICG_DIS_FTE_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_GPIO_LEN    3
#define SYSCTRL_CFG_ICG_EN_GPIO_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_GPIO_LEN    3
#define SYSCTRL_CFG_ICG_DIS_GPIO_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_DDRC_LEN    2
#define SYSCTRL_CFG_ICG_EN_DDRC_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_DDRC_LEN    2
#define SYSCTRL_CFG_ICG_DIS_DDRC_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_ICG_EN_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_ICG_DIS_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_ICG_EN_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_ICG_DIS_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_SMMU_TRANS_LEN    1
#define SYSCTRL_CFG_ICG_EN_SMMU_TRANS_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_SMMU_TRANS_LEN    1
#define SYSCTRL_CFG_ICG_DIS_SMMU_TRANS_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_SDMAM_LEN    1
#define SYSCTRL_CFG_ICG_EN_SDMAM_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_SDMAM_LEN    1
#define SYSCTRL_CFG_ICG_DIS_SDMAM_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_PROBE_LEN    1
#define SYSCTRL_CFG_ICG_EN_PROBE_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_PROBE_LEN    1
#define SYSCTRL_CFG_ICG_DIS_PROBE_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_WDOG_LEN    20
#define SYSCTRL_CFG_ICG_EN_WDOG_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_WDOG_LEN    20
#define SYSCTRL_CFG_ICG_DIS_WDOG_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_ICG_EN_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_ICG_DIS_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_SFC2X_LEN      1
#define SYSCTRL_CFG_ICG_EN_SFC2X_OFFSET   2
#define SYSCTRL_CFG_ICG_EN_SFC1X_LEN      1
#define SYSCTRL_CFG_ICG_EN_SFC1X_OFFSET   1
#define SYSCTRL_CFG_ICG_EN_SFC_BUS_LEN    1
#define SYSCTRL_CFG_ICG_EN_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_SFC2X_LEN      1
#define SYSCTRL_CFG_ICG_DIS_SFC2X_OFFSET   2
#define SYSCTRL_CFG_ICG_DIS_SFC1X_LEN      1
#define SYSCTRL_CFG_ICG_DIS_SFC1X_OFFSET   1
#define SYSCTRL_CFG_ICG_DIS_SFC_BUS_LEN    1
#define SYSCTRL_CFG_ICG_DIS_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_TIMER0_LEN    32
#define SYSCTRL_CFG_ICG_EN_TIMER0_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_TIMER0_LEN    32
#define SYSCTRL_CFG_ICG_DIS_TIMER0_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_TIMER1_LEN    28
#define SYSCTRL_CFG_ICG_EN_TIMER1_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_TIMER1_LEN    28
#define SYSCTRL_CFG_ICG_DIS_TIMER1_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_SEC_TIMER_LEN    2
#define SYSCTRL_CFG_ICG_EN_SEC_TIMER_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_SEC_TIMER_LEN    2
#define SYSCTRL_CFG_ICG_DIS_SEC_TIMER_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_REF_LEN    1
#define SYSCTRL_CFG_ICG_EN_REF_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_REF_LEN    1
#define SYSCTRL_CFG_ICG_DIS_REF_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_GPIO_DB_LEN    1
#define SYSCTRL_CFG_ICG_EN_GPIO_DB_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_GPIO_DB_LEN    1
#define SYSCTRL_CFG_ICG_DIS_GPIO_DB_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_DJTAG_LEN    1
#define SYSCTRL_CFG_ICG_EN_DJTAG_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_DJTAG_LEN    1
#define SYSCTRL_CFG_ICG_DIS_DJTAG_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_ICG_EN_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_ICG_DIS_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_HPM_LEN    1
#define SYSCTRL_CFG_ICG_EN_HPM_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_HPM_LEN    1
#define SYSCTRL_CFG_ICG_DIS_HPM_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_SYSCNT_LEN    1
#define SYSCTRL_CFG_ICG_EN_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_SYSCNT_LEN    1
#define SYSCTRL_CFG_ICG_DIS_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_ULTRASOC_LEN    1
#define SYSCTRL_CFG_ICG_EN_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_ICG_EN_CHIE_MON_LEN    1
#define SYSCTRL_CFG_ICG_EN_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_ULTRASOC_LEN    1
#define SYSCTRL_CFG_ICG_DIS_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_ICG_DIS_CHIE_MON_LEN    1
#define SYSCTRL_CFG_ICG_DIS_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_ICG_EN_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_ICG_EN_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_ICG_EN_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_ICG_EN_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_ICG_EN_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_ICG_DIS_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_ICG_DIS_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_ICG_DIS_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_ICG_DIS_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_ICG_DIS_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_MBIST_DDRC_HHA_LEN    2
#define SYSCTRL_CFG_ICG_EN_MBIST_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_MBIST_DDRC_HHA_LEN    2
#define SYSCTRL_CFG_ICG_DIS_MBIST_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_MESH_LEN    1
#define SYSCTRL_CFG_ICG_EN_MESH_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_MESH_LEN    1
#define SYSCTRL_CFG_ICG_DIS_MESH_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_ICG_EN_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_ICG_EN_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_ICG_EN_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_ICG_DIS_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_ICG_DIS_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_ICG_DIS_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_EN_L3D1_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_DIS_L3D1_OFFSET 0

#define SYSCTRL_CFG_ICG_EN_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_EN_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_ICG_DIS_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_DIS_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_MBIGEN_LEN    1
#define SYSCTRL_CFG_SRST_REQ_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_MBIGEN_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_SDMAM_LEN    1
#define SYSCTRL_CFG_SRST_REQ_SDMAM_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_SDMAM_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_SDMAM_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_FTE_LEN    1
#define SYSCTRL_CFG_SRST_REQ_FTE_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_FTE_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_FTE_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_GPIO_LEN    3
#define SYSCTRL_CFG_SRST_REQ_GPIO_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_GPIO_LEN    3
#define SYSCTRL_CFG_SRST_DREQ_GPIO_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_REQ_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_SRST_REQ_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_SRST_REQ_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_SFC1X_LEN      1
#define SYSCTRL_CFG_SRST_REQ_SFC1X_OFFSET   2
#define SYSCTRL_CFG_SRST_REQ_SFC2X_LEN      1
#define SYSCTRL_CFG_SRST_REQ_SFC2X_OFFSET   1
#define SYSCTRL_CFG_SRST_REQ_SFC_BUS_LEN    1
#define SYSCTRL_CFG_SRST_REQ_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_SFC1X_LEN      1
#define SYSCTRL_CFG_SRST_DREQ_SFC1X_OFFSET   2
#define SYSCTRL_CFG_SRST_DREQ_SFC2X_LEN      1
#define SYSCTRL_CFG_SRST_DREQ_SFC2X_OFFSET   1
#define SYSCTRL_CFG_SRST_DREQ_SFC_BUS_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_TIMER0_LEN    32
#define SYSCTRL_CFG_SRST_REQ_TIMER0_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_TIMER0_LEN    32
#define SYSCTRL_CFG_SRST_DREQ_TIMER0_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_TIMER1_LEN    28
#define SYSCTRL_CFG_SRST_REQ_TIMER1_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_TIMER1_LEN    28
#define SYSCTRL_CFG_SRST_DREQ_TIMER1_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_TIMER_SEC_LEN    2
#define SYSCTRL_CFG_SRST_REQ_TIMER_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_TIMER_SEC_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_TIMER_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_WDOG_LEN    20
#define SYSCTRL_CFG_SRST_REQ_WDOG_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_WDOG_LEN    20
#define SYSCTRL_CFG_SRST_DREQ_WDOG_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_SRST_REQ_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_PHY_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_REQ_PHY_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_PHY_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_PHY_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_ULTRASOC_LEN    1
#define SYSCTRL_CFG_SRST_REQ_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_SRST_REQ_CHIE_MON_LEN    1
#define SYSCTRL_CFG_SRST_REQ_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_ULTRASOC_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_SRST_DREQ_CHIE_MON_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_STATUS_LEN    1
#define SYSCTRL_CFG_SRST_REQ_STATUS_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_STATUS_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_STATUS_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_SRST_REQ_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_SRST_REQ_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_SRST_REQ_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_SRST_REQ_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_SRST_REQ_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_SRST_DREQ_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_SRST_DREQ_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_SRST_DREQ_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_DJTAG_LEN    1
#define SYSCTRL_CFG_SRST_REQ_DJTAG_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_DJTAG_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_DJTAG_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_SRST_REQ_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_HPM_LEN    1
#define SYSCTRL_CFG_SRST_REQ_HPM_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_HPM_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_HPM_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_SYSCNT_LEN    1
#define SYSCTRL_CFG_SRST_REQ_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_SYSCNT_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_MBIST_HHA1_LEN    2
#define SYSCTRL_CFG_SRST_REQ_MBIST_HHA1_OFFSET 2
#define SYSCTRL_CFG_SRST_REQ_MBIST_HHA0_LEN    2
#define SYSCTRL_CFG_SRST_REQ_MBIST_HHA0_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_MBIST_HHA1_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_MBIST_HHA1_OFFSET 2
#define SYSCTRL_CFG_SRST_DREQ_MBIST_HHA0_LEN    2
#define SYSCTRL_CFG_SRST_DREQ_MBIST_HHA0_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_SRST_REQ_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_SRST_REQ_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_SRST_REQ_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_SRST_DREQ_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_REQ_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_REQ_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_REQ_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_DREQ_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_DREQ_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_SC_DIE_ID_LEN    2
#define SYSCTRL_CFG_SC_DIE_ID_OFFSET 0

#define SYSCTRL_CFG_SC_SOCKET_ID_LEN    2
#define SYSCTRL_CFG_SC_SOCKET_ID_OFFSET 0

#define SYSCTRL_CFG_SYSCNT_CLK_SEL_LEN    1
#define SYSCTRL_CFG_SYSCNT_CLK_SEL_OFFSET 0

#define SYSCTRL_CFG_ERRRSP_DISABLE_LEN    1
#define SYSCTRL_CFG_ERRRSP_DISABLE_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_DIG_ULTRAHIGH_LEN    32
#define SYSCTRL_CFG_TSENSOR_DIG_ULTRAHIGH_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_DIG_HIGH_LEN    32
#define SYSCTRL_CFG_TSENSOR_DIG_HIGH_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_DIG_LOW_LEN    32
#define SYSCTRL_CFG_TSENSOR_DIG_LOW_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_SAMPLE_SHIFT_NUM_LEN    4
#define SYSCTRL_CFG_TSENSOR_SAMPLE_SHIFT_NUM_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_DIG_EN_LEN     1
#define SYSCTRL_CFG_TSENSOR_DIG_EN_OFFSET  16
#define SYSCTRL_CFG_TSENSOR_DIG_CFG_LEN    16
#define SYSCTRL_CFG_TSENSOR_DIG_CFG_OFFSET 0

#define SYSCTRL_CFG_DFF_IGNORE_CORE_LEN       14
#define SYSCTRL_CFG_DFF_IGNORE_CORE_OFFSET    7
#define SYSCTRL_CFG_DETECT_PERIOD_CORE_LEN    2
#define SYSCTRL_CFG_DETECT_PERIOD_CORE_OFFSET 5
#define SYSCTRL_CFG_CLK_DIV_CFG_CORE_LEN      2
#define SYSCTRL_CFG_CLK_DIV_CFG_CORE_OFFSET   3
#define SYSCTRL_CFG_DETECT_ENABLE_CORE_LEN    3
#define SYSCTRL_CFG_DETECT_ENABLE_CORE_OFFSET 0

#define SYSCTRL_CFG_TEST_IN_CORE_LEN             8
#define SYSCTRL_CFG_TEST_IN_CORE_OFFSET          22
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_CORE_LEN    1
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_CORE_OFFSET 21
#define SYSCTRL_CFG_BYPASS_ENABLE_CORE_LEN       1
#define SYSCTRL_CFG_BYPASS_ENABLE_CORE_OFFSET    20
#define SYSCTRL_CFG_DC_TSEL_CORE_LEN             2
#define SYSCTRL_CFG_DC_TSEL_CORE_OFFSET          18
#define SYSCTRL_CFG_DFF_TSEL_CORE_LEN            3
#define SYSCTRL_CFG_DFF_TSEL_CORE_OFFSET         15
#define SYSCTRL_CFG_DFF_TEST_E_CORE_LEN          1
#define SYSCTRL_CFG_DFF_TEST_E_CORE_OFFSET       14
#define SYSCTRL_CFG_DFF_LIMIT_CORE_LEN           14
#define SYSCTRL_CFG_DFF_LIMIT_CORE_OFFSET        0

#define SYSCTRL_CFG_DETECT_PERIOD_BIST0_LEN       2
#define SYSCTRL_CFG_DETECT_PERIOD_BIST0_OFFSET    7
#define SYSCTRL_CFG_CLK_DIV_CFG_BIST0_LEN         2
#define SYSCTRL_CFG_CLK_DIV_CFG_BIST0_OFFSET      5
#define SYSCTRL_CFG_DETECT_ENABLE_BIST0_LEN       1
#define SYSCTRL_CFG_DETECT_ENABLE_BIST0_OFFSET    4
#define SYSCTRL_CFG_BYPASS_ENABLE_BIST0_LEN       1
#define SYSCTRL_CFG_BYPASS_ENABLE_BIST0_OFFSET    3
#define SYSCTRL_CFG_DC_TSEL_BIST0_LEN             2
#define SYSCTRL_CFG_DC_TSEL_BIST0_OFFSET          1
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_BIST0_LEN    1
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_BIST0_OFFSET 0

#define SYSCTRL_CFG_DETECT_PERIOD_BIST4_LEN       2
#define SYSCTRL_CFG_DETECT_PERIOD_BIST4_OFFSET    7
#define SYSCTRL_CFG_CLK_DIV_CFG_BIST4_LEN         2
#define SYSCTRL_CFG_CLK_DIV_CFG_BIST4_OFFSET      5
#define SYSCTRL_CFG_DETECT_ENABLE_BIST4_LEN       1
#define SYSCTRL_CFG_DETECT_ENABLE_BIST4_OFFSET    4
#define SYSCTRL_CFG_BYPASS_ENABLE_BIST4_LEN       1
#define SYSCTRL_CFG_BYPASS_ENABLE_BIST4_OFFSET    3
#define SYSCTRL_CFG_DC_TSEL_BIST4_LEN             2
#define SYSCTRL_CFG_DC_TSEL_BIST4_OFFSET          1
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_BIST4_LEN    1
#define SYSCTRL_CFG_FORCE_ERR_ENABLE_BIST4_OFFSET 0

#define SYSCTRL_CFG_SC_RCD_DRV_LEN    3
#define SYSCTRL_CFG_SC_RCD_DRV_OFFSET 0

#define SYSCTRL_CFG_SC_RCD_SEL_LEN    3
#define SYSCTRL_CFG_SC_RCD_SEL_OFFSET 0

#define SYSCTRL_CFG_SC_DBGACK_EN_LEN     1
#define SYSCTRL_CFG_SC_DBGACK_EN_OFFSET  1
#define SYSCTRL_CFG_SC_DBGACK_SEL_LEN    1
#define SYSCTRL_CFG_SC_DBGACK_SEL_OFFSET 0

#define SYSCTRL_CFG_AXI_CACHE_ULTRASOC_LEN    4
#define SYSCTRL_CFG_AXI_CACHE_ULTRASOC_OFFSET 28
#define SYSCTRL_CFG_AXI_USER_ULTRASOC_LEN     6
#define SYSCTRL_CFG_AXI_USER_ULTRASOC_OFFSET  0

#define SYSCTRL_CFG_ULTRASOC_MSG_SEL_LEN    1
#define SYSCTRL_CFG_ULTRASOC_MSG_SEL_OFFSET 0

#define SYSCTRL_CFG_AXI_USER_NS_ULTRASOC_LEN    1
#define SYSCTRL_CFG_AXI_USER_NS_ULTRASOC_OFFSET 0

#define SYSCTRL_CFG_SC_DDRC_ENABLE_LEN    4
#define SYSCTRL_CFG_SC_DDRC_ENABLE_OFFSET 0

#define SYSCTRL_CFG_SC_EXT_INT_POLARITY_LEN    9
#define SYSCTRL_CFG_SC_EXT_INT_POLARITY_OFFSET 0

#define SYSCTRL_CFG_SC_EXT_INT_MASK_LEN    9
#define SYSCTRL_CFG_SC_EXT_INT_MASK_OFFSET 0

#define SYSCTRL_CFG_IO_SDA0_DS3_LEN             1
#define SYSCTRL_CFG_IO_SDA0_DS3_OFFSET          12
#define SYSCTRL_CFG_IO_SCL0_DS3_LEN             1
#define SYSCTRL_CFG_IO_SCL0_DS3_OFFSET          11
#define SYSCTRL_CFG_IO_RST_OUT_DS3_LEN          1
#define SYSCTRL_CFG_IO_RST_OUT_DS3_OFFSET       10
#define SYSCTRL_CFG_IO_WDG_RSTN_DS3_LEN         1
#define SYSCTRL_CFG_IO_WDG_RSTN_DS3_OFFSET      9
#define SYSCTRL_CFG_IO_RST_ACK_DS3_LEN          1
#define SYSCTRL_CFG_IO_RST_ACK_DS3_OFFSET       8
#define SYSCTRL_CFG_IO_PMBUS_SCL_DS3_LEN        1
#define SYSCTRL_CFG_IO_PMBUS_SCL_DS3_OFFSET     7
#define SYSCTRL_CFG_IO_PMBUS_SDA_DS3_LEN        1
#define SYSCTRL_CFG_IO_PMBUS_SDA_DS3_OFFSET     6
#define SYSCTRL_CFG_IO_PMBUS_ALERT_N_DS3_LEN    1
#define SYSCTRL_CFG_IO_PMBUS_ALERT_N_DS3_OFFSET 5
#define SYSCTRL_CFG_IO_GPIO0_DS3_LEN            1
#define SYSCTRL_CFG_IO_GPIO0_DS3_OFFSET         4
#define SYSCTRL_CFG_IO_GPIO1_DS3_LEN            1
#define SYSCTRL_CFG_IO_GPIO1_DS3_OFFSET         3
#define SYSCTRL_CFG_IO_GPIO14_DS3_LEN           1
#define SYSCTRL_CFG_IO_GPIO14_DS3_OFFSET        2
#define SYSCTRL_CFG_IO_GPIO61_DS3_LEN           1
#define SYSCTRL_CFG_IO_GPIO61_DS3_OFFSET        1
#define SYSCTRL_CFG_IO_GPIO62_DS3_LEN           1
#define SYSCTRL_CFG_IO_GPIO62_DS3_OFFSET        0

#define SYSCTRL_CFG_IO_MDIO0_CLK_DS3_LEN     1
#define SYSCTRL_CFG_IO_MDIO0_CLK_DS3_OFFSET  21
#define SYSCTRL_CFG_IO_MDIO0_DATA_DS3_LEN    1
#define SYSCTRL_CFG_IO_MDIO0_DATA_DS3_OFFSET 20
#define SYSCTRL_CFG_IO_GPIO2_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO2_DS3_OFFSET      19
#define SYSCTRL_CFG_IO_GPIO3_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO3_DS3_OFFSET      18
#define SYSCTRL_CFG_IO_GPIO4_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO4_DS3_OFFSET      17
#define SYSCTRL_CFG_IO_GPIO5_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO5_DS3_OFFSET      16
#define SYSCTRL_CFG_IO_GPIO6_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO6_DS3_OFFSET      15
#define SYSCTRL_CFG_IO_GPIO7_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO7_DS3_OFFSET      14
#define SYSCTRL_CFG_IO_GPIO8_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO8_DS3_OFFSET      13
#define SYSCTRL_CFG_IO_GPIO9_DS3_LEN         1
#define SYSCTRL_CFG_IO_GPIO9_DS3_OFFSET      12
#define SYSCTRL_CFG_IO_GPIO10_DS3_LEN        1
#define SYSCTRL_CFG_IO_GPIO10_DS3_OFFSET     11
#define SYSCTRL_CFG_IO_GPIO11_DS3_LEN        1
#define SYSCTRL_CFG_IO_GPIO11_DS3_OFFSET     10
#define SYSCTRL_CFG_IO_GPIO12_DS3_LEN        1
#define SYSCTRL_CFG_IO_GPIO12_DS3_OFFSET     9
#define SYSCTRL_CFG_IO_GPIO13_DS3_LEN        1
#define SYSCTRL_CFG_IO_GPIO13_DS3_OFFSET     8
#define SYSCTRL_CFG_IO_SPICK0_DS3_LEN        1
#define SYSCTRL_CFG_IO_SPICK0_DS3_OFFSET     7
#define SYSCTRL_CFG_IO_SPICSN0_0_DS3_LEN     1
#define SYSCTRL_CFG_IO_SPICSN0_0_DS3_OFFSET  6
#define SYSCTRL_CFG_IO_SPICSN0_1_DS3_LEN     1
#define SYSCTRL_CFG_IO_SPICSN0_1_DS3_OFFSET  5
#define SYSCTRL_CFG_IO_SPICSN0_2_DS3_LEN     1
#define SYSCTRL_CFG_IO_SPICSN0_2_DS3_OFFSET  4
#define SYSCTRL_CFG_IO_URXD0_DS3_LEN         1
#define SYSCTRL_CFG_IO_URXD0_DS3_OFFSET      3
#define SYSCTRL_CFG_IO_UTXD0_DS3_LEN         1
#define SYSCTRL_CFG_IO_UTXD0_DS3_OFFSET      2
#define SYSCTRL_CFG_IO_SDA1_DS3_LEN          1
#define SYSCTRL_CFG_IO_SDA1_DS3_OFFSET       1
#define SYSCTRL_CFG_IO_SCL1_DS3_LEN          1
#define SYSCTRL_CFG_IO_SCL1_DS3_OFFSET       0

#define SYSCTRL_CFG_SC_MPAM_READ_MERGE_EN_LEN    1
#define SYSCTRL_CFG_SC_MPAM_READ_MERGE_EN_OFFSET 0

#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS0_LEN    32
#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS0_OFFSET 0

#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS1_LEN    32
#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS1_OFFSET 0

#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS2_LEN    32
#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS2_OFFSET 0

#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS3_LEN    32
#define SYSCTRL_CFG_SC_CMD_DELY_DEFINE_CFG_BUS3_OFFSET 0

#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS0_LEN    10
#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS0_OFFSET 0

#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS1_LEN    10
#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS1_OFFSET 0

#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS2_LEN    10
#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS2_OFFSET 0

#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS3_LEN    10
#define SYSCTRL_CFG_RD_WAIT_CYCLE_CFG_BUS3_OFFSET 0

#define SYSCTRL_CFG_SFC_CLK_SEL_LEN    2
#define SYSCTRL_CFG_SFC_CLK_SEL_OFFSET 0

#define SYSCTRL_CFG_MEM_POWER_MODE_SMMU_LEN    6
#define SYSCTRL_CFG_MEM_POWER_MODE_SMMU_OFFSET 12
#define SYSCTRL_CFG_SP_RAM_TMOD_SMMU_LEN       10
#define SYSCTRL_CFG_SP_RAM_TMOD_SMMU_OFFSET    0

#define SYSCTRL_CFG_MEM_CFG_HISI_SP_ULTRASOC_LEN    8
#define SYSCTRL_CFG_MEM_CFG_HISI_SP_ULTRASOC_OFFSET 0

#define SYSCTRL_CFG_TIMER32_EN_EXTERNAL_LEN    32
#define SYSCTRL_CFG_TIMER32_EN_EXTERNAL_OFFSET 0

#define SYSCTRL_CFG_TIMER64_EN_EXTERNA_LEN    32
#define SYSCTRL_CFG_TIMER64_EN_EXTERNA_OFFSET 0

#define SYSCTRL_CFG_SECURE_TIMER1_EN_EXTERNAL_LEN    1
#define SYSCTRL_CFG_SECURE_TIMER1_EN_EXTERNAL_OFFSET 1
#define SYSCTRL_CFG_SECURE_TIMER0_EN_EXTERNAL_LEN    1
#define SYSCTRL_CFG_SECURE_TIMER0_EN_EXTERNAL_OFFSET 0

#define SYSCTRL_CFG_TIMER32_CLK_SEL0_L_LEN    32
#define SYSCTRL_CFG_TIMER32_CLK_SEL0_L_OFFSET 0

#define SYSCTRL_CFG_TIMER32_CLK_SEL0_M_LEN    8
#define SYSCTRL_CFG_TIMER32_CLK_SEL0_M_OFFSET 0

#define SYSCTRL_CFG_TIMER64_CLK_SEL0_LEN    20
#define SYSCTRL_CFG_TIMER64_CLK_SEL0_OFFSET 0

#define SYSCTRL_CFG_TIMER32_CLK_SEL1_L_LEN    32
#define SYSCTRL_CFG_TIMER32_CLK_SEL1_L_OFFSET 0

#define SYSCTRL_CFG_TIMER32_CLK_SEL1_M_LEN    8
#define SYSCTRL_CFG_TIMER32_CLK_SEL1_M_OFFSET 0

#define SYSCTRL_CFG_TIMER64_CLK_SEL1_LEN    20
#define SYSCTRL_CFG_TIMER64_CLK_SEL1_OFFSET 0

#define SYSCTRL_CFG_SEC_TIMER_CLK_SEL1_LEN    2
#define SYSCTRL_CFG_SEC_TIMER_CLK_SEL1_OFFSET 2
#define SYSCTRL_CFG_SEC_TIMER_CLK_SEL0_LEN    2
#define SYSCTRL_CFG_SEC_TIMER_CLK_SEL0_OFFSET 0

#define SYSCTRL_CFG_SC_RST_REQ_MASK_WDOG_SEC1_LEN    1
#define SYSCTRL_CFG_SC_RST_REQ_MASK_WDOG_SEC1_OFFSET 1
#define SYSCTRL_CFG_SC_RST_REQ_MASK_WDOG_SEC0_LEN    1
#define SYSCTRL_CFG_SC_RST_REQ_MASK_WDOG_SEC0_OFFSET 0

#define SYSCTRL_CFG_SC_RAS1_ERI_IMU_EN_LEN    1
#define SYSCTRL_CFG_SC_RAS1_ERI_IMU_EN_OFFSET 3
#define SYSCTRL_CFG_SC_RAS1_FHI_IMU_EN_LEN    1
#define SYSCTRL_CFG_SC_RAS1_FHI_IMU_EN_OFFSET 2
#define SYSCTRL_CFG_SC_RAS0_ERI_IMU_EN_LEN    1
#define SYSCTRL_CFG_SC_RAS0_ERI_IMU_EN_OFFSET 1
#define SYSCTRL_CFG_SC_RAS0_FHI_IMU_EN_LEN    1
#define SYSCTRL_CFG_SC_RAS0_FHI_IMU_EN_OFFSET 0

#define SYSCTRL_CFG_SC_BUS_NUM_LEN    8
#define SYSCTRL_CFG_SC_BUS_NUM_OFFSET 0

#define SYSCTRL_CFG_SC_DEV_NUM_LEN    8
#define SYSCTRL_CFG_SC_DEV_NUM_OFFSET 0

#define SYSCTRL_CFG_MBIST_CPUI_ENABLE_LEN    1
#define SYSCTRL_CFG_MBIST_CPUI_ENABLE_OFFSET 0

#define SYSCTRL_CFG_MBIST_CPUI_DATAIN_LEN    32
#define SYSCTRL_CFG_MBIST_CPUI_DATAIN_OFFSET 0

#define SYSCTRL_CFG_MBIST_CPUI_WRITE_EN_LEN    1
#define SYSCTRL_CFG_MBIST_CPUI_WRITE_EN_OFFSET 0

#define SYSCTRL_CFG_MBIST_SMS_FUNC_MBIST_RESET_LEN    1
#define SYSCTRL_CFG_MBIST_SMS_FUNC_MBIST_RESET_OFFSET 0

#define SYSCTRL_CFG_MBIST_REQ_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_MBIST_REQ_DDRC_HHA_OFFSET 2
#define SYSCTRL_CFG_MBIST_REQ_L3D1_LEN        1
#define SYSCTRL_CFG_MBIST_REQ_L3D1_OFFSET     1
#define SYSCTRL_CFG_MBIST_REQ_L3D0_LEN        1
#define SYSCTRL_CFG_MBIST_REQ_L3D0_OFFSET     0

#define SYSCTRL_CFG_SC_BYP_EN_SFC_MEM_LEN    1
#define SYSCTRL_CFG_SC_BYP_EN_SFC_MEM_OFFSET 1
#define SYSCTRL_CFG_SC_BYP_EN_SFC_REG_LEN    1
#define SYSCTRL_CFG_SC_BYP_EN_SFC_REG_OFFSET 0

#define SYSCTRL_CFG_SC_DAW_EN_LEN      1
#define SYSCTRL_CFG_SC_DAW_EN_OFFSET   25
#define SYSCTRL_CFG_SC_DAW_SIZE_LEN    5
#define SYSCTRL_CFG_SC_DAW_SIZE_OFFSET 20
#define SYSCTRL_CFG_SC_DAW_ADDR_LEN    12
#define SYSCTRL_CFG_SC_DAW_ADDR_OFFSET 0

#define SYSCTRL_CFG_SC_CLOSE_PORT_DDRHHA_LEN    1
#define SYSCTRL_CFG_SC_CLOSE_PORT_DDRHHA_OFFSET 3
#define SYSCTRL_CFG_SC_CLOSE_PORT_PERI_LEN      1
#define SYSCTRL_CFG_SC_CLOSE_PORT_PERI_OFFSET   2
#define SYSCTRL_CFG_SC_CLOSE_PORT_L2BUFF_LEN    1
#define SYSCTRL_CFG_SC_CLOSE_PORT_L2BUFF_OFFSET 1
#define SYSCTRL_CFG_SC_CLOSE_PORT_L3D_LEN       1
#define SYSCTRL_CFG_SC_CLOSE_PORT_L3D_OFFSET    0

#define SYSCTRL_CFG_SC_MESH_REACTIVATE_EN_LEN    1
#define SYSCTRL_CFG_SC_MESH_REACTIVATE_EN_OFFSET 0

#define SYSCTRL_CFG_SC_MESH_REACTIVATE_CYCLES_LEN    10
#define SYSCTRL_CFG_SC_MESH_REACTIVATE_CYCLES_OFFSET 0

#define SYSCTRL_CFG_SC_TS_EN_LEN    1
#define SYSCTRL_CFG_SC_TS_EN_OFFSET 0

#define SYSCTRL_CFG_PLL1_UNLOCK_LEN    1
#define SYSCTRL_CFG_PLL1_UNLOCK_OFFSET 0

#define SYSCTRL_CFG_PLL6_UNLOCK_INT_MASK_LEN    1
#define SYSCTRL_CFG_PLL6_UNLOCK_INT_MASK_OFFSET 1
#define SYSCTRL_CFG_PLL1_UNLOCK_INT_MASK_LEN    1
#define SYSCTRL_CFG_PLL1_UNLOCK_INT_MASK_OFFSET 0

#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_LEN    1
#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_OFFSET 0

#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_INT_MASK_LEN    1
#define SYSCTRL_CFG_DJTAG_STA_TIMEOUT_INT_MASK_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_LEN    1
#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_OFFSET 2
#define SYSCTRL_CFG_TSENSOR_OVER_LEN          1
#define SYSCTRL_CFG_TSENSOR_OVER_OFFSET       1
#define SYSCTRL_CFG_TSENSOR_UNDER_LEN         1
#define SYSCTRL_CFG_TSENSOR_UNDER_OFFSET      0

#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_INT_MASK_LEN    1
#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_INT_MASK_OFFSET 2
#define SYSCTRL_CFG_TSENSOR_OVER_INT_MASK_LEN          1
#define SYSCTRL_CFG_TSENSOR_OVER_INT_MASK_OFFSET       1
#define SYSCTRL_CFG_TSENSOR_UNDER_INT_MASK_LEN         1
#define SYSCTRL_CFG_TSENSOR_UNDER_INT_MASK_OFFSET      0

#define SYSCTRL_CFG_SC_PLL6_UNLOCK_STATUS_CLR_LEN    1
#define SYSCTRL_CFG_SC_PLL6_UNLOCK_STATUS_CLR_OFFSET 0

#define SYSCTRL_CFG_INT_MODE_PERF_L3T_LEN     1
#define SYSCTRL_CFG_INT_MODE_PERF_L3T_OFFSET  1
#define SYSCTRL_CFG_INT_MODE_PERF_DDRC_LEN    1
#define SYSCTRL_CFG_INT_MODE_PERF_DDRC_OFFSET 0

#define SYSCTRL_CFG_XTAL_TIME_LEN     16
#define SYSCTRL_CFG_XTAL_TIME_OFFSET  3
#define SYSCTRL_CFG_XTAL_EN_SW_LEN    1
#define SYSCTRL_CFG_XTAL_EN_SW_OFFSET 1
#define SYSCTRL_CFG_XTAL_OVER_LEN     1
#define SYSCTRL_CFG_XTAL_OVER_OFFSET  0

#define SYSCTRL_CFG_SC_ITCR_LEN    1
#define SYSCTRL_CFG_SC_ITCR_OFFSET 0

#define SYSCTRL_CFG_SC_ITIR0_LEN    13
#define SYSCTRL_CFG_SC_ITIR0_OFFSET 0

#define SYSCTRL_CFG_SC_ITOR_LEN    11
#define SYSCTRL_CFG_SC_ITOR_OFFSET 0

#define SYSCTRL_CFG_SC_CNT_DATA_CFG_LEN    25
#define SYSCTRL_CFG_SC_CNT_DATA_CFG_OFFSET 0



#define SYSCTRL_CFG_TEST_LOAD_TIME_LEN    1
#define SYSCTRL_CFG_TEST_LOAD_TIME_OFFSET 2
#define SYSCTRL_CFG_TEST_PLL_EN_LEN       1
#define SYSCTRL_CFG_TEST_PLL_EN_OFFSET    1
#define SYSCTRL_CFG_TEST_MODE_EN_LEN      1
#define SYSCTRL_CFG_TEST_MODE_EN_OFFSET   0

#define SYSCTRL_CFG_IN_MD_TYPE_LEN    1
#define SYSCTRL_CFG_IN_MD_TYPE_OFFSET 7
#define SYSCTRL_CFG_IT_MD_CLK_LEN     3
#define SYSCTRL_CFG_IT_MD_CLK_OFFSET  4
#define SYSCTRL_CFG_IT_MD_CTRL_LEN    3
#define SYSCTRL_CFG_IT_MD_CTRL_OFFSET 1
#define SYSCTRL_CFG_IT_MD_EN_LEN      1
#define SYSCTRL_CFG_IT_MD_EN_OFFSET   0

#define SYSCTRL_CFG_IT_MD_STAT_LEN    1
#define SYSCTRL_CFG_IT_MD_STAT_OFFSET 0

#define SYSCTRL_CFG_CHAIN3_ERR_INT_LEN    1
#define SYSCTRL_CFG_CHAIN3_ERR_INT_OFFSET 3
#define SYSCTRL_CFG_CHAIN2_ERR_INT_LEN    1
#define SYSCTRL_CFG_CHAIN2_ERR_INT_OFFSET 2
#define SYSCTRL_CFG_CHAIN1_ERR_INT_LEN    1
#define SYSCTRL_CFG_CHAIN1_ERR_INT_OFFSET 1
#define SYSCTRL_CFG_CHAIN0_ERR_INT_LEN    1
#define SYSCTRL_CFG_CHAIN0_ERR_INT_OFFSET 0

#define SYSCTRL_CFG_CHAIN3_ERR_INTMASK_LEN    1
#define SYSCTRL_CFG_CHAIN3_ERR_INTMASK_OFFSET 3
#define SYSCTRL_CFG_CHAIN2_ERR_INTMASK_LEN    1
#define SYSCTRL_CFG_CHAIN2_ERR_INTMASK_OFFSET 2
#define SYSCTRL_CFG_CHAIN1_ERR_INTMASK_LEN    1
#define SYSCTRL_CFG_CHAIN1_ERR_INTMASK_OFFSET 1
#define SYSCTRL_CFG_CHAIN0_ERR_INTMASK_LEN    1
#define SYSCTRL_CFG_CHAIN0_ERR_INTMASK_OFFSET 0

#define SYSCTRL_CFG_CHAIN3_ERR_INTSTATUS_LEN    1
#define SYSCTRL_CFG_CHAIN3_ERR_INTSTATUS_OFFSET 3
#define SYSCTRL_CFG_CHAIN2_ERR_INTSTATUS_LEN    1
#define SYSCTRL_CFG_CHAIN2_ERR_INTSTATUS_OFFSET 2
#define SYSCTRL_CFG_CHAIN1_ERR_INTSTATUS_LEN    1
#define SYSCTRL_CFG_CHAIN1_ERR_INTSTATUS_OFFSET 1
#define SYSCTRL_CFG_CHAIN0_ERR_INTSTATUS_LEN    1
#define SYSCTRL_CFG_CHAIN0_ERR_INTSTATUS_OFFSET 0

#define SYSCTRL_CFG_GIC_NOCMT_IRQ_SRC_LEN    16
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_SRC_OFFSET 0

#define SYSCTRL_CFG_GIC_NOCMT_IRQ_INT_MASK_LEN    16
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_INT_MASK_OFFSET 0

#define SYSCTRL_CFG_SC_GIC_NOCMT_RST_OUT_EN_LEN    1
#define SYSCTRL_CFG_SC_GIC_NOCMT_RST_OUT_EN_OFFSET 0

#define SYSCTRL_CFG_SC_GIC_NOCMT_IRQ_SEL_LEN    1
#define SYSCTRL_CFG_SC_GIC_NOCMT_IRQ_SEL_OFFSET 0

#define SYSCTRL_CFG_SC_MAX2MIN_CYC_LEN       5
#define SYSCTRL_CFG_SC_MAX2MIN_CYC_OFFSET    8
#define SYSCTRL_CFG_SC_CDTC_REV_LEN          1
#define SYSCTRL_CFG_SC_CDTC_REV_OFFSET       7
#define SYSCTRL_CFG_SC_FDTC_REV_LEN          1
#define SYSCTRL_CFG_SC_FDTC_REV_OFFSET       6
#define SYSCTRL_CFG_SC_DTC_START_LEN         1
#define SYSCTRL_CFG_SC_DTC_START_OFFSET      5
#define SYSCTRL_CFG_SC_TIMING_CTRL_EN_LEN    1
#define SYSCTRL_CFG_SC_TIMING_CTRL_EN_OFFSET 4
#define SYSCTRL_CFG_SC_ONE2TWO_CYC_LEN       1
#define SYSCTRL_CFG_SC_ONE2TWO_CYC_OFFSET    3
#define SYSCTRL_CFG_SC_JM_RST_N_LEN          1
#define SYSCTRL_CFG_SC_JM_RST_N_OFFSET       2
#define SYSCTRL_CFG_SC_JM_CLK_EN_LEN         1
#define SYSCTRL_CFG_SC_JM_CLK_EN_OFFSET      0

#define SYSCTRL_CFG_SC_CDTC_GAP_LEN      5
#define SYSCTRL_CFG_SC_CDTC_GAP_OFFSET   11
#define SYSCTRL_CFG_SC_DTC_MARGIN_LEN    10
#define SYSCTRL_CFG_SC_DTC_MARGIN_OFFSET 0

#define SYSCTRL_CFG_SC_CDTC_CODE_INIT_LEN    8
#define SYSCTRL_CFG_SC_CDTC_CODE_INIT_OFFSET 8
#define SYSCTRL_CFG_SC_FDTC_CODE_INIT_LEN    8
#define SYSCTRL_CFG_SC_FDTC_CODE_INIT_OFFSET 0

#define SYSCTRL_CFG_SC_CDTC_CYC_LEN    5
#define SYSCTRL_CFG_SC_CDTC_CYC_OFFSET 8
#define SYSCTRL_CFG_SC_FDTC_CYC_LEN    5
#define SYSCTRL_CFG_SC_FDTC_CYC_OFFSET 0

#define SYSCTRL_CFG_SC_CDTC_STEP_LEN    6
#define SYSCTRL_CFG_SC_CDTC_STEP_OFFSET 8
#define SYSCTRL_CFG_SC_FDTC_STEP_LEN    7
#define SYSCTRL_CFG_SC_FDTC_STEP_OFFSET 0

#define SYSCTRL_CFG_SC_CDTC_LENGTH_LEN    8
#define SYSCTRL_CFG_SC_CDTC_LENGTH_OFFSET 8
#define SYSCTRL_CFG_SC_FDTC_LENGTH_LEN    8
#define SYSCTRL_CFG_SC_FDTC_LENGTH_OFFSET 0

#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_VALUE_LEN    16
#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_VALUE_OFFSET 0

#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_EN_LEN    1
#define SYSCTRL_CFG_PROBE_SYSTEM_COUNTER_EN_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE0_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE1_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE2_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE3_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE4_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE5_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE6_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE7_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE8_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE9_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE10_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE11_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE12_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE13_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE14_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR0_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR0_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR1_LEN    32
#define SYSCTRL_CFG_BROADCAST_DIE15_ADDR1_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_EN_LEN    16
#define SYSCTRL_CFG_BROADCAST_EN_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_CORE_EVENT_LEN    32
#define SYSCTRL_CFG_BROADCAST_CORE_EVENT_OFFSET 0



#define SYSCTRL_CFG_PLL6_LOCK_LEN    1
#define SYSCTRL_CFG_PLL6_LOCK_OFFSET 1
#define SYSCTRL_CFG_PLL1_LOCK_LEN    1
#define SYSCTRL_CFG_PLL1_LOCK_OFFSET 0

#define SYSCTRL_CFG_PLL_ON_LEN    1
#define SYSCTRL_CFG_PLL_ON_OFFSET 0

#define SYSCTRL_CFG_SYS_MODE_LEN    4
#define SYSCTRL_CFG_SYS_MODE_OFFSET 0

#define SYSCTRL_CFG_WARM_RST_ACKED_LEN    1
#define SYSCTRL_CFG_WARM_RST_ACKED_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_MBIGEN_LEN    1
#define SYSCTRL_CFG_ICG_ST_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_FTE_LEN    1
#define SYSCTRL_CFG_ICG_ST_FTE_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_GPIO_LEN    3
#define SYSCTRL_CFG_ICG_ST_GPIO_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_DDRC_LEN    2
#define SYSCTRL_CFG_ICG_ST_DDRC_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_ICG_ST_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_ICG_ST_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_SMMU_TRANS_LEN    1
#define SYSCTRL_CFG_ICG_ST_SMMU_TRANS_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_SDMAM_LEN    1
#define SYSCTRL_CFG_ICG_ST_SDMAM_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_PROBE_LEN    1
#define SYSCTRL_CFG_ICG_ST_PROBE_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_WDOG_LEN    20
#define SYSCTRL_CFG_ICG_ST_WDOG_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_ICG_ST_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_SFC2X_LEN      1
#define SYSCTRL_CFG_ICG_ST_SFC2X_OFFSET   2
#define SYSCTRL_CFG_ICG_ST_SFC1X_LEN      1
#define SYSCTRL_CFG_ICG_ST_SFC1X_OFFSET   1
#define SYSCTRL_CFG_ICG_ST_SFC_BUS_LEN    1
#define SYSCTRL_CFG_ICG_ST_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_TIMER0_LEN    32
#define SYSCTRL_CFG_ICG_ST_TIMER0_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_TIMER1_LEN    28
#define SYSCTRL_CFG_ICG_ST_TIMER1_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_SEC_TIMER_LEN    2
#define SYSCTRL_CFG_ICG_ST_SEC_TIMER_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_REF_LEN    1
#define SYSCTRL_CFG_ICG_ST_REF_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_GPIO_DB_LEN    1
#define SYSCTRL_CFG_ICG_ST_GPIO_DB_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_DJTAG_LEN    1
#define SYSCTRL_CFG_ICG_ST_DJTAG_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_ICG_ST_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_HPM_LEN    1
#define SYSCTRL_CFG_ICG_ST_HPM_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_SYSCNT_LEN    1
#define SYSCTRL_CFG_ICG_ST_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_ULTRASOC_LEN    1
#define SYSCTRL_CFG_ICG_ST_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_ICG_ST_CHIE_MON_LEN    1
#define SYSCTRL_CFG_ICG_ST_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_ICG_ST_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_ICG_ST_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_ICG_ST_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_ICG_ST_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_ICG_ST_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_MBIST_DDRC_HHA_LEN    2
#define SYSCTRL_CFG_ICG_ST_MBIST_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_MESH_LEN    1
#define SYSCTRL_CFG_ICG_ST_MESH_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_ICG_ST_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_ICG_ST_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_ICG_ST_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_ST_L3D1_OFFSET 0

#define SYSCTRL_CFG_ICG_ST_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_ICG_ST_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_MBIGEN_LEN    1
#define SYSCTRL_CFG_SRST_ST_MBIGEN_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_SDMAM_LEN    1
#define SYSCTRL_CFG_SRST_ST_SDMAM_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_FTE_LEN    1
#define SYSCTRL_CFG_SRST_ST_FTE_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_GPIO_LEN    3
#define SYSCTRL_CFG_SRST_ST_GPIO_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_ST_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_DDRC_EXMBIST_LEN    2
#define SYSCTRL_CFG_SRST_ST_DDRC_EXMBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_DDRC_HHA_LEN    1
#define SYSCTRL_CFG_SRST_ST_DDRC_HHA_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_SFC1X_LEN      1
#define SYSCTRL_CFG_SRST_ST_SFC1X_OFFSET   2
#define SYSCTRL_CFG_SRST_ST_SFC2X_LEN      1
#define SYSCTRL_CFG_SRST_ST_SFC2X_OFFSET   1
#define SYSCTRL_CFG_SRST_ST_SFC_BUS_LEN    1
#define SYSCTRL_CFG_SRST_ST_SFC_BUS_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_TIMER0_LEN    32
#define SYSCTRL_CFG_SRST_ST_TIMER0_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_TIEMR1_LEN    28
#define SYSCTRL_CFG_SRST_ST_TIEMR1_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_TIMER_SEC_LEN    2
#define SYSCTRL_CFG_SRST_ST_TIMER_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_WDOG_LEN    20
#define SYSCTRL_CFG_SRST_ST_WDOG_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_WDOG_SEC_LEN    2
#define SYSCTRL_CFG_SRST_ST_WDOG_SEC_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_PHY_DDRC_LEN    2
#define SYSCTRL_CFG_SRST_ST_PHY_DDRC_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_ULTRASOC_LEN    1
#define SYSCTRL_CFG_SRST_ST_ULTRASOC_OFFSET 1
#define SYSCTRL_CFG_SRST_ST_CHIE_MON_LEN    1
#define SYSCTRL_CFG_SRST_ST_CHIE_MON_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_STATUS_LEN    1
#define SYSCTRL_CFG_SRST_ST_STATUS_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_DCIP_CORE_LEN       1
#define SYSCTRL_CFG_SRST_ST_DCIP_CORE_OFFSET    2
#define SYSCTRL_CFG_SRST_ST_DCIP_BCBIST1_LEN    1
#define SYSCTRL_CFG_SRST_ST_DCIP_BCBIST1_OFFSET 1
#define SYSCTRL_CFG_SRST_ST_DCIP_BCBIST0_LEN    1
#define SYSCTRL_CFG_SRST_ST_DCIP_BCBIST0_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_DJTAG_LEN    1
#define SYSCTRL_CFG_SRST_ST_DJTAG_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_FUNC_MBIST_LEN    1
#define SYSCTRL_CFG_SRST_ST_FUNC_MBIST_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_HPM_LEN    1
#define SYSCTRL_CFG_SRST_ST_HPM_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_SYSCNT_LEN    1
#define SYSCTRL_CFG_SRST_ST_SYSCNT_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_MBIST_HHA1_LEN    2
#define SYSCTRL_CFG_SRST_ST_MBIST_HHA1_OFFSET 2
#define SYSCTRL_CFG_SRST_ST_MBIST_HHA0_LEN    2
#define SYSCTRL_CFG_SRST_ST_MBIST_HHA0_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_FMETA_TEST_RD_LEN    1
#define SYSCTRL_CFG_SRST_ST_FMETA_TEST_RD_OFFSET 1
#define SYSCTRL_CFG_SRST_ST_FMETA_TEST_WR_LEN    1
#define SYSCTRL_CFG_SRST_ST_FMETA_TEST_WR_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_ST_L3D1_OFFSET 0

#define SYSCTRL_CFG_SRST_ST_MBIST_L3D1_LEN    1
#define SYSCTRL_CFG_SRST_ST_MBIST_L3D1_OFFSET 0

#define SYSCTRL_CFG_GIC_NOCMT_IRQ_AND_LEN    1
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_AND_OFFSET 2
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_OR_LEN     1
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_OR_OFFSET  1
#define SYSCTRL_CFG_GIC_NOCMT_RST_OUT_LEN    1
#define SYSCTRL_CFG_GIC_NOCMT_RST_OUT_OFFSET 0

#define SYSCTRL_CFG_GIC_NOCMT_IRQ_STATUS_LEN    16
#define SYSCTRL_CFG_GIC_NOCMT_IRQ_STATUS_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_DATA_READY_LEN    1
#define SYSCTRL_CFG_TSENSOR_DATA_READY_OFFSET 17
#define SYSCTRL_CFG_TSENSOR_DATA_CLK_LEN      1
#define SYSCTRL_CFG_TSENSOR_DATA_CLK_OFFSET   16
#define SYSCTRL_CFG_TSENSOR_DATA_OUT_LEN      16
#define SYSCTRL_CFG_TSENSOR_DATA_OUT_OFFSET   0

#define SYSCTRL_CFG_TSENSOR_TEMP_VALID_LEN    1
#define SYSCTRL_CFG_TSENSOR_TEMP_VALID_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_TEMP_SAMPLE_LEN    32
#define SYSCTRL_CFG_TSENSOR_TEMP_SAMPLE_OFFSET 0

#define SYSCTRL_CFG_TEST_OUT_CORE_LEN          8
#define SYSCTRL_CFG_TEST_OUT_CORE_OFFSET       22
#define SYSCTRL_CFG_DFF_STATE_CORE_LEN         2
#define SYSCTRL_CFG_DFF_STATE_CORE_OFFSET      20
#define SYSCTRL_CFG_DFF_LOCATION_CORE_LEN      14
#define SYSCTRL_CFG_DFF_LOCATION_CORE_OFFSET   6
#define SYSCTRL_CFG_MID_FLAG_NOW_CORE_LEN      1
#define SYSCTRL_CFG_MID_FLAG_NOW_CORE_OFFSET   5
#define SYSCTRL_CFG_MID_FLAG_CORE_LEN          1
#define SYSCTRL_CFG_MID_FLAG_CORE_OFFSET       4
#define SYSCTRL_CFG_OUTER_FLAG_NOW_CORE_LEN    1
#define SYSCTRL_CFG_OUTER_FLAG_NOW_CORE_OFFSET 3
#define SYSCTRL_CFG_OUTER_FLAG_CORE_LEN        1
#define SYSCTRL_CFG_OUTER_FLAG_CORE_OFFSET     2
#define SYSCTRL_CFG_INNER_FLAG_NOW_CORE_LEN    1
#define SYSCTRL_CFG_INNER_FLAG_NOW_CORE_OFFSET 1
#define SYSCTRL_CFG_INNER_FLAG_CORE_LEN        1
#define SYSCTRL_CFG_INNER_FLAG_CORE_OFFSET     0

#define SYSCTRL_CFG_FLAG_NOW_BCBIST4_LEN    1
#define SYSCTRL_CFG_FLAG_NOW_BCBIST4_OFFSET 3
#define SYSCTRL_CFG_FLAG_BCBIST4_LEN        1
#define SYSCTRL_CFG_FLAG_BCBIST4_OFFSET     2
#define SYSCTRL_CFG_FLAG_NOW_BCBIST0_LEN    1
#define SYSCTRL_CFG_FLAG_NOW_BCBIST0_OFFSET 1
#define SYSCTRL_CFG_FLAG_BCBIST0_LEN        1
#define SYSCTRL_CFG_FLAG_BCBIST0_OFFSET     0

#define SYSCTRL_CFG_MEM_ECC_STATUS_ULTRASOC_LEN    4
#define SYSCTRL_CFG_MEM_ECC_STATUS_ULTRASOC_OFFSET 0

#define SYSCTRL_CFG_JM_CODE_A_LEN    8
#define SYSCTRL_CFG_JM_CODE_A_OFFSET 8
#define SYSCTRL_CFG_JM_CODE_B_LEN    8
#define SYSCTRL_CFG_JM_CODE_B_OFFSET 0

#define SYSCTRL_CFG_JM_CODE_C_LEN    8
#define SYSCTRL_CFG_JM_CODE_C_OFFSET 8
#define SYSCTRL_CFG_JM_CODE_D_LEN    8
#define SYSCTRL_CFG_JM_CODE_D_OFFSET 0

#define SYSCTRL_CFG_JM_CODE_E_LEN           8
#define SYSCTRL_CFG_JM_CODE_E_OFFSET        8
#define SYSCTRL_CFG_TEST_DTC_CURR_ST_LEN    3
#define SYSCTRL_CFG_TEST_DTC_CURR_ST_OFFSET 4
#define SYSCTRL_CFG_JM_OVERFLOW_LEN         1
#define SYSCTRL_CFG_JM_OVERFLOW_OFFSET      3
#define SYSCTRL_CFG_JM_UNDERFLOW_LEN        1
#define SYSCTRL_CFG_JM_UNDERFLOW_OFFSET     2
#define SYSCTRL_CFG_TEST_COMP_LEN           1
#define SYSCTRL_CFG_TEST_COMP_OFFSET        1
#define SYSCTRL_CFG_JM_DTC_MEA_DONE_LEN     1
#define SYSCTRL_CFG_JM_DTC_MEA_DONE_OFFSET  0

#define SYSCTRL_CFG_JM_CODE_MAX_LEN    8
#define SYSCTRL_CFG_JM_CODE_MAX_OFFSET 8
#define SYSCTRL_CFG_JM_CODE_MIN_LEN    8
#define SYSCTRL_CFG_JM_CODE_MIN_OFFSET 0

#define SYSCTRL_CFG_SC_EXT_INT_POLARITY_ST_LEN    9
#define SYSCTRL_CFG_SC_EXT_INT_POLARITY_ST_OFFSET 0

#define SYSCTRL_CFG_SC_EXT_INT_MASK_ST_LEN    9
#define SYSCTRL_CFG_SC_EXT_INT_MASK_ST_OFFSET 0

#define SYSCTRL_CFG_MBIST_CPUI_DATAOUT_LEN    32
#define SYSCTRL_CFG_MBIST_CPUI_DATAOUT_OFFSET 0

#define SYSCTRL_CFG_PLL6_UNLOCK_LEN               1
#define SYSCTRL_CFG_PLL6_UNLOCK_OFFSET            2
#define SYSCTRL_CFG_PLL6_UNLOCK_INT_STATUS_LEN    1
#define SYSCTRL_CFG_PLL6_UNLOCK_INT_STATUS_OFFSET 1
#define SYSCTRL_CFG_PLL1_UNLOCK_INT_STATUS_LEN    1
#define SYSCTRL_CFG_PLL1_UNLOCK_INT_STATUS_OFFSET 0

#define SYSCTRL_CFG_DJTAG_TIMEOUT_INT_STATUS_LEN    1
#define SYSCTRL_CFG_DJTAG_TIMEOUT_INT_STATUS_OFFSET 0

#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_INT_STATUS_LEN    1
#define SYSCTRL_CFG_TSENSOR_ULTRA_OVER_INT_STATUS_OFFSET 2
#define SYSCTRL_CFG_TSENSOR_OVER_INT_STATUS_LEN          1
#define SYSCTRL_CFG_TSENSOR_OVER_INT_STATUS_OFFSET       1
#define SYSCTRL_CFG_TSENSOR_UNDER_INT_STATUS_LEN         1
#define SYSCTRL_CFG_TSENSOR_UNDER_INT_STATUS_OFFSET      0

#define SYSCTRL_CFG_XTAL_ON_LEN    1
#define SYSCTRL_CFG_XTAL_ON_OFFSET 0

#define SYSCTRL_CFG_XTAL_PLL_TIMEOUT_LEN    1
#define SYSCTRL_CFG_XTAL_PLL_TIMEOUT_OFFSET 0

#define SYSCTRL_CFG_SC_ITIR0_TST_LEN    13
#define SYSCTRL_CFG_SC_ITIR0_TST_OFFSET 0

#define SYSCTRL_CFG_SC_ITOR_TST_LEN    11
#define SYSCTRL_CFG_SC_ITOR_TST_OFFSET 0

#define SYSCTRL_CFG_SC_CNT_DATA_LEN    25
#define SYSCTRL_CFG_SC_CNT_DATA_OFFSET 0

#define SYSCTRL_CFG_BROADCAST_BERROR_LEN     1
#define SYSCTRL_CFG_BROADCAST_BERROR_OFFSET  8
#define SYSCTRL_CFG_SYSCNT_CURR_STAT_LEN     4
#define SYSCTRL_CFG_SYSCNT_CURR_STAT_OFFSET  4
#define SYSCTRL_CFG_AXI_SYSCNT_WR_ERR_LEN    1
#define SYSCTRL_CFG_AXI_SYSCNT_WR_ERR_OFFSET 0

#define SYSCTRL_CFG_DJTAG_SEC_ACC_EN_LEN    1
#define SYSCTRL_CFG_DJTAG_SEC_ACC_EN_OFFSET 0

#define SYSCTRL_CFG_DJTAG_MSTR_ADDR_LEN    31
#define SYSCTRL_CFG_DJTAG_MSTR_ADDR_OFFSET 0

#define SYSCTRL_CFG_DJTAG_MSTR_DATA_LEN    32
#define SYSCTRL_CFG_DJTAG_MSTR_DATA_OFFSET 0

#define SYSCTRL_CFG_DJTAG_MSTR_DISABLE_LEN    1
#define SYSCTRL_CFG_DJTAG_MSTR_DISABLE_OFFSET 31
#define SYSCTRL_CFG_DJTAG_NOR_CFG_EN_LEN      1
#define SYSCTRL_CFG_DJTAG_NOR_CFG_EN_OFFSET   30
#define SYSCTRL_CFG_DJTAG_MSTR_WR_LEN         1
#define SYSCTRL_CFG_DJTAG_MSTR_WR_OFFSET      29
#define SYSCTRL_CFG_DEBUG_MODULE_SEL_LEN      8
#define SYSCTRL_CFG_DEBUG_MODULE_SEL_OFFSET   16
#define SYSCTRL_CFG_CHAIN_UNIT_CFG_EN_LEN     16
#define SYSCTRL_CFG_CHAIN_UNIT_CFG_EN_OFFSET  0

#define SYSCTRL_CFG_DJTAG_MSTR_START_EN_LEN    1
#define SYSCTRL_CFG_DJTAG_MSTR_START_EN_OFFSET 0

#define SYSCTRL_CFG_DJTAG_CPUI_PIPE_EN_LEN          1
#define SYSCTRL_CFG_DJTAG_CPUI_PIPE_EN_OFFSET       8
#define SYSCTRL_CFG_DJTAG_MSTR_PIPE_WAIT_NUM_LEN    7
#define SYSCTRL_CFG_DJTAG_MSTR_PIPE_WAIT_NUM_OFFSET 0

#define SYSCTRL_CFG_DJTAG_TMOUT_LEN    32
#define SYSCTRL_CFG_DJTAG_TMOUT_OFFSET 0

#define SYSCTRL_CFG_DJTAG_SEC_MODE_LEN    1
#define SYSCTRL_CFG_DJTAG_SEC_MODE_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_SEC_ACC_EN_LEN    1
#define SYSCTRL_CFG_AXI_MSTR_SEC_ACC_EN_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_CACHE_LEN      4
#define SYSCTRL_CFG_AXI_MSTR_CACHE_OFFSET   28
#define SYSCTRL_CFG_AXI_USER_SNPATTR_LEN    1
#define SYSCTRL_CFG_AXI_USER_SNPATTR_OFFSET 27
#define SYSCTRL_CFG_AXI_USER_PKG_LEN        1
#define SYSCTRL_CFG_AXI_USER_PKG_OFFSET     26
#define SYSCTRL_CFG_AXI_USER_FNA_LEN        1
#define SYSCTRL_CFG_AXI_USER_FNA_OFFSET     25
#define SYSCTRL_CFG_AXI_USER_FA_LEN         1
#define SYSCTRL_CFG_AXI_USER_FA_OFFSET      24
#define SYSCTRL_CFG_AXI_USER_STRMID_LEN     24
#define SYSCTRL_CFG_AXI_USER_STRMID_OFFSET  0

#define SYSCTRL_CFG_AXI_MSTR_WDATA0_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_WDATA0_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_WDATA1_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_WDATA1_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_WDATA2_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_WDATA2_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_WDATA3_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_WDATA3_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_QOS_LEN    4
#define SYSCTRL_CFG_AXI_MSTR_QOS_OFFSET 4
#define SYSCTRL_CFG_AXI_MSTR_WR_LEN     1
#define SYSCTRL_CFG_AXI_MSTR_WR_OFFSET  0

#define SYSCTRL_CFG_AXI_MSTR_ADDR0_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_ADDR0_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_ADDR1_LEN    32
#define SYSCTRL_CFG_AXI_MSTR_ADDR1_OFFSET 0

#define SYSCTRL_CFG_AXI_MSTR_START_EN_LEN    1
#define SYSCTRL_CFG_AXI_MSTR_START_EN_OFFSET 0

#define SYSCTRL_CFG_DJTAG_NS_ALLOW_LEN    1
#define SYSCTRL_CFG_DJTAG_NS_ALLOW_OFFSET 0

#define SYSCTRL_CFG_BOOT_64B_MUXED_LEN    16
#define SYSCTRL_CFG_BOOT_64B_MUXED_OFFSET 16
#define SYSCTRL_CFG_BOOT_SEL_MUXED_LEN    2
#define SYSCTRL_CFG_BOOT_SEL_MUXED_OFFSET 0

#define SYSCTRL_CFG_PAD_MPCORE_SEL_LEN    1
#define SYSCTRL_CFG_PAD_MPCORE_SEL_OFFSET 28
#define SYSCTRL_CFG_PAD_IODIE_TYPE_LEN    1
#define SYSCTRL_CFG_PAD_IODIE_TYPE_OFFSET 24
#define SYSCTRL_CFG_PAD_PROBE_MODE_LEN    1
#define SYSCTRL_CFG_PAD_PROBE_MODE_OFFSET 20
#define SYSCTRL_CFG_PAD_RST_MODE_LEN      1
#define SYSCTRL_CFG_PAD_RST_MODE_OFFSET   16
#define SYSCTRL_CFG_PAD_BOOT_SEL_LEN      3
#define SYSCTRL_CFG_PAD_BOOT_SEL_OFFSET   8
#define SYSCTRL_CFG_PAD_DIE_ID_LEN        2
#define SYSCTRL_CFG_PAD_DIE_ID_OFFSET     4
#define SYSCTRL_CFG_PAD_SOCKET_ID_LEN     2
#define SYSCTRL_CFG_PAD_SOCKET_ID_OFFSET  0

#define SYSCTRL_CFG_LAST_RST_STATUS_LEN    20
#define SYSCTRL_CFG_LAST_RST_STATUS_OFFSET 0

#define SYSCTRL_CFG_BOARD_CFG_INFO_LEN    22
#define SYSCTRL_CFG_BOARD_CFG_INFO_OFFSET 0

#define SYSCTRL_CFG_EFUSE_HARD_REPAIR_DONE1_LEN    1
#define SYSCTRL_CFG_EFUSE_HARD_REPAIR_DONE1_OFFSET 1
#define SYSCTRL_CFG_EFUSE_HARD_REPAIR_DONE0_LEN    1
#define SYSCTRL_CFG_EFUSE_HARD_REPAIR_DONE0_OFFSET 0

#define SYSCTRL_CFG_PAD_JTAG_AUTH_RES_IN_LEN    1
#define SYSCTRL_CFG_PAD_JTAG_AUTH_RES_IN_OFFSET 2
#define SYSCTRL_CFG_DFT_DISABLE_LEN             1
#define SYSCTRL_CFG_DFT_DISABLE_OFFSET          1
#define SYSCTRL_CFG_DJTAG_DISABLE_LEN           1
#define SYSCTRL_CFG_DJTAG_DISABLE_OFFSET        0

#define SYSCTRL_CFG_SYSCTRL_CFG_VERSION0_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_VERSION0_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_CFG_MAGIC_WORD_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_MAGIC_WORD_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG0_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG0_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG1_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG1_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG2_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG2_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG3_LEN    32
#define SYSCTRL_CFG_SYSCTRL_CFG_ECO_CFG3_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA0_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA0_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA1_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA1_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA2_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA2_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA3_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA3_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA4_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA4_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA5_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA5_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA6_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA6_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA7_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA7_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA8_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA8_OFFSET 0

#define SYSCTRL_CFG_DJTAG_RD_DATA9_LEN    32
#define SYSCTRL_CFG_DJTAG_RD_DATA9_OFFSET 0

#define SYSCTRL_CFG_RDATA_CHANGED_LEN    10
#define SYSCTRL_CFG_RDATA_CHANGED_OFFSET 16
#define SYSCTRL_CFG_DEBUG_BUS_EN_LEN     1
#define SYSCTRL_CFG_DEBUG_BUS_EN_OFFSET  9
#define SYSCTRL_CFG_DJTAG_OP_DONE_LEN    1
#define SYSCTRL_CFG_DJTAG_OP_DONE_OFFSET 8
#define SYSCTRL_CFG_UNIT_CONFLICT_LEN    8
#define SYSCTRL_CFG_UNIT_CONFLICT_OFFSET 0

#define SYSCTRL_CFG_AXI_RD_DATA0_LEN    32
#define SYSCTRL_CFG_AXI_RD_DATA0_OFFSET 0

#define SYSCTRL_CFG_AXI_RD_DATA1_LEN    32
#define SYSCTRL_CFG_AXI_RD_DATA1_OFFSET 0

#define SYSCTRL_CFG_AXI_RD_DATA2_LEN    32
#define SYSCTRL_CFG_AXI_RD_DATA2_OFFSET 0

#define SYSCTRL_CFG_AXI_RD_DATA3_LEN    32
#define SYSCTRL_CFG_AXI_RD_DATA3_OFFSET 0

#define SYSCTRL_CFG_AXI_OP_CONFLICT_LEN    1
#define SYSCTRL_CFG_AXI_OP_CONFLICT_OFFSET 3
#define SYSCTRL_CFG_AXI_WR_ERROR_LEN       1
#define SYSCTRL_CFG_AXI_WR_ERROR_OFFSET    2
#define SYSCTRL_CFG_AXI_RD_ERROR_LEN       1
#define SYSCTRL_CFG_AXI_RD_ERROR_OFFSET    1
#define SYSCTRL_CFG_AXI_OP_DONE_LEN        1
#define SYSCTRL_CFG_AXI_OP_DONE_OFFSET     0

#define SYSCTRL_CFG_SC_NORESET_0_LEN    32
#define SYSCTRL_CFG_SC_NORESET_0_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_1_LEN    32
#define SYSCTRL_CFG_SC_NORESET_1_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_2_LEN    32
#define SYSCTRL_CFG_SC_NORESET_2_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_3_LEN    32
#define SYSCTRL_CFG_SC_NORESET_3_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_4_LEN    32
#define SYSCTRL_CFG_SC_NORESET_4_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_5_LEN    32
#define SYSCTRL_CFG_SC_NORESET_5_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_6_LEN    32
#define SYSCTRL_CFG_SC_NORESET_6_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_7_LEN    32
#define SYSCTRL_CFG_SC_NORESET_7_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_8_LEN    32
#define SYSCTRL_CFG_SC_NORESET_8_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_9_LEN    32
#define SYSCTRL_CFG_SC_NORESET_9_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_10_LEN    32
#define SYSCTRL_CFG_SC_NORESET_10_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_11_LEN    32
#define SYSCTRL_CFG_SC_NORESET_11_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_12_LEN    32
#define SYSCTRL_CFG_SC_NORESET_12_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_13_LEN    32
#define SYSCTRL_CFG_SC_NORESET_13_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_14_LEN    32
#define SYSCTRL_CFG_SC_NORESET_14_OFFSET 0

#define SYSCTRL_CFG_SC_NORESET_15_LEN    32
#define SYSCTRL_CFG_SC_NORESET_15_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_LOCK_LEN    32
#define SYSCTRL_CFG_SYSCTRL_LOCK_OFFSET 0

#define SYSCTRL_CFG_SYSCTRL_UNLOCK_LEN    32
#define SYSCTRL_CFG_SYSCTRL_UNLOCK_OFFSET 0

#define SYSCTRL_CFG_PROBE_MUX_SEL_LEN    4
#define SYSCTRL_CFG_PROBE_MUX_SEL_OFFSET 0

#define SYSCTRL_CFG_ECO_RSV0_LEN    32
#define SYSCTRL_CFG_ECO_RSV0_OFFSET 0

#define SYSCTRL_CFG_ECO_RSV1_LEN    32
#define SYSCTRL_CFG_ECO_RSV1_OFFSET 0

#define SYSCTRL_CFG_ECO_RSV2_LEN    32
#define SYSCTRL_CFG_ECO_RSV2_OFFSET 0

#define SYSCTRL_CFG_ECO_RSV3_LEN    32
#define SYSCTRL_CFG_ECO_RSV3_OFFSET 0

#define SYSCTRL_CFG_PROTOTYPE_CLK_LEN    32
#define SYSCTRL_CFG_PROTOTYPE_CLK_OFFSET 0

#define SYSCTRL_CFG_PROTOTYPE_RST_N_LEN    32
#define SYSCTRL_CFG_PROTOTYPE_RST_N_OFFSET 0

#define SYSCTRL_CFG_SC_MONITOR_TEST0_LEN    32
#define SYSCTRL_CFG_SC_MONITOR_TEST0_OFFSET 0

#define SYSCTRL_CFG_SC_MONITOR_TEST1_LEN    32
#define SYSCTRL_CFG_SC_MONITOR_TEST1_OFFSET 0

#define SYSCTRL_CFG_SPECIAL_CODE_LEN    12
#define SYSCTRL_CFG_SPECIAL_CODE_OFFSET 20
#define SYSCTRL_CFG_CHIP_NAME_LEN       16
#define SYSCTRL_CFG_CHIP_NAME_OFFSET    4
#define SYSCTRL_CFG_CHIP_VERSION_LEN    4
#define SYSCTRL_CFG_CHIP_VERSION_OFFSET 0

#define SYSCTRL_CFG_SC_VER_NUM_LEN    32
#define SYSCTRL_CFG_SC_VER_NUM_OFFSET 0

#endif // __SYSCTRL_CFG_REG_OFFSET_FIELD_H__
