// ****************************************************************************** 
// Copyright     :  Copyright (C) 2019, Hisilicon Technologies Co. Ltd.
// File name     :  ts_secure_reg_offset_field.h
// Department    :  CAD Development Department
// Author        : huawei
// Version       :  1.0
// Date          :  2013/3/10
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.2 
// History       : huawei 2019/01/26 15:17:25 Create file
// ******************************************************************************

#ifndef __TS_SECURE_REG_OFFSET_FIELD_H__
#define __TS_SECURE_REG_OFFSET_FIELD_H__

#define TS_SECURE_TS_FCM_LOCAL_CORE3_NS_LEN    1
#define TS_SECURE_TS_FCM_LOCAL_CORE3_NS_OFFSET 7
#define TS_SECURE_TS_FCM_LOCAL_CORE2_NS_LEN    1
#define TS_SECURE_TS_FCM_LOCAL_CORE2_NS_OFFSET 6
#define TS_SECURE_TS_FCM_LOCAL_CORE1_NS_LEN    1
#define TS_SECURE_TS_FCM_LOCAL_CORE1_NS_OFFSET 5
#define TS_SECURE_TS_FCM_LOCAL_CORE0_NS_LEN    1
#define TS_SECURE_TS_FCM_LOCAL_CORE0_NS_OFFSET 4
#define TS_SECURE_TS_SYSCTRL_NS_LEN            1
#define TS_SECURE_TS_SYSCTRL_NS_OFFSET         0

#define TS_SECURE_SECURE1_LEN                27
#define TS_SECURE_SECURE1_OFFSET             5
#define TS_SECURE_DBGCONNECTED_FCM_LEN       1
#define TS_SECURE_DBGCONNECTED_FCM_OFFSET    4
#define TS_SECURE_TS_AWUSER_NS_LEN           1
#define TS_SECURE_TS_AWUSER_NS_OFFSET        3
#define TS_SECURE_TS_ARUSER_NS_LEN           1
#define TS_SECURE_TS_ARUSER_NS_OFFSET        2
#define TS_SECURE_SC_AW_SECURE_ENABLE_LEN    1
#define TS_SECURE_SC_AW_SECURE_ENABLE_OFFSET 1
#define TS_SECURE_SC_AR_SECURE_ENABLE_LEN    1
#define TS_SECURE_SC_AR_SECURE_ENABLE_OFFSET 0

#define TS_SECURE_TS_BS_ARMID_LEN     6
#define TS_SECURE_TS_BS_ARMID_OFFSET  24
#define TS_SECURE_TS_BS_AWMID_LEN     6
#define TS_SECURE_TS_BS_AWMID_OFFSET  16
#define TS_SECURE_TS_CPU_ARMID_LEN    6
#define TS_SECURE_TS_CPU_ARMID_OFFSET 8
#define TS_SECURE_TS_CPU_AWMID_LEN    6
#define TS_SECURE_TS_CPU_AWMID_OFFSET 0

#define TS_SECURE_SECURE3_LEN                28
#define TS_SECURE_SECURE3_OFFSET             4
#define TS_SECURE_SPNIDEN_FCM_DISABLE_LEN    1
#define TS_SECURE_SPNIDEN_FCM_DISABLE_OFFSET 3
#define TS_SECURE_SPIDEN_FCM_DISABLE_LEN     1
#define TS_SECURE_SPIDEN_FCM_DISABLE_OFFSET  2
#define TS_SECURE_NIDEN_FCM_DISABLE_LEN      1
#define TS_SECURE_NIDEN_FCM_DISABLE_OFFSET   1
#define TS_SECURE_DBGEN_FCM_DISABLE_LEN      1
#define TS_SECURE_DBGEN_FCM_DISABLE_OFFSET   0

#define TS_SECURE_SECURE4_LEN    32
#define TS_SECURE_SECURE4_OFFSET 0

#define TS_SECURE_SECURE5_LEN    32
#define TS_SECURE_SECURE5_OFFSET 0

#define TS_SECURE_SECURE6_LEN    32
#define TS_SECURE_SECURE6_OFFSET 0

#define TS_SECURE_SECURE7_LEN    32
#define TS_SECURE_SECURE7_OFFSET 0

#define TS_SECURE_SECURE8_LEN    32
#define TS_SECURE_SECURE8_OFFSET 0

#define TS_SECURE_SECURE9_LEN    32
#define TS_SECURE_SECURE9_OFFSET 0

#define TS_SECURE_SECURE10_LEN    32
#define TS_SECURE_SECURE10_OFFSET 0

#define TS_SECURE_SECURE11_LEN    32
#define TS_SECURE_SECURE11_OFFSET 0

#define TS_SECURE_SECURE12_LEN    32
#define TS_SECURE_SECURE12_OFFSET 0

#define TS_SECURE_SECURE13_LEN    32
#define TS_SECURE_SECURE13_OFFSET 0

#define TS_SECURE_SECURE14_LEN    32
#define TS_SECURE_SECURE14_OFFSET 0

#define TS_SECURE_SECURE15_LEN    32
#define TS_SECURE_SECURE15_OFFSET 0

#define TS_SECURE_SECURE16_LEN    32
#define TS_SECURE_SECURE16_OFFSET 0

#define TS_SECURE_SECURE17_LEN    32
#define TS_SECURE_SECURE17_OFFSET 0

#define TS_SECURE_SECURE18_LEN    32
#define TS_SECURE_SECURE18_OFFSET 0

#define TS_SECURE_SECURE19_LEN    32
#define TS_SECURE_SECURE19_OFFSET 0

#define TS_SECURE_SECURE20_LEN    32
#define TS_SECURE_SECURE20_OFFSET 0

#define TS_SECURE_SECURE21_LEN    32
#define TS_SECURE_SECURE21_OFFSET 0

#define TS_SECURE_SECURE22_LEN    32
#define TS_SECURE_SECURE22_OFFSET 0

#define TS_SECURE_SECURE23_LEN    32
#define TS_SECURE_SECURE23_OFFSET 0

#define TS_SECURE_SECURE24_LEN    32
#define TS_SECURE_SECURE24_OFFSET 0

#define TS_SECURE_SECURE25_LEN    32
#define TS_SECURE_SECURE25_OFFSET 0

#define TS_SECURE_SECURE26_LEN    32
#define TS_SECURE_SECURE26_OFFSET 0

#define TS_SECURE_SECURE27_LEN    32
#define TS_SECURE_SECURE27_OFFSET 0

#define TS_SECURE_SECURE28_LEN    32
#define TS_SECURE_SECURE28_OFFSET 0

#define TS_SECURE_SECURE29_LEN    32
#define TS_SECURE_SECURE29_OFFSET 0

#define TS_SECURE_SECURE30_LEN    32
#define TS_SECURE_SECURE30_OFFSET 0

#define TS_SECURE_SECURE31_LEN    32
#define TS_SECURE_SECURE31_OFFSET 0

#endif // __TS_SECURE_REG_OFFSET_FIELD_H__
