// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co. Ltd.
// File name     :  vitruvian perisub_reg_offset.h
// Project line  :  ICT
// Department    :  ICT Processor Chipset Development Dep
// Author        :  huawei
// Version       :  1.0
// Date          :  2017/11/13
// Description   :  The description of Hi1910 project
// Others        :  Generated automatically by nManager V4.2 
// History       :  huawei 2018/08/16 12:05:51 Create file
// ******************************************************************************

#ifndef __VITRUVIAN_PERISUB_REG_OFFSET_H__
#define __VITRUVIAN_PERISUB_REG_OFFSET_H__

/* VITRUVIAN PERISUB Base address of Module's Register */
#define SOC_VITRUVIAN_PERISUB_BASE                       (0x0)

/******************************************************************************/
/*                      SOC VITRUVIAN PERISUB Registers' Definitions                            */
/******************************************************************************/

#define SOC_VITRUVIAN_PERISUB_SFC_REG_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x89200000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_AXI_COM_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x89100000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SMB_HSLV_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x89000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SFC_MEM_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x90000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SDMAM_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x84090000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_DISP_REG_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x84060000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SCHE_REG_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x84050000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_FTE_REG_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x84040000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SMMU_REG3_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x84030000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SMMU_REG2_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x84020000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SMMU_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x84010000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SMMU_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x84000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_CFGBUS_SLV1_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x83000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_CFGBUS_CS1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x82000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_CFGBUS_SLV0_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x81000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_CFGBUS_CS0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x80000000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG9_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F90000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG8_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F80000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG7_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F70000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG6_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F60000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG5_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F50000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG4_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F40000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG3_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F30000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG2_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F20000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F10000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC2_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88F00000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG9_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E90000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG8_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E80000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG7_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E70000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG6_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E60000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG5_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E50000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG4_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E40000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG3_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E30000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG2_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E20000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E10000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC0_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88E00000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_I2C1_REG_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x88DE0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_I2C0_REG_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x88DD0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_GPIO1_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88D90000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_GPIO0_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88D80000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_UART1_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88D60000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_UART0_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88D50000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SPI_REG_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x88D30000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_AVS_REG_REG          (SOC_VITRUVIAN_PERISUB_BASE + 0x88D20000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_IOMUX0_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88D10000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SUBCTRL_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88D00000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER59_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88BB0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER58_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88BA0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER57_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B90000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER56_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B80000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER55_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B70000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER54_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B60000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER53_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B50000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER52_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B40000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER51_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B30000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER50_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B20000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER49_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B10000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER48_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88B00000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER47_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AF0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER46_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AE0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER45_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AD0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER44_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AC0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER43_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AB0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER42_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88AA0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER41_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A90000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER40_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A80000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER39_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A70000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER38_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A60000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER37_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A50000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER36_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A40000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER35_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A30000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER34_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A20000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER33_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A10000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER32_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88A00000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER31_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889F0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER30_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889E0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER29_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889D0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER28_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889C0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER27_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889B0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER26_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x889A0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER25_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88990000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER24_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88980000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER23_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88970000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER22_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88960000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER21_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88950000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER20_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88940000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER19_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88930000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER18_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88920000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER17_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88910000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER16_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x88900000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER15_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888F0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER14_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888E0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER13_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888D0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER12_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888C0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER11_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888B0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER10_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x888A0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER9_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88890000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER8_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88880000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER7_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88870000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER6_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88860000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER5_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88850000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER4_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88840000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER3_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88830000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER2_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88820000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER1_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88810000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TIMER0_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88800000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_OS_TIMER1_REG_REG    (SOC_VITRUVIAN_PERISUB_BASE + 0x88790000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_OS_TIMER0_REG_REG    (SOC_VITRUVIAN_PERISUB_BASE + 0x88780000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SECURE_WDG0_REG1_REG (SOC_VITRUVIAN_PERISUB_BASE + 0x88710000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SECURE_WDG0_REG0_REG (SOC_VITRUVIAN_PERISUB_BASE + 0x88700000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG19_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88670000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG19_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88660000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG18_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88650000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG18_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88640000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG17_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88630000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG17_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88620000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG16_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88610000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG16_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88600000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG15_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885F0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG15_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885E0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG14_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885D0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG14_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885C0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG13_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885B0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG13_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x885A0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG12_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88590000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG12_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88580000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG11_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88570000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG11_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88560000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG10_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88550000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG10_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88540000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG9_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88530000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG9_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88520000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG8_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88510000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG8_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88500000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG7_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884F0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG7_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884E0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG6_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884D0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG6_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884C0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG5_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884B0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG5_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x884A0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG4_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88490000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG4_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88480000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG3_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88470000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG3_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88460000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG2_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88450000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG2_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88440000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG1_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88430000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG1_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88420000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG0_REG1_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88410000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_WDG0_REG0_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88400000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG9_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88390000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG8_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88380000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG7_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88370000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG6_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88360000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG5_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88350000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG4_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88340000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG3_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88330000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG2_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88320000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88310000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC3_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88300000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG9_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88290000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG8_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88280000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG7_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88270000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG6_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88260000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG5_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88250000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG4_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88240000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG3_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88230000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG2_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88220000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG1_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88210000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_HBMC1_REG0_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x88200000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_DDRC1_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88110000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_DDRC0_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88100000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_MBIGEN_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x880D0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_TZPC_REG_REG         (SOC_VITRUVIAN_PERISUB_BASE + 0x880C0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_IOMUX1_REG_REG       (SOC_VITRUVIAN_PERISUB_BASE + 0x880A0000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_GPIO3_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88070000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_GPIO2_REG_REG        (SOC_VITRUVIAN_PERISUB_BASE + 0x88060000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SYSTEM_COUNTER_REG   (SOC_VITRUVIAN_PERISUB_BASE + 0x88020000) /* 基地址 */
#define SOC_VITRUVIAN_PERISUB_SYSCTRL_REG_REG      (SOC_VITRUVIAN_PERISUB_BASE + 0x80000000) /* 基地址 */

#endif // __VITRUVIAN PERISUB_REG_OFFSET_H__
