{
 "title": "DLTS群集统计",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "全部GPU",
   "type": "singlestat",
   "description": "Number of GPUs in the cluster.\n\nTODO: Currently it's showing k8s capacity. Ideally it should all underlying GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'}))  OR on() vector(0)",
     "legendFormat": "全部"
    }
   ]
  },
  {
   "title": "可分配的GPU",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_available{device_str='nvidia.com/gpu'}))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "不健康的GPU",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in k8s or marked as unschedulable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'}))  OR on() vector(0)) - (sum(avg by (host_ip) (k8s_node_device_allocatable{device_str='nvidia.com/gpu'})) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "分配的GPU",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs.\n\nTODO: Exclude unhealthy but in use GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) OR on() vector(0)",
     "legendFormat": "已分配"
    }
   ]
  },
  {
   "title": "活动的GPU",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization > 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的GPU",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "全部NPU",
   "type": "singlestat",
   "description": "Number of NPUs in the cluster.\n\nTODO: Currently it's showing k8s capacity. Ideally it should all underlying NPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "全部"
    }
   ]
  },
  {
   "title": "可分配的NPU",
   "type": "singlestat",
   "description": "Number of NPUs immediately assignable to jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_available{device_str='npu.huawei.com/NPU'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "不健康的NPU",
   "type": "singlestat",
   "description": "Number of unhealthy NPUs in k8s or marked as unschedulable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (sum(avg by (host_ip) (k8s_node_device_allocatable{device_str='npu.huawei.com/NPU'})) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "分配的NPU",
   "type": "singlestat",
   "description": "Number of NPUs assigned to jobs.\n\nTODO: Exclude unhealthy but in use NPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "已分配"
    }
   ]
  },
  {
   "title": "活动的NPU",
   "type": "singlestat",
   "description": "Number of assigned NPUs having utilization > 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的NPU",
   "type": "singlestat",
   "description": "Number of assigned NPUs having utilization 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "随时间推移的设备", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "设备",
   "type": "graph",
   "description": "Device numbers in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'}))",
     "legendFormat": "全部GPU"
    },
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_available{device_str='nvidia.com/gpu'}))",
     "legendFormat": "可安排GPU"
    },
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'})) - sum(avg by (host_ip) (k8s_node_device_allocatable{device_str='nvidia.com/gpu'}))",
     "legendFormat": "不健康GPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) OR on() vector(0)",
     "legendFormat": "已分配GPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "活动的GPU"
    },
    {
     "expr": "(count (avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "空闲的GPU"
    },
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "全部NPU"
    },
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_available{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "可分配NPU"
    },
    {
     "expr": "sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'})) - sum(avg by (host_ip) (k8s_node_device_allocatable{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "不健康NPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "已分配NPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "活动NPU"
    },
    {
     "expr": "(count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "空闲NPU"
    }
   ]
  },
  { "title": "GPU 利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "集群GPU利用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'})))"
    }
   ]
  },
  {
   "title": "随着时间的推移集群GPU利用率",
   "type": "singlestat",
   "description": "Average GPU utlization across all GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'}))"
    }
   ]
  },
  {
   "title": "分配的GPU使用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "随时间分配的GPU使用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})",
     "legendFormat": "分配的GPU实用程序"
    }
   ]
  },
  {
   "title": "主动GPU利用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>=0)",
     "legendFormat": "分配的GPU实用程序"
    }
   ]
  },
  {
   "title": "随着时间的推移主动使用GPU",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>=0)",
     "legendFormat": "分配的GPU实用程序"
    }
   ]
  },
  { "title": "NPU利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "集群NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all NPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'})))"
    }
   ]
  },
  {
   "title": "随着时间的推移集群NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utlization across all NPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'}))"
    }
   ]
  },
  {
   "title": "分配的NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "随时间分配的NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "分配的NPU实用程序"
    }
   ]
  },
  {
   "title": "主动NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>=0)",
     "legendFormat": "分配的NPU实用程序"
    }
   ]
  },
  {
   "title": "随时间推移主动NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>=0)",
     "legendFormat": "分配的NPU实用程序"
    }
   ]
  },
  { "title": "随着时间的推移设备利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "设备利用率",
   "type": "graph",
   "description": "Average Device utilization in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='nvidia.com/gpu'}))",
     "legendFormat": "集群(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})",
     "legendFormat": "已安排(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "活动(GPU)"
    },
    {
     "expr": "sum(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'})) / sum(avg by (host_ip) (k8s_node_device_total{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "集群(NPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "已安排(NPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "活动(NPU)"
    }
   ]
  },
  { "title": "设备碎片", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "可分配设备的节点数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Node count" }
   ],
   "targets": [
    {
     "expr": "count_values(\"gpu_available\", avg by (uuid) (k8s_node_device_available{device_str='nvidia.com/gpu'}))",
     "legendFormat": "GPU:{{'{{'}}gpu_available{{'}}'}}"
    },
    {
     "expr": "count_values(\"npu_available\", avg by (uuid) (k8s_node_device_available{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "NPU:{{'{{'}}npu_available{{'}}'}}"
    }
   ]
  },
  { "title": "工作状态延迟", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "未批准->已排队",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})"
    }
   ]
  },
  {
   "title": "排队->排程",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})"
    }
   ]
  },
  {
   "title": "排程->执行中",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})"
    }
   ]
  },
  { "title": "随时间变化的工作状态延迟", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "平均工作状态更改延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})",
     "legendFormat": "未批准->已排队"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})",
     "legendFormat": "排队->排程"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})",
     "legendFormat": "排程->执行中"
    }
   ]
  },
  { "title": "每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "GPU内存",
   "type": "singlestat",
   "description": "Average GPU memory utilization per GPU across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'})) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "分配的GPU实用程序"
    }
   ]
  },
  {
   "title": "NPU内存",
   "type": "singlestat",
   "description": "Average GPU memory utilization per GPU across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 74 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'})) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "分配的NPU实用程序"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "内存",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 74 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘读取",
   "type": "singlestat",
   "description": "Average disk read rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘写入",
   "type": "singlestat",
   "description": "Average disk write rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输入",
   "type": "singlestat",
   "description": "Average network inbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输出",
   "type": "singlestat",
   "description": "Average network outbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  { "title": "随时间推移每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "每个活动设备的设备内存",
   "type": "graph",
   "description": "Average Device memory utilization per active Device in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'})) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum((avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'})) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "每个活动设备的CPU",
   "type": "graph",
   "description": "Average CPU usage per active Device in the cluster over time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum(task_cpu_percent) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "每个活动设备的内存",
   "type": "graph",
   "description": "Average memory usage per active Device in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum(task_mem_usage_byte) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "每个活动设备的磁盘I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "In(NPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "Out(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的网络I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(avg by (uuid) (task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    }
   ]
  },
  { "title": "VC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "VC分配的设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='nvidia.com/gpu'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='npu.huawei.com/NPU'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC分配比例",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='nvidia.com/gpu'})) by (vc_name) / ignoring (vc_name) group_left sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='nvidia.com/gpu'}))",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='npu.huawei.com/NPU'})) by (vc_name) / ignoring (vc_name) group_left sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC分配的设备利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (uuid,vc_name) (task_device_percent{device_str='nvidia.com/gpu'})) by (vc_name) / sum(avg by (uuid,vc_name) (k8s_vc_device_total{device_str='nvidia.com/gpu'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(avg by (uuid,vc_name) (task_device_percent{device_str='npu.huawei.com/NPU'})) by (vc_name) / sum(avg by (uuid,vc_name) (k8s_vc_device_total{device_str='npu.huawei.com/NPU'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC分配的设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid,vc_name) (task_device_percent{device_str='nvidia.com/gpu'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(avg by (uuid,vc_name) (task_device_percent{device_str='npu.huawei.com/NPU'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC分配设备比率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid,vc_name) (task_device_percent{device_str='nvidia.com/gpu'})) by (vc_name) / sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='nvidia.com/gpu'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(avg by (uuid,vc_name) (task_device_percent{device_str='npu.huawei.com/NPU'})) by (vc_name) / sum(avg by (instance,vc_name) (k8s_vc_device_total{device_str='npu.huawei.com/NPU'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC分配的设备利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC有源设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid,vc_name)(task_device_percent{device_str='nvidia.com/gpu'}>0)) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(avg by (uuid,vc_name)(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC有源设备比率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid,vc_name)(task_device_percent{device_str='nvidia.com/gpu'}>0)) by (vc_name) / count(avg by (uuid,vc_name)(task_device_percent{device_str='nvidia.com/gpu'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(avg by (uuid,vc_name)(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) by (vc_name) / count(avg by (uuid,vc_name)(task_device_percent{device_str='npu.huawei.com/NPU'})) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC主动GPU利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}"
    }
   ]
  }
 ]
}