{
 "title": "DLTS用户统计",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "label_values(task_cpu_percent, username)"
   },
   {
    "name": "vc_name",
    "query": "label_values(task_cpu_percent{username=\"$username\"}, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "分配的GPU",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "主动式GPU",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的GPU",
   "type": "singlestat",
   "description": "Number of idle GPUs under  the user.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "分配的NPU",
   "type": "singlestat",
   "description": "Number of NPUs assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "有源NPU",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的NPU",
   "type": "singlestat",
   "description": "Number of idle GPUs under  the user.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "随时间推移的设备", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)",
     "legendFormat": "GPU已分配"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "GPU活动"
    },
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "GPU空闲"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "NPU已分配"
    },
    {
     "expr": "count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "NPU活动"
    },
    {
     "expr": "(count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid)(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "NPU空闲"
    }
   ]
  },
  { "title": "GPU使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "分配的GPU使用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "随时间分配的GPU使用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "主动GPU利用率",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  {
   "title": "随着时间的推移主动使用GPU",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  { "title": "NPU利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "分配的NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned GPUs to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "随时间分配的NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "主动NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  {
   "title": "随时间推移主动NPU利用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) assigned to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  { "title": "随着时间的推移设备利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "设备利用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "GPU已分配"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "GPU活动"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "GPU VC 已分配"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "GPU VC 活动"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "NPU 已分配"
    },
    {
     "expr": "avg(task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "NPU 活动"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "NPU VC 已分配"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "NPU VC 活动"
    }
   ]
  },
  { "title": "每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "GPU内存",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (avg by (uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU内存",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "内存",
   "type": "singlestat",
   "description": "Memory usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 45 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘读取",
   "type": "singlestat",
   "description": "Block In Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘写入",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输入",
   "type": "singlestat",
   "description": "Network Inbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输出",
   "type": "singlestat",
   "description": "Network Outbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 45 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  { "title": "随时间推移每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "每个活动设备的设备内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid) ((task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) / 100)) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的磁盘I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的网络I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{username=\"$username\",vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "User Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance) (rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    }
   ]
  }
 ]
}