{
 "title": "DLTS Cluster Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPUs",
   "type": "singlestat",
   "description": "Number of GPUs in the cluster.\n\nTODO: Currently it's showing k8s capacity. Ideally it should all underlying GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_node_device_total{device_str='nvidia.com/gpu'})  OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Assignable GPUs",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_node_device_available{device_str='nvidia.com/gpu'})  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Unhealthy GPUs",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in k8s or marked as unschedulable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(k8s_node_device_total{device_str='nvidia.com/gpu'})  OR on() vector(0)) - (sum(k8s_node_device_allocatable{device_str='nvidia.com/gpu'}) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs.\n\nTODO: Exclude unhealthy but in use GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization > 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{device_str='nvidia.com/gpu'}) OR on() vector(0)) - (count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total NPUs",
   "type": "singlestat",
   "description": "Number of NPUs in the cluster.\n\nTODO: Currently it's showing k8s capacity. Ideally it should all underlying NPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Assignable NPUs",
   "type": "singlestat",
   "description": "Number of NPUs immediately assignable to jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_node_device_available{device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Unhealthy NPUs",
   "type": "singlestat",
   "description": "Number of unhealthy NPUs in k8s or marked as unschedulable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (sum(k8s_node_device_allocatable{device_str='npu.huawei.com/NPU'}) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Assigned NPUs",
   "type": "singlestat",
   "description": "Number of NPUs assigned to jobs.\n\nTODO: Exclude unhealthy but in use NPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Active NPUs",
   "type": "singlestat",
   "description": "Number of assigned NPUs having utilization > 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle NPUs",
   "type": "singlestat",
   "description": "Number of assigned NPUs having utilization 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "Device Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Devices",
   "type": "graph",
   "description": "Device numbers in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_node_device_total{device_str='nvidia.com/gpu'})",
     "legendFormat": "Total GPU"
    },
    {
     "expr": "sum(k8s_node_device_available{device_str='nvidia.com/gpu'})",
     "legendFormat": "Assignable GPU"
    },
    {
     "expr": "sum(k8s_node_device_total{device_str='nvidia.com/gpu'}) - sum(k8s_node_device_allocatable{device_str='nvidia.com/gpu'})",
     "legendFormat": "Unhealthy GPU"
    },
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "Assigned GPU"
    },
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "Active GPU"
    },
    {
     "expr": "(count(task_device_percent{device_str='nvidia.com/gpu'}) OR on() vector(0)) - (count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0))",
     "legendFormat": "Idle GPU"
    },
    {
     "expr": "sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Total NPU"
    },
    {
     "expr": "sum(k8s_node_device_available{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assignable NPU"
    },
    {
     "expr": "sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'}) - sum(k8s_node_device_allocatable{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Unhealthy NPU"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "Assigned NPU"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "Active NPU"
    },
    {
     "expr": "(count(task_device_percent{device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))",
     "legendFormat": "Idle NPU"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cluster GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_device_percent{device_str='nvidia.com/gpu'}) / sum(k8s_node_device_total{device_str='nvidia.com/gpu'}))"
    }
   ]
  },
  {
   "title": "Cluster GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utlization across all GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_device_percent{device_str='nvidia.com/gpu'}) / sum(k8s_node_device_total{device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  { "title": "NPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cluster NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all NPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_device_percent{device_str='npu.huawei.com/NPU'}) / sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'}))"
    }
   ]
  },
  {
   "title": "Cluster NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utlization across all NPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_device_percent{device_str='npu.huawei.com/NPU'}) / sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assigned NPU Util"
    }
   ]
  },
  {
   "title": "Active NPU Utilization",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "Assigned NPU Util"
    }
   ]
  },
  {
   "title": "Active NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "Assigned NPU Util"
    }
   ]
  },
  { "title": "Device Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Device Utilization",
   "type": "graph",
   "description": "Average Device utilization in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_device_percent{device_str='nvidia.com/gpu'}) / sum(k8s_node_device_total{device_str='nvidia.com/gpu'})",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'})",
     "legendFormat": "Assigned(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "Active(GPU)"
    },
    {
     "expr": "sum(task_device_percent{device_str='npu.huawei.com/NPU'}) / sum(k8s_node_device_total{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Cluster(NPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assigned(NPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "Active(NPU)"
    }
   ]
  },
  { "title": "Device Fragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Node Count By Assignable Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Node count" }
   ],
   "targets": [
    {
     "expr": "count_values(\"gpu_available\", k8s_node_device_available{device_str='nvidia.com/gpu'})",
     "legendFormat": "GPU:{{'{{'}}gpu_available{{'}}'}}"
    },
    {
     "expr": "count_values(\"npu_available\", k8s_node_device_available{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "NPU:{{'{{'}}npu_available{{'}}'}}"
    }
   ]
  },
  { "title": "Job Status Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "unapproved -> queued",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})"
    }
   ]
  },
  {
   "title": "queued -> scheduling",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})"
    }
   ]
  },
  {
   "title": "scheduling -> running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 61 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})"
    }
   ]
  },
  { "title": "Job Status Latency Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Average Job Status Change Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})",
     "legendFormat": "unapproved -> queued"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})",
     "legendFormat": "queued -> scheduling"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})",
     "legendFormat": "scheduling -> running"
    }
   ]
  },
  { "title": "Resource Per Active Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization per GPU across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'}) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  {
   "title": "NPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization per GPU across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 74 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'}) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Assigned NPU Util"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(task_device_percent{device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 74 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Average disk read rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Average disk write rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Average network inbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Average network outbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 74 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Resource Per Active Device Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Device Memory Per Active Device",
   "type": "graph",
   "description": "Average Device memory utilization per active Device in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'}) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum((task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'}) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "CPU Per Active Device",
   "type": "graph",
   "description": "Average CPU usage per active Device in the cluster over time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(task_device_percent{device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum(task_cpu_percent) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) / 100) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "Memory Per Active Device",
   "type": "graph",
   "description": "Average memory usage per active Device in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "NPU"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "In(NPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))",
     "legendFormat": "Out(NPU)"
    }
   ]
  },
  {
   "title": "Network I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))",
     "legendFormat": "Out(GPU)"
    }
   ]
  },
  { "title": "VC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "VC Allocated Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_vc_device_total{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Allocation Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_vc_device_total{device_str='nvidia.com/gpu'}) by (vc_name) / ignoring (vc_name) group_left sum(k8s_vc_device_total{device_str='nvidia.com/gpu'})",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}) by (vc_name) / ignoring (vc_name) group_left sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Allocated Device Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_device_percent{device_str='nvidia.com/gpu'}) by (vc_name) / sum(k8s_vc_device_total{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "sum(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name) / sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Assigned Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Assignment Device Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name) / sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name) / sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Assigned Device Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Active Devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}>0) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Active Device Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{device_str='nvidia.com/gpu'}>0) by (vc_name) / count(task_device_percent{device_str='nvidia.com/gpu'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) by (vc_name) / count(task_device_percent{device_str='npu.huawei.com/NPU'}) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "VC Active GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{device_str='nvidia.com/gpu'}>0) by (vc_name)",
     "legendFormat": "{{'{{'}}vc_name{{'}}'}}"
    }
   ]
  }
 ]
}