{
 "title": "DLTS VC Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vc_name",
    "label": "vc_name",
    "query": "label_values(k8s_vc_device_total, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocated",
   "type": "singlestat",
   "description": "Number of Devices allocated to the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assignable",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assigned",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0% in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)) - (count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Allocated",
   "type": "singlestat",
   "description": "Number of Devices allocated to the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assignable",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assigned",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0% in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "Device Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Devices",
   "type": "graph",
   "description": "GPU numbers in the VC over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Allocated GPU"
    },
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Assignable GPU"
    },
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Unhealthy GPU"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)",
     "legendFormat": "Assigned GPU"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0)",
     "legendFormat": "Active GPU"
    },
    {
     "expr": "(count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)) - (count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) OR on() vector(0))",
     "legendFormat": "Idle GPU"
    },
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Allocated NPU"
    },
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assignable NPU"
    },
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Unhealthy NPU"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)",
     "legendFormat": "Assigned NPU"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0)",
     "legendFormat": "Active NPU"
    },
    {
     "expr": "(count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)) - (count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) OR on() vector(0))",
     "legendFormat": "Idle NPU"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Allocated GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs allocated to the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / sum(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Allocated GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / sum(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)"
    }
   ]
  },
  { "title": "NPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Allocated NPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs allocated to the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / sum(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Allocated NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / sum(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Assigned NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "Active NPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)"
    }
   ]
  },
  {
   "title": "Active NPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)"
    }
   ]
  },
  { "title": "Device Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Device Utilization",
   "type": "graph",
   "description": "Average GPU utilization in the VC over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / sum(k8s_vc_device_total{device_str='nvidia.com/gpu'})",
     "legendFormat": "Allocated GPU"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Assigned GPU"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "Active GPU"
    },
    {
     "expr": "sum(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / sum(k8s_vc_device_total{device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Allocated NPU"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assigned NPU"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "Active NPU"
    }
   ]
  },
  { "title": "Resource Per Active Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 53 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 53 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Average disk read rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Average disk write rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Average network inbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Average network outbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Resource Per Active Device Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }
  },
  {
   "title": "Device Memory Per Active Device",
   "type": "graph",
   "description": "Average GPU memory utilization per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum((task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'}) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum((task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    },
    {
     "expr": "(sum((task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'}) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "CPU Per Active Device",
   "type": "graph",
   "description": "Average CPU usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(task_cpu_percent) / count(task_device_percent{device_str='nvidia.com/gpu'}>0) / 100) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) / 100) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    },
    {
     "expr": "(sum(task_cpu_percent) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0) / 100) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "Memory Usage Per Device",
   "type": "graph",
   "description": "Average memory usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC(GPU)"
    },
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC(NPU)"
    },
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster In(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    },
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster In(NPU)"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out(NPU)"
    }
   ]
  },
  {
   "title": "Network I/O Per Active Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster In(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_device_percent{device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out(GPU)"
    },
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    },
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster In(NPU)"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out(NPU)"
    }
   ]
  },
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Assigned Device By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "Assigned Device Utilization By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "Active Device By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(GPU)"
    },
    {
     "expr": "count(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(NPU)"
    }
   ]
  },
  {
   "title": "Active Device Utilization By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) by (username)",
     "legendFormat": "{{'{{'}}username{{'}}'}}(NPU)"
    }
   ]
  }
 ]
}